### ISSUE TITLE
storeDir directive does not work with  AWS S3 path

### ISSUE THREAD

**Issue by syousry6** [nextflow-io/nextflow#2904] opened 2022-05-25 20:26 UTC
Hello Everyone,

We are running nextflow pipelines on AWS EKS cluster, We use the storeDir directive together with an AWS S3 path to store the results for processes.
We are getting the following error everytime we run a process with storeDir as follows
```
Missing output file(s) `L1.Aligned.sortedByCoord.out.bam` expected by process `alignment`
```

- Here is the error in .nextflow.log
```
Process `alignment (A09-00159428-B-RNA-013:L1)` is unable to find [S3Path]: `/k8s-temporal-efs/results/210811_NB501495_0936_AH555LBGXK/A09-00159428-B-RNA-013/align/L1/L1.Aligned.sortedByCoord.out.bam` (pattern: `L1.Aligned.sortedByCoord.out.bam`)
```

- Here is the process configuration in [modular.nf](http://modular.nf/)
```
params.results = "s3://k8s-temporal-efs/results/"

process alignment {
echo true
tag { sample_name + ":" + lane_id }
container '183449805178.dkr.ecr.us-east-1.amazonaws.com/nextflow-container:latest'

pod = [nodeSelector: "${config.instanceType.alignment}, uuid=${params.uuid}"]
cpus "${config.clustercores.alignment}" 
memory "${config.clustermem.alignment}" 

// limit here to avoid overloading the S3 download pool
maxForks 16
maxRetries 3
errorStrategy { sleep(Math.pow(2, task.attempt) * 15 as long); return 'retry' }

storeDir { "${params.results}/$runid/$sample_name/align/$lane_id" }
//publishDir { "${params.results}/$runid/$sample_name/align/$lane_id" }

input:
file reference
set sample_name, sample_id, lane_id, file(read1), file(read2) from fastqs
//val k from kickoff.first()
val k from kickoff

output:
set sample_name, file ("${lane_id}.Aligned.sortedByCoord.out.bam") into alignments
set sample_name, file ("${lane_id}.Chimeric.out.sam") into fusion_sams
set sample_name, file ("${lane_id}.Chimeric.out.junction") into fusion_jxns

set sample_name, file ("${lane_id}.Log.final.out") into star_logs

set sample_name, sample_id, lane_id into meta

script:
template "alignment.sh"
}
```

- Here is the content of alignment.sh
```
#!/bin/bash

source $baseDir/templates/common.sh
script_begin ${task.process} "$sample_name"

{

	echo "runid = ${runid}"
	echo "sample_name = ${sample_name}"
	echo "sample_id = ${sample_id}"
	echo "lane_id = ${lane_id}"
	echo "readFilesIn = ${read1} ${read2}"
	echo "uuid = ${params.uuid}"
	echo "reference = ${reference}"
	echo "params_reference = ${params.reference}"

	echo "starting STAR at `date`"

	echo "making temporary directory ${params.javatmp}/${params.uuid}"
	mkdir -p ${params.javatmp}/${params.uuid}

	echo "removing temp dir in case of a retry..."
	rm -rf ${params.javatmp}/${params.uuid}/STAR-${runid}-${sample_name}.${lane_id}

	$params.star_path/STAR \
		--genomeLoad ${params.config.alignment.genomeLoad} \
		--genomeDir ${params.reference} \
		--readFilesIn ${read1} ${read2} \
		--readFilesCommand ${params.config.alignment.readFilesCommand} \
		--outReadsUnmapped ${params.config.alignment.outReadsUnmapped} \
		--outSAMunmapped  ${params.config.alignment.outSAMunmapped} \
		--outSAMtype ${params.config.alignment.outSAMtype} \
		--outSAMattrRGline ID:$sample_name.$lane_id LB:library PL:Illumina SM:$sample_name \
		--limitBAMsortRAM ${params.config.memory.alignmentBAMSort} \
		--runThreadN ${params.config.alignment.runThreadN} \
		--chimSegmentMin ${params.config.alignment.chimSegmentMin}  \
		--chimJunctionOverhangMin ${params.config.alignment.chimJunctionOverhangMin} \
		--chimScoreMin ${params.config.alignment.chimScoreMin} \
		--chimScoreDropMax ${params.config.alignment.chimScoreDropMax} \
		--chimScoreSeparation ${params.config.alignment.chimScoreSeparation} \
		--chimScoreJunctionNonGTAG ${params.config.alignment.chimScoreJunctionNonGTAG} \
		--sjdbOverhang ${params.config.alignment.sjdbOverhang} \
		--seedSearchStartLmax ${params.config.alignment.seedSearchStartLmax} \
		--outFileNamePrefix ${lane_id}. \
		--outTmpDir ${params.javatmp}/${params.uuid}/STAR-${runid}-${sample_name}.${lane_id}
	ev=\$?

} 2>&1

script_exit
```

FYKI
If we tried to use publishDir instead of storeDir with the same bucket, we had no issues, which shows that it’s not a permissions issue. The problem with publishDir that it doesn’t let us use the cached results.

Nextflow version: 22.04.0
Operating system: Linux

**Comment by smplyayush** [comment] 2022-07-07 16:15
Changing` '$name' to "$name" i.e. adding double quotes to the parameter in .command.run fixes the issue. Need some one from Nextflow to add an urgent patch to fix this. This is blocking our active development since a month now.

nxf_unstage() { true cp .command.out /mnt/efs/ngs_scratch/workdir/210812_NB501331_0892_AH57FVBGXK/updated-path4/14/96e35fb77d096c4ca2d3291e49b398/.command.out || true cp .command.err /mnt/efs/ngs_scratch/workdir/210812_NB501331_0892_AH57FVBGXK/updated-path4/14/96e35fb77d096c4ca2d3291e49b398/.command.err || true cp .command.trace /mnt/efs/ngs_scratch/workdir/210812_NB501331_0892_AH57FVBGXK/updated-path4/14/96e35fb77d096c4ca2d3291e49b398/.command.trace || true [[ ${nxf_main_ret:=0} != 0 ]] && return IFS=$'\n' for name in $(eval "ls -1d L1.Aligned.sortedByCoord.out.bam L1.Chimeric.out.sam L1.Chimeric.out.junction L1.Log.final.out" | sort | uniq); do nxf_s3_upload '**$name**' s3://k8s-temporal-efs/results/210812_NB501331_0892_AH57FVBGXK/A01-00159459-VL45582-A-d/align/L1 || true done unset IFS }

**Comment by bentsherman** [comment] 2022-07-07 19:18
Possible duplicate of #2790

**Closed** 2022-07-11 19:29 UTC
Labels: storage/aws-s3
