### ISSUE TITLE
NF can't get job status from SGE.

### ISSUE THREAD

**Issue by HerderB** [nextflow-io/nextflow#1007] opened 2019-01-25 08:14 UTC
### Expected behavior and actual behavior

Normally, NF should communicate with SGE to keep track of job status and keep running while jobs are active. However, at the moment NF can't get the job status from SGE and Nextflow stops. The SGE job is still running at this point and finished correctly. Judging from the logs, it's having trouble reading the .exitcode file.

### Steps to reproduce the problem

Run a Nextflow process taking more than 10 minutes using SGE as the executor.

### Program output 

See nextflow.log.
[nextflow.log](https://github.com/nextflow-io/nextflow/files/2795157/nextflow.log)

### Environment 

* Nextflow version: 19.01.0
* Java version: openjdk version "1.8.0_191"
* Operating system: Linux

### Additional context

**Comment by pditommaso** [comment] 2019-01-25 09:18
The problem is that the `qstat` command does not return any output 

```
Jan-25 09:05:52.300 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SGE] getting queue (all.q) status > cmd: qstat -q all.q
Jan-25 09:05:52.413 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SGE] queue (all.q) status > cmd exit: 0

Jan-25 09:05:52.414 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SGE] queue (all.q) status >
  (empty)

```

Can you also provide the following file:

```
/mnt/nfs/testfolder/mark/data/nextflow_assembly/work/4b/612b29dbc1ae9efaf3f523b9aac065/.command.run
```

**Comment by HerderB** [comment] 2019-01-25 09:20
Here it is:
[command.run.txt](https://github.com/nextflow-io/nextflow/files/2795425/command.run.txt)

**Comment by HerderB** [comment] 2019-01-25 09:42
Shouldn't the command be qstat -q all.q -u '*' anyway?

**Comment by pditommaso** [comment] 2019-01-25 10:05
Why? it should fetch the status of jobs only submitted by the current user. Why NF should take check the status for other jobs ?

**Comment by pditommaso** [comment] 2019-01-30 07:14
I'm closing this because there's no more feedback. Feel free to comment/reopen if needed.

**Closed by pditommaso** 2019-01-30 07:14 UTC
Labels: triage/invalid
