### ISSUE TITLE
21.12.1-edge and later cause query string to be dropped from the URL-files

### ISSUE THREAD

**Issue by J-81** [nextflow-io/nextflow#3023] opened 2022-07-11 19:10 UTC
### Expected behavior and actual behavior

**Expected behavior:**
File instances include query string from initial URL string

**Actual behavior:**
File instances drop query strings from initial string of URL

### Steps to reproduce the problem

``` nextflow
nextflow.enable.dsl=2

/**************************************************
* ACTUAL WORKFLOW  ********************************
**************************************************/
workflow {
    input_url = channel.value(
        file("https://genelab-data.ndc.nasa.gov/genelab/static/media/dataset/GLDS-48_rna_seq_Mmus_C57-6J_LVR_GC_I_Rep1_M31_R1_raw.fastq.gz?version=1")
        )
    input_url | view { it.dump()} | splitFastq(decompress: true, limit: 2, by: 2) | view

}
```

### Failing under 21.12.1-edge (also failing on 22.04.4)
``` bash
gitpod /workspace/launch $ NXF_VER=21.12.1-edge nextflow run ./issue_demo.nf 
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
N E X T F L O W  ~  version 21.12.1-edge
Launching `./issue_demo.nf` [cheesy_lorenz] - revision: 76bc9c68f4
<nextflow.file.http.XPath@715e0c32 fs=nextflow.file.http.XFileSystem@e049d30d path=/genelab/static/media/dataset/GLDS-48_rna_seq_Mmus_C57-6J_LVR_GC_I_Rep1_M31_R1_raw.fastq.gz query=null>
Server returned HTTP response code: 500 for URL: https://genelab-data.ndc.nasa.gov/geode-py/ws/studies/GLDS-48/download?file=GLDS-48_rna_seq_Mmus_C57-6J_LVR_GC_I_Rep1_M31_R1_raw.fastq.gz&version=null
```

### Working under 21.10.6
``` bash
gitpod /workspace/launch $ NXF_VER=21.10.6 nextflow run ./issue_demo.nf 
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
N E X T F L O W  ~  version 21.10.6
Launching `./issue_demo.nf` [magical_nobel] - revision: 76bc9c68f4
<nextflow.file.http.XPath@cd417ffe fs=nextflow.file.http.XFileSystem@791014ca path=/genelab/static/media/dataset/GLDS-48_rna_seq_Mmus_C57-6J_LVR_GC_I_Rep1_M31_R1_raw.fastq.gz?version=1>
@J00113:34:H37JWBBXX:5:1101:1274:1000 1:N:0:ATGAGC
GGATGAACTCAGCTGCTCTTCCATTGTCAATAGCGATGCTCGCCTTTATC
+
AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
@J00113:34:H37JWBBXX:5:1101:3101:1000 1:N:0:ATGAGC
GTGTGAGTCAGCAGGGAGGTCTGGGTCTCATTATGAGGGGGCTTTACAAT
+
AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKK
```

### Environment 

* Nextflow version: Tested as occurring on [21.12.1-edge] and [22.04.4] 
* Java version: [Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)]
* Operating system: [Linux]
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by pditommaso** [comment] 2022-07-12 08:04
Duplicate of #2918. Solved by [43cc851](https://github.com/nextflow-io/nextflow/commit/43cc85118fda9dc5a1ff9a7bcd9f68bf440f6afd)

**Closed by pditommaso** 2022-07-12 08:04 UTC
