### ISSUE TITLE
LocalExecutor can randomly hang with no running task

### ISSUE THREAD

**Issue by austindoupnik** [nextflow-io/nextflow#191] opened 2016-06-27 23:53 UTC
I have seen a non-deterministic bug where execution of a nextflow workflow will hang indefinitely with a single log message repeating.

```
Jun-17 23:53:04.366 [Thread-5] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 0 -- first: null
Jun-17 23:58:04.385 [Thread-5] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 0 -- first: null
Jun-18 00:03:04.391 [Thread-5] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 0 -- first: null
Jun-18 00:08:04.484 [Thread-5] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 0 -- first: null
Jun-18 00:13:04.577 [Thread-5] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 0 -- first: null
```

**Comment by pditommaso** [comment] 2016-06-28 16:42
Please include the full `.nextflow.log` file of the run affected by this problem. Also, it would be important if you could provide a script that replicate the issue.

**Comment by austindoupnik** [comment] 2016-06-28 20:41
Alright I took a random stab at reproducing it and was actually able to. It is a bit weird though. The workflow is very simple, just 100 processes all sleeping then echoing "hello world" and one process which writes about `14m` with dd, here it is,

[helloworld.nf.txt](https://github.com/nextflow-io/nextflow/files/333769/helloworld.nf.txt)
[nextflow.config.txt](https://github.com/nextflow-io/nextflow/files/333770/nextflow.config.txt)

I then created a `tmpfs` volume,

```
mount -t tmpfs -o size=16m tmpfs /mnt/helloworld
```

Since it is nondetermenistic I had to run it in a while loop until it hung, it took maybe an hour or so

```
cd /mnt/helloworld
while true ; do rm -rf * .* && ~/nextflow-0.20.1-all ~/helloworld.nf; done
```

**Comment by austindoupnik** [comment] 2016-06-28 20:42
Also using docker containers here

**Comment by austindoupnik** [comment] 2016-06-28 20:55
Actually it looks like me reproduction above is useless, it is just `docker` getting wedged, not `nextflow`

**Comment by pditommaso** [comment] 2016-06-29 17:42
> Actually it looks like me reproduction above is useless, it is just docker getting wedged, not nextflow

@austindoupnik What do you mean?

**Comment by austindoupnik** [comment] 2016-06-29 17:45
It looks like not all docker containers are cleaned up and I end up with hundreds in the "Dead" state over time. At some point the docker daemon will stop responding to requests from the client. Sometimes the unix socket it uses to communicate with the client will actually disappear even though the daemon is still running

**Comment by pditommaso** [comment] 2016-06-29 17:50
I don't think the hang problem is related to containers usage. I would suggest to not use Docker to replicate the issue.

**Comment by austindoupnik** [comment] 2016-06-29 18:01
I don't think it is either. We have just seen the hang again while docker is in a perfectly stable state. Thanks!

**Comment by austindoupnik** [comment] 2016-06-29 18:21
I am attempting to get the stack trace for the hung nextflow process. My normal approach is to run `kill -3` which causes the `JVM` to dump the stack trace for all threads to `stdout` but this is not working.

I then install the `JDK` and tried to use `jstack` and received the following error,

```
3155: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding
```

Using the `-F` flag I see the following,

```
Attaching to process ID 3155, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.72-b15
Deadlock Detection:

java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f034001a000 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
        at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:166)
        at sun.jvm.hotspot.runtime.Threads.first(Threads.java:150)
        at sun.jvm.hotspot.runtime.DeadlockDetector.createThreadTable(DeadlockDetector.java:149)
        at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:56)
        at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
        at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:62)
        at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
        at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
        at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
        at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00007f034001a000
        at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
        at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
        at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:162)
        ... 17 more
Can't print deadlocks:Unable to deduce type of thread from address 0x00007f034001a000 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
        at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: java.lang.InternalError: Metadata does not appear to be polymorphic
        at sun.jvm.hotspot.types.basic.BasicTypeDataBase.findDynamicTypeForAddress(BasicTypeDataBase.java:278)
        at sun.jvm.hotspot.runtime.VirtualBaseConstructor.instantiateWrapperFor(VirtualBaseConstructor.java:102)
        at sun.jvm.hotspot.oops.Metadata.instantiateWrapperFor(Metadata.java:68)
        at sun.jvm.hotspot.memory.DictionaryEntry.klass(DictionaryEntry.java:71)
        at sun.jvm.hotspot.memory.DictionaryEntry.equals(DictionaryEntry.java:79)
        at sun.jvm.hotspot.memory.Dictionary.getEntry(Dictionary.java:99)
        at sun.jvm.hotspot.memory.Dictionary.find(Dictionary.java:87)
        at sun.jvm.hotspot.memory.SystemDictionary.find(SystemDictionary.java:159)
        at sun.jvm.hotspot.memory.SystemDictionary.find(SystemDictionary.java:151)
        at sun.jvm.hotspot.memory.SystemDictionary.getAbstractOwnableSynchronizerKlass(SystemDictionary.java:135)
        at sun.jvm.hotspot.runtime.ConcurrentLocksPrinter.fillLocks(ConcurrentLocksPrinter.java:66)
        at sun.jvm.hotspot.runtime.ConcurrentLocksPrinter.<init>(ConcurrentLocksPrinter.java:36)
        at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:71)
        at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
        at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
        at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
        ... 6 more
```

None of which seems particularly useful, but I thought I would keep you in the loop.

**Comment by pditommaso** [comment] 2016-06-29 18:26
This stack trace seems related to `jstack` which actually I've never used. 

You may want to give a try to [YourKit](http://www.yourkit.com) (or eventually VisualVM and Java Mission Control)

**Comment by austindoupnik** [comment] 2016-06-29 18:29
Yes it is related to `jstack`. All of those tools use the same communication mechanism, I have also tried `visualvm` and it hangs while trying to connect. I believe YourKit is a paid profiling tool, not sure about it's introspection capabilities.

**Comment by pditommaso** [comment] 2016-06-29 18:34
I've used successfully YourKit with Nextflow. Not sure, but there should be at least a trial version.

**Comment by austindoupnik** [comment] 2016-06-29 18:37
I just tried to fire up `visualvm` again and it just says "Cannot open application with pid 3155"

I have used `visualvm` and `jstack` with `nextflow` and it has worked in the past, this seems to be a very low level problem that has really wedged the `JVM`.

Oddly enough it is still printing log messages

**Comment by pditommaso** [comment] 2016-06-29 18:39
Still using 1.7.3? Did you give a try to the latest version?

**Comment by austindoupnik** [comment] 2016-06-29 18:49
Yeah this is with the latest version

**Comment by pditommaso** [comment] 2016-06-29 18:49
I see. Can you include the complete log file?

**Comment by austindoupnik** [comment] 2016-06-29 18:58
I can upload it after it has been deidentified, which is going to take a little while.

**Comment by austindoupnik** [comment] 2016-06-29 22:41
Here is the full log with process and filenames change

[Nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/340358/Nextflow.log.txt)

**Comment by austindoupnik** [comment] 2016-06-29 23:04
Is there any `JNI` code being used or any bytecode generation being done in `nextflow`?

**Comment by pditommaso** [comment] 2016-06-30 13:09
No, at least in the nextflow code base. I'm not 100% sure about some libraries used by it.

**Comment by austindoupnik** [comment] 2016-07-01 19:24
@pditommaso I think I may have tracked down a potential cause. Your code is quite clean so I was able to look through it fairly easily. Bear with my while I try to explain this.

It seems that each `process` will have a `StateObj` wrapped by an `Agent`, what I think can happen is that `incCompleted` is called before `incSubmitted`. This will cause the `else` branch in `incCompleted` to be taken throwing an exception. The `Agent` gathers these exceptions but they aren't looked up anywhere later it seems.

The reason that I think `incCompleted` can be called before `incSubmitted` is that `incCompleted` is that an `update` to the `Agent` to apply `incCompleted` is made in `TaskPollingMonitor.pollLoop > checkAllTasks > checkTaskStatus > finalizeTask > finalizeTask0`. The same thing is done for `incSubmitted` but it is done in the `TaskProcessorInterceptor.beforeRun` callback.

I believe that if the polling loop happens to run right after the process completes, but before the `beforeRun` method is called (due to randomness in thread scheduling) it is possible for `incCompleted` to be called first and cause an `IllegalStateException` to be thrown.

I have tested this by forcing `incCompleted` to always throw an exception and it seems to reproduce the behavior we are seeing (I also fixed a small typo in the exception message).

Here is the small patch,
```
diff --git a/src/main/groovy/nextflow/processor/StateObj.groovy b/src/main/groovy/nextflow/processor/StateObj.groovy
index 1cc4521..4d954be 100644
--- a/src/main/groovy/nextflow/processor/StateObj.groovy
+++ b/src/main/groovy/nextflow/processor/StateObj.groovy
@@ -61,11 +61,13 @@ class StateObj implements Serializable, Cloneable {
      * Increment the number of completed tasks
      */
     void incCompleted() {
+        /*
         if( completed < submitted )
             completed++

         else
-            throw new IllegalStateException("Processed messages ($submitted) cannot overcome received messages ($submitted)")
+        */
+            throw new IllegalStateException("Processed messages ($completed) cannot overcome received messages ($submitted)")
     }

     void poison() {
```

And the very simple workflow
```
process helloWorld {
        output:
                file "helloworld.txt"

        script:
                """
                        echo hello world > helloworld.txt
                """
}
```

Let me know if these seems reasonable (there might be something else forcing order between `incCompleted` and `incSubmitted` but I didn't see it), or if you need some more clarification from me.

If you can also suggest a fix I can start working on it. I will start to think about one as well.

Thanks!

**Comment by austindoupnik** [comment] 2016-07-01 21:20
Oh I forgot to mention that when an exception is thrown inside of a closure passed to the `Agent.update` method those exceptions will be accumulated by the `Agent` and can be seen using `Agent.getErrors`.

It seems like you may want to consider `Agent.hasErrors` as a termination condition and print the contents of `Agent.getErrors`.

**Comment by pditommaso** [comment] 2016-07-01 21:28
Thanks a lot for this detailed report. I need to review carefully your patch because this is a quite tricky piece of code. 

The best thing would be if you could provide a test case that replicates your issue, and showing that the patch proposed fix it.

**Comment by austindoupnik** [comment] 2016-07-01 21:31
The patch doesn't fix the issue actually, it just reproduces the bug consistently by forcing a condition that normal happens only due to a race. So it is the test case.

I was hoping to get some feedback from you on my debugging to see if I didn't miss anything! :)

**Comment by pditommaso** [comment] 2016-07-01 21:32
Can't verify it now. I work on this next week.

**Comment by austindoupnik** [comment] 2016-07-01 21:33
Thanks!

**Comment by austindoupnik** [comment] 2016-07-04 06:24
Actually looking a bit more I think I see how the ordering is enforced. It seems `beforeRun` is being called before the operator runs and adds the task to the list for the monitor to loop over.

**Comment by pditommaso** [comment] 2016-07-04 13:15
I've inspecting the log you have included. It looks like there are two processes (25 and 30) that never stop because they do not received the termination signal from the upstream process. This log is produced by a test case or a real script? Also how many processes there are in this script? 39 or more?

**Comment by austindoupnik** [comment] 2016-07-05 15:25
Yup that is the case. It is from a real script, and it succeeds *most* of the time. It will hang maybe 1/15.

I believe there are 38 processes (I didn't write the script).

Any ideas why it would report waiting for 0 tasks?

**Comment by pditommaso** [comment] 2016-07-06 09:39
I continues to wait because two process did not terminate correctly. I've uploaded a new snapshot fixing the bug https://github.com/nextflow-io/nextflow/issues/189 which could be related to your problem. You may want to give a try. To use it prepend the variable `NXF_VER=0.20.2-SNAPSHOT` to the usual nextflow command line.

**Comment by austindoupnik** [comment] 2016-07-06 15:09
Could that be non-deterministic though? That sounds like something that
will always fail

**Comment by pditommaso** [comment] 2016-07-06 15:13
Um, you are right. OK, I need to give a try to the example that you have included.

**Comment by pditommaso** [comment] 2016-07-11 12:46
I've run your test case for several hours. No way to reproduce the issue.  I'm thinking the best way manage this problem would be having a shared environment to replicate the issue. What about setting up  an EC2 instance with the code needed to replicate it? (same for #188)

**Comment by austindoupnik** [comment] 2016-07-11 15:57
Which test case? Throwing an exception in one of the `state` update Closures will always hang. The "helloworld" test case was hanging due to docker, and was a red herring.

**Comment by pditommaso** [comment] 2016-07-11 16:03
No, I was meaning the "helloworld.nf.txt" script. So, it was caused by Docker I would close this issue. Do you agree?

**Comment by austindoupnik** [comment] 2016-07-11 16:17
No that test cases hang was being caused by docker. This hang still happens while docker is functioning, I just don't have a test case to reproduce it.

I believe that it is related to exceptions being thrown in the `state` update Closures, since they are not handled anywhere and print no error message. If you try my most recent test case (the patch and trivial workflow) you will see this behavior

**Comment by pditommaso** [comment] 2016-07-11 17:23
Yes, I agree that that exceptions are really a bad idea, though I don't see how `incCompleted` can be invoked before `incSubmitted`. In any case I've replaced with a log debugging message that won't result in the process to hang. 

I've just uploaded a snapshot `0.20.2-SNAPSHOT build 3894` including this patch. I'm closing this issue. If you will continue to experience it, please reopen it.

**Comment by austindoupnik** [comment] 2016-07-11 17:24
Sounds great. Thanks!

**Closed by pditommaso** 2016-07-11 17:23 UTC
Labels: WIP
