### ISSUE TITLE
Access process input through map instead of array

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#653] opened 2018-04-11 20:27 UTC
As per my post in the Google Groups, I think it would be helpful to be able to access process inputs through a map (dictionary) instead of only an array. This would make it possible to use the same processing to conditionally work on output from a channel in which not all items have the same cardinality. Here is an example to show what I mean:

```
Channel.from( [ [caller: 'HaplotypeCaller', sampleID:'Sample1', sample_file:file('Sample1.txt')],
                [caller: 'MuTect2', tumorID:'Sample2', normalID: 'Sample3', sample_file:file('Sample2.txt')] ] )
        .into { samples; samples2 }
samples.subscribe { println "[samples] ${it}" }

process filter_data {
    tag "${sampleID}"
    echo true

    input:
    set val(caller: { it.get('caller') }), val(sampleID: { it.get('sampleID', null) }), val(tumorID: { it.get('tumorID', null) } ), val(normalID: { it.get('normalID', null) }), file(sample_file: { it.get('sample_file') }) from samples2

    if ( sampleID == null ) {
        sampleID = "${tumorID}.${normalID}"
    }

    output:
    set val(caller), val(sampleID), file(output_file) into filtered_data

    script:
    output_file = "${sampleID}.txt"
    if (caller == 'HaplotypeCaller')
        """
        echo "[filter_data] processing HaplotypeCaller file ${sample_file} for sample ${sampleID}"
        echo "processing goes here" > "${output_file}"
        """
    else if (caller ==  'MuTect2')
        """
        echo "[filter_data] processing MuTect2 file ${sample_file} for tumor sample ${tumorID} and normal sample ${normalID}"
        echo "processing goes here" > "${output_file}"
        """
    else
        error "Invalid caller: ${caller}"
}

```

Here, the values for `sampleID`, `tumorID`, and `normalID` would be optional input items, and if `sampleID` was not passed, then its `null` value gets replaced with a string created from `tumorID` and `normalID`. 

However, this example does not currently work:

```
./nextflow run main.nf
N E X T F L O W  ~  version 0.28.0
Launching `main.nf` [thirsty_swartz] - revision: 185c464a88
[samples] [caller:HaplotypeCaller, sampleID:Sample1, sample_file:/Users/kellys04/projects/nextflow-demos/test1/Sample1.txt]
[samples] [caller:MuTect2, tumorID:Sample2, normalID:Sample3, sample_file:/Users/kellys04/projects/nextflow-demos/test1/Sample2.txt]
ERROR ~ No such variable: caller

 -- Check script 'main.nf' at line: 11 or see '.nextflow.log' file for more details
make: *** [run] Error 1
```

It seems the 'key:value' attribute of the elements in the original map do not propagate through to the `input` statement. 

This would be helpful so that you could handle processing of channels with heterogeneous cardinality without having to duplicate every process in your workflow. Right now, I would have to create independent `process`es for each cardinality, despite them being functionally identical.

**Comment by pditommaso** [comment] 2018-04-23 13:14
Yes, this could be useful. I think this is a duplicate of #343, right?

**Comment by stevekm** [comment] 2018-04-23 14:03
Yeah for the most part.

**Comment by pditommaso** [comment] 2018-04-23 14:08
Ok, I will close this and continue the discussion there.

**Closed by pditommaso** 2018-04-23 14:08 UTC
