### ISSUE TITLE
Resuming nextflow causes duplicates within the trace.txt file and leads to a re-launch of most jobs even if successfully finished

### ISSUE THREAD

**Issue by mpml** [nextflow-io/nextflow#571] opened 2018-01-15 09:19 UTC
Hello, 

Some of my jobs were killed by my cluster manager (slurm) as exceeding a threshold time limit. I hence resumed my nextflow pipe with the -resume option. So far so good.

However, this change caused  duplicates within the "trace.txt" file and also leads to a re-launch of most jobs even if successfully finished in the first round of calculations. Here is for example a copy of the last 5 lines of the "trace.txt": 

```
2025    c1/b97231       26743001        calculate_summaries_statistics (1022)   CACHED  0       2018-01-14 21:28:06.009 2h 13m 58s      1h 55m 45s      180.9%  741.7 MB        2.4 GB  195.7 MB        120.5 MB
2025    c1/b97231       26743001        calculate_summaries_statistics (1022)   CACHED  0       2018-01-14 21:28:06.009 2h 13m 58s      1h 55m 45s      180.9%  741.7 MB        2.4 GB  195.7 MB        120.5 MB
2025    c1/b97231       26743001        calculate_summaries_statistics (1022)   CACHED  0       2018-01-14 21:28:06.009 2h 13m 58s      1h 55m 45s      180.9%  741.7 MB        2.4 GB  195.7 MB        120.5 MB
2025    c1/b97231       26743001        calculate_summaries_statistics (1022)   CACHED  0       2018-01-14 21:28:06.009 2h 13m 58s      1h 55m 45s      180.9%  741.7 MB        2.4 GB  195.7 MB        120.5 MB
2025    c1/b97231       26743001        calculate_summaries_statistics (1022)   CACHED  0       2018-01-14 21:28:06.009 2h 13m 58s      1h 55m 45s      180.9%  741.7 MB        2.4 GB  195.7 MB        120.5 MB
```

The only think I changed is the `nextflow.config` file. Which was: 

```
process{
    executor='slurm'
    queue = 'common,dedicated'
    clusterOptions = "--qos=fast"
    cache='deep'
    scratch=true
    errorStrategy='retry'
    maxRetries=1
}
executor {
    name = 'slurm'
    queueSize = 500
}
trace {
    enabled = true
    file = 'trace.txt'
}
timeline {
    enabled = true
    file = 'timeline.html'
}
dag {
    enabled = true
    file = 'dag.pdf'
}
```

Which I now changed to following to increase the time available for the jobs to finish successfully: 

```
process{
    executor='slurm'
    queue = 'common'
    clusterOptions = "--qos=normal"
    cache='deep'
    scratch=true
    errorStrategy='retry'
    maxRetries=2
}
executor {
    name = 'slurm'
    queueSize = 500
}
trace {
    enabled = true
    file = 'trace.txt'
}
timeline {
    enabled = true
    file = 'timeline.html'
}
dag {
    enabled = true
    file = 'dag.pdf'
}
```

Could you please tell me if this is normal behaviour of nextflow under this circumstances and if there is a workaround to avoid re-calculating most of the previous successful runs? Many thanks! 

Best, 
Mathieu

**Comment by pditommaso** [comment] 2018-01-15 14:14
No, it should not happen. Can you post the output of the command `nextflow log` ?

**Comment by pditommaso** [comment] 2018-01-16 09:48
Something very strange is happening, the log file contains planty of tasks having the same hash key: 

```
Jan-15 09:43:27.363 [Actor Thread 5] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (1)
Jan-15 09:43:27.363 [Actor Thread 37] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (12)
Jan-15 09:43:27.363 [Actor Thread 28] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (3)
Jan-15 09:43:27.363 [Actor Thread 26] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (2)
Jan-15 09:43:27.363 [Actor Thread 34] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (9)
Jan-15 09:43:27.364 [Actor Thread 33] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (8)
Jan-15 09:43:27.366 [Actor Thread 32] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (7)
Jan-15 09:43:27.366 [Actor Thread 30] INFO  nextflow.processor.TaskProcessor - [3e/7d2927] Cached process > calculate_summaries_statistics (5)
```

That's very likely  the cause why the trace contains duplicates of the same entry. This requires to be investigated carefully. Are you able to replicate the issue with a test case using a small dataset. That would help a lot to troubleshoot the prolem.

**Comment by mpml** [comment] 2018-01-16 10:40
OK, I'll try to replicate it. By the way, here is the output of the command _nextflow log_: 
TIMESTAMP               DURATION        RUN NAME                STATUS  REVISION ID     SESSION ID                              COMMAND                                                     
2018-01-13 23:50:39     6.3s            cheesy_wozniak          ERR     dd707f0df3      e162439e-1945-405f-b912-fee0e376058a    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf        
2018-01-13 23:51:39     11m 32s         spontaneous_caravaggio  ERR     dd707f0df3      69862974-f8dc-4c9e-9b16-5e6dc4d37801    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf        
2018-01-14 00:05:06     4m 35s          maniac_roentgen         ERR     dd707f0df3      69862974-f8dc-4c9e-9b16-5e6dc4d37801    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf -resume
2018-01-14 17:35:56     1m 54s          boring_curran           ERR     dd707f0df3      69862974-f8dc-4c9e-9b16-5e6dc4d37801    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf -resume
2018-01-14 17:39:14     1m 44s          special_mendel          ERR     d15fa28221      69862974-f8dc-4c9e-9b16-5e6dc4d37801    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf -resume
2018-01-14 17:43:17     2m 59s          hungry_ampere           ERR     d15fa28221      69862974-f8dc-4c9e-9b16-5e6dc4d37801    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf -resume
2018-01-14 17:52:02     -               silly_solvay            -       d15fa28221      69862974-f8dc-4c9e-9b16-5e6dc4d37801    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf -resume
2018-01-15 09:42:37     -               happy_mahavira          -       d15fa28221      69862974-f8dc-4c9e-9b16-5e6dc4d37801    nextflow BD-SIRD-PN_regression_pipeline_v20180113.nf -resume

**Comment by mpml** [comment] 2018-01-19 12:11
I think I figured out the issue: there was a mistake in my pipe, I was combining two channels - one with a header file, one with a set of contents of files of a given chunkSize - as an input to a process requiring both a header and some contents. But it did it the wrong way: the header channel was containing duplicates header files, which was probably the source of the error. Sorry for the inconvenience. 

By the way, related to this mistake I made, is there in NextFlow a more elegant way than having to deal with separate channels for the header file and its associated split contents files, e.g. having a sort of "header: true" option for the splitText operator? (same option as splitCSV, but acting on files, not on their contents). Not sure it is a relevant remark, and probably it is already possible but am doing it the wrong way. 

Many thanks in advance for your advice

**Comment by pditommaso** [comment] 2018-01-19 15:49
I see, ok. If so I'm closing this issue.

> is there in NextFlow a more elegant way than having to deal with separate channels for the header file and its associated split contents files, e.g. having a sort of "header: true" option for the splitText operator? (same option as splitCSV, but acting on files, not on their contents).

Not sure to understand. Could you provide an example?

**Closed by pditommaso** 2018-01-19 15:49 UTC
