### ISSUE TITLE
GCP preemption not reported

### ISSUE THREAD

**Issue by feldman4** [nextflow-io/nextflow#4410] opened 2023-10-15 07:05 UTC
### Expected behavior and actual behavior

GCP Batch jobs that fail due to Spot VM preemption lack an exit code and so can't be specifically caught and retried. 

### Program output

An example failed job:
```
$ grep ec5343d7 nextflow.log -A 2
Oct-14 22:20:55.073 [Task submitter] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Process `GRAFT_gcp:run_2 (398)` submitted > job=nf-ec5343d7-1697321925187; uid=nf-ec5343d7-169732-3a5bce7a-5d07-401b0; work-dir=gs://bii-nextflow/work/ec/5343d7275d2b0ab90e0e992dcfd673
Oct-14 22:20:55.073 [Task submitter] INFO  nextflow.Session - [ec/5343d7] Submitted process > GRAFT_gcp:run_2 (398)
Oct-14 22:20:55.447 [Task submitter] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Process `GRAFT_gcp:run_2 (400)` submitted > job=nf-2f94afe0-1697321925269; uid=nf-2f94afe0-169732-008726d1-2a57-43970; work-dir=gs://bii-nextflow/work/2f/94afe0311f77a6cfe6bc6dc4bc1a38
--
Oct-14 23:02:58.724 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Process `GRAFT_gcp:run_2 (398)` - terminated job=nf-ec5343d7-1697321925187; state=FAILED
Oct-14 23:02:58.753 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Cannot read exit status for task: `GRAFT_gcp:run_2 (398)` - gs://bii-nextflow/work/ec/5343d7275d2b0ab90e0e992dcfd673/.exitcode
Oct-14 23:02:59.579 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 401; name: GRAFT_gcp:run_2 (398); status: COMPLETED; exit: -; error: -; workDir: gs://bii-nextflow/work/ec/5343d7275d2b0ab90e0e992dcfd673]
```

Failed due to "Spot VM preemption with exit code 50001"
```
$ gcloud batch jobs describe nf-ec5343d7-1697321925187 --location=us-east4
...
status:
  runDuration: 1906.687568744s
  state: FAILED
  statusEvents:
  - description: Job state is set from QUEUED to SCHEDULED for job projects/XXX/locations/us-east4/jobs/nf-ec5343d7-1697321925187.
    eventTime: '2023-10-14T22:28:02.850256268Z'
    type: STATUS_CHANGED
  - description: Job state is set from SCHEDULED to RUNNING for job projects/XXX/locations/us-east4/jobs/nf-ec5343d7-1697321925187.
    eventTime: '2023-10-14T22:30:34.365190311Z'
    type: STATUS_CHANGED
  - description: Job state is set from RUNNING to FAILED for job projects/XXX/locations/us-east4/jobs/nf-ec5343d7-1697321925187.
      Job failed due to task failures. For example, task with index 0 failed, failed
      task event description is Task state is updated from RUNNING to FAILED on zones/us-east4-a/instances/8695952087571671283
      due to Spot VM preemption with exit code 50001.
    eventTime: '2023-10-14T23:02:21.052759055Z'
    type: STATUS_CHANGED
...
```

In Tower:
<img width="643" alt="image" src="https://github.com/nextflow-io/nextflow/assets/10049717/c09d97a6-fd98-43e3-897a-5a7fcc15c91b">

```
$ gsutil ls gs://bii-nextflow/work/ec/5343d7275d2b0ab90e0e992dcfd673
gs://bii-nextflow/work/ec/5343d7275d2b0ab90e0e992dcfd673/.command.begin
gs://bii-nextflow/work/ec/5343d7275d2b0ab90e0e992dcfd673/.command.run
gs://bii-nextflow/work/ec/5343d7275d2b0ab90e0e992dcfd673/.command.sh
```

### Environment 

* Nextflow version: 23.09.3-edge build 5888
* Java version: 11
* Operating system: Linux
* Bash version: 5.14

**Comment by pditommaso** [comment] 2023-10-15 09:02
Likely it could be managed and restart the job transparently how it's done for AWS Batch. Tagging @bentsherman

**Comment by Puumanamana** [comment] 2023-10-30 12:18
This is probably the same as #4225

**Comment by bentsherman** [comment] 2023-10-30 22:41
Duplicate of #4225

**Closed by bentsherman** 2023-10-30 22:41 UTC
