### ISSUE TITLE
Nextflow truncating preceding "0" of a CLI passed parameter

### ISSUE THREAD

**Issue by AdrianLimaG** [nextflow-io/nextflow#4652] opened 2024-01-10 20:14 UTC
## Bug report 

Hi,
I have a nextflow script which takes in a date "MMDDYY" and uses this to name folders.
Since it is the start of the year i have now running into the issue where nextflow is skipping over the preceding "0" of the month.
For examples "013123" is entered but nextflow shortens this to "13123".

Of course i have other ways to rename the folders, but would much rather have nextflow not ignore a input value.

I have tried adding quote marks (both of them) and nextflow seems to continue to ignore this preceding "0".

Any suggestion on how to get around this would be great! 

Example:

 --run_date "010824"

Output from Nextflow

10824

**Comment by bentsherman** [comment] 2024-01-10 21:08
Duplicate of #4629 (see that issue for the solution)

**Closed by bentsherman** 2024-01-10 21:08 UTC
