### ISSUE TITLE
Google Cloud - `trace` do not support buckets

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#1084] opened 2019-03-21 09:25 UTC
## Bug report 

My `nextflow.config` has [Tracing & visualisation](https://www.nextflow.io/docs/latest/tracing.html) capabilities:
```
trace { 
  enabled = true
  fields = 'process,task_id,hash,name,attempt,status,exit,realtime,%cpu,vmem,rss,submit,start,complete,duration,realtime,rchar,wchar'
  file = "${params.outDir}/Reports/trace.txt"
}
```
When using `google-genomics` executor and the output directory is a google bucket (ie `--outDir gs://my-google-bucket/Results`), _tracing_ leads the pipeline to crash.

### Expected behavior and actual behavior

Expected behaviour: being able to output those things in a bucket.
Actual behaviour: crashes with
```
ERROR ~ APPEND
```
(see logs below)

### Steps to reproduce the problem

(I'm hoping that it is that this simply hasn't been implemented, and thus straightforward to understand the behaviour. Otherwise, I'll work on a minimal example.)

### Program output 

Here's the content of `.nextflow.log`
```
Mar-21 10:01:10.713 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /Results/Reports/oipipe_trace.txt
Mar-21 10:01:10.962 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.UnsupportedOperationException: APPEND
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newWriteChannel(CloudStorageFileSystemProvider.java:406)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFileSystemProvider.java:302)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2919)
        at nextflow.trace.TraceFileObserver.onFlowStart(TraceFileObserver.groovy:204)
        at nextflow.Session$_start_closure17.doCall(Session.groovy:507)
        at nextflow.Session$_start_closure17.call(Session.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
        at nextflow.Session.start(Session.groovy:507)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:163)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:240)
        at nextflow.cli.Launcher.run(Launcher.groovy:445)
        at nextflow.cli.Launcher.main(Launcher.groovy:622)
```

### Environment 

* Nextflow version: 19.01.0
* Java version: 11.0.2
* Operating system: macOS, google-genomics

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment] 2019-03-21 09:34
Duplicate of #813

**Comment by huguesfontenelle** [comment] 2019-03-21 09:35
Argh, sorry!

**Closed** 2019-03-21 09:34 UTC
