### ISSUE TITLE
Memory reservation for LSF cluster when all arguments are per slot

### ISSUE THREAD

**Issue by kpjonsson** [nextflow-io/nextflow#1071] opened 2019-03-12 12:43 UTC
This is in reference to #124.

I work on an LSF cluster where _both_ `-M` and `-R "rusage[mem=*]"` are _per slot_. This is contrary to the [current solution](https://github.com/nextflow-io/nextflow/blob/b49e6d74dae782def6be2b087d06fdd8fa6b9291/modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy#L70) whereby only the `-M` argument is assumed to be per slot when `perJobMemLimit` is set to `False`. 

I don't know how common this is, but I at least have access to two different LSF clusters, one on which this both arguments are per slot, and one where they both are per job.

**Comment by pditommaso** [comment] 2019-03-12 12:50
Basically the reservation should be divided by the cpus like the mem, right?

**Comment by kpjonsson** [comment] 2019-03-12 15:15
Yes, that's correct.

**Comment by gongyixiao** [comment] 2019-03-12 18:18
Does -M mandatory?

**Comment by gongyixiao** [comment] 2019-03-12 20:10
I made this change in your code it seems to do the desired work on our lsf cluster (me and @kpjonsson ) are talking about the same cluster. 

https://github.com/mskcc/nextflow/commit/04d116b1e7d7a5b378bd2a677ca1d33dc19da6e7#diff-30fd6700c95dc5b545b4bf66bf2bdb36R73

**Comment by pditommaso** [comment] 2019-03-12 20:25
That's good, but where in the docs is specified `select` and `rusage` are use cpu-mem instead job-mem ?

**Comment by kpjonsson** [comment] 2019-03-12 21:17
As far as I'm aware, it is not explicit anywhere. As per #124, it is maybe not true for all clusters that two arguments are set on the same level (job versus slots), but on our two compute clusters, that is indeed the case.

If you take the [docs](https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.2/lsf_command_ref/bsub.1.html) at face value, `-M` "Sets a per-process (soft) memory limit for all the processes that belong to this job", and `-R` "Runs the job on a host that meets the specified resource requirements". It either way, seems like this can be configured differently.

**Comment by gongyixiao** [comment] 2019-03-12 23:55
I don't think my solution actually works...

I need to look into it again.

**Comment by gongyixiao** [comment] 2019-03-13 03:32
This one is able to successfully change the -R to be divided by the number of cpus. 

But I still don't know if -M is mandatory here, or this is the best solution for all lsf users. 

https://github.com/mskcc/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy

**Comment by gongyixiao** [comment] 2019-03-13 03:49
I confirmed this revision correctly divide the -R by the number of cpus. I don't know why my previous revision is not working.

But I still don't know if -M is mandatory here or if this is the best solution. 

https://github.com/mskcc/nextflow/commit/442ce07269c91db293757d0b4dd55e23a95598b8

**Comment by pditommaso** [comment] 2019-03-13 09:59
The option you are mentioning is related to `LSB_JOB_MEMLIMIT` config setting. The [documentation](https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.3/lsf_config_ref/lsf.conf.lsb_job_memlimit.5.html) states 

> This parameter applies to memory limits set when a job is submitted with bsub -M mem_limit, and to memory limits set for queues with the MEMLIMIT parameter in the lsb.queues file.

Therefore I understand  that it should *not* take in consideration for `-R` *select* and *rusage* directives.

**Comment by kpjonsson** [comment] 2019-03-13 12:39
Right, `-M` determines when/if a job gets killed, `-R` determines resource distribution and thus possibly the wait time on the LSF cluster.

**Comment by pditommaso** [comment] 2019-03-13 13:02
I'm inclined to think the current implementation is correct and therefore close this issue.

**Comment by evanbiederstedt** [comment] 2019-03-14 01:40
RE: The conceptual  difference between -M and -R "rusage[mem=*]" in LSF. 

Conceptual  difference between `-M` and `-R "rusage[mem=*]"` in LSF. The first one -M is used for actual memory reservation for slots or job (it's configurable)  and integrates with cgroups/mem on the execute host. The job will be killed if it uses more memory than -M. The second one (`-R "rusage[mem=*]"`) is just used for resource reservation internally in LSF, as result LSF keeps internally the amount of memory been reserved per host, so it will not allocate more memory on host then the total available memory.
https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_config_ref/lsb.params.resource_reserve_per_task.5.html

> That's good, but where in the docs is specified select and rusage are use cpu-mem instead job-mem ?

For LSF, `-M` can be per slot/task or per job. For us, it appears that `-R “rusage[mem=GB]` is  inheriting settings from `-M`.

The consensus from the system administrators is that we've chosen the settings "memory per slot" especially for multi-hosts jobs as MPI jobs. This is so we can guarantee memory per slot on different compute nodes; otherwise if we have memory per Job, LSF will unpredictably assign memory per slot on different hosts (albeit resulting in the total memory requested). 

So it appears this is standard LSF configuration (though we could be mistaken). I could do some searching in the documents.

I'm happy to create a PR to cater to these users (but first finding time to finish the other!)

**Comment by evanbiederstedt** [comment] 2019-03-14 01:43
As for the issue itself, it appears we (internally, given our settings explained above) want the `-M` value and the `-R` value to be the same. 

https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy#L70-L73

Therefore, on the short-term, let's try setting `perJobMemLimit` to be true and request the memory values as if we were submitting via slot, not by job. (That is, we set `perJobMemLimit` to be true, but act as if `perJobMemLimit` is false.)

**Comment by pditommaso** [comment] 2019-03-15 10:40
As per this comment https://github.com/nextflow-io/nextflow/issues/124#issuecomment-204656321 `-R` memory is always per job, and I was unable to find anything in the docs showing the contrary. If you can bring such evidence I will be happy to add the support for it.

**Comment by evanbiederstedt** [comment] 2019-03-15 16:23
Hi @pditommaso 

Thanks for the response. 

> The reservation is always per-job. I agree it's not very explicit in the documentation (the only hint is that it's called "job-level resource reservation").

We haven't been able to find strong evidence for this in the documentation. I cannot see in the IBM LSF documentation whereby it requires `-R` to be always per job. 

> If you can bring such evidence I will be happy to add the support for it.

Here's what we found, under the section  **Where LSF gets the job information for each factor**:

https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_admin/job_priority_aps.html

For factor `MEM`, it appears that that `-R` value is multiplied by number of slots if `RESOURCE_RESERVE_PER_TASK=Y`. The schedule will not do multiplication if `RESOURCE_RESERVE_PER_TASK=N`. 

The pdf version of the documentation for download is here: [Administering IBM Spectrum LSF](https://www.ibm.com/developerworks/community/wikis/form/anonymous/api/wiki/99245193-fced-40e5-90df-a0e9f50a0fb0/page/22e9aefe-a2e8-46e6-ad62-2ff5860f45aa/attachment/9bde7ab3-2c14-4b1d-9738-a43e7925008e/media/lsf_admin.pdf)  I'm looking at page 491, Chapter 5, "Where LSF gets the job information for each factor"

There is more information here: https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.3/lsf_command_ref/bsub.__r.1.html

The options exist for job-level or queue-level resource allocation. It appears to be a standard, accepted LSF configuration.

(As a side note, the website organization here and this documentation isn't the most helpful, which breeds confusion. Misspellings, etc.)

I'm happy to help out with the PR, and we appreciate the help on this.

**Comment by pditommaso** [comment] 2019-03-18 07:36
Frankly it's very confusing, it seems that `RESOURCE_RESERVE_PER_TASK` applies only to * compound resource requirements*, also there's no mention about `-R select`. 

> The options exist for job-level or queue-level resource allocation. It appears to be a standard, accepted LSF configuration.

Cannot find any reference, where exactly?

**Comment by evanbiederstedt** [comment] 2019-03-19 21:20
Hi @pditommaso 

Apologies for the delays. 

With regards to "compound resource requirements", here is what I've found in the documentation; there are "simple" and "compound" resource requirements:

https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.2/lsf_admin/res_req_strings_about.html

> Most LSF commands accept a `-R "res_req"` argument to specify resource requirements. The exact behavior depends on the command....Resource requirement strings can be simple (applying to the entire job) or compound (applying to the specified number of slots).

So for this:

> also there's no mention about -R select

Within the following link:

https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.3/lsf_command_ref/bsub.__r.1.html

The phrase `"res_req" within `bsub -R "res_req"` is shorthand for:

> The resource requirement string sections have the following syntax:
> select[selection_string] order[order_string] rusage[
> usage_string [, usage_string][|| usage_string] ...]
> span[span_string] same[same_string] cu[cu_string]] affinity[affinity_string]

Within that document, there's discussions of job-level vs. queue-level resource allocation. 

We have `RESOURCE_RESERVE_PER_TASK=Y` on a global LSF configuration.

**Comment by pditommaso** [comment] 2019-03-21 15:11
Still looks a very grey area to me. However to summarise: 

1)`-R rusage` can be set as mem-per-cpu
2) this setting cannot be inferred by any other means than adding an extra NF setting
3) still unclear if this should be applied also to `-R select`

**Comment by pditommaso** [comment] 2019-04-03 09:20
> On site, we actually don't require -R select for memory. We would rather use -R select to (let's say) run jobs on GPUs vs CPUs.
Could you clarify why both -R select[###] and -R usage[###] are required for Nextflow?

They are not required by NF but the node selection is coherent with the expected memory usage. 

> I don't think the flag perJobMemLimit is necessary, as this is based on LSF configurations. I'm not sure why users would (or could) use this flag (though it is very possible I'm missing something). If we removed -R select[###], I think that solves all issues.

If the current mem setting applied by NF does not work with you LSF installation I would suggest to *not* use the `memory` directive and use instead [clusterOptions](https://www.nextflow.io/docs/latest/process.html#containeroptions) that allow the specification of any settings as you wish.

**Comment by evanbiederstedt** [comment] 2019-04-04 01:30
Hi Paolo

> If the current mem setting applied by NF does not work with you LSF installation I would suggest to not use the memory directive and use instead clusterOptions that allow the specification of any settings as you wish.

That might work. If we don't specify the memory with Nextflow, we could specify it there. Locally, we are also doing a bit of arithmetic to make sure we don't run into this issue. 

> They are not required by NF but the node selection is coherent with the expected memory usage.

This is interesting! It looks like you are requiring the NF jobs been scheduled on nodes with enough memory and certain hardware configuration.

We tried the following test on site, FWIW:

```
$ bsub -n 1 -W 10 -R "select[700>mem] rusage[mem=700]" sleep 2000
$ bjobs -l 6845381

Job <6845381>, User <sveta>, Project <default>, Application <defaultOS7>, Statu
                     s <PEND>, Queue <general>, Job Priority <25>, Command <sle
                     ep 2000>, Esub <memlimit>
Wed Apr  3 12:11:59: Submitted from host <juno>, CWD <$HOME>, Requested Resourc
                     es <select[700>mem] rusage[mem=700]>;
 PENDING REASONS:
 Job requirements for reserving resource (mem) not satisfied: 53 hosts;
 
$ bsub -n 1 -W 10 -R " rusage[mem=700]" sleep 2000
Job <6845415> is submitted to default queue <general>.
$ bjobs -l 6845415

Job <6845415>, User <sveta>, Project <default>, Application <defaultOS7>, Statu
                     s <PEND>, Queue <general>, Job Priority <25>, Command <sle
                     ep 2000>, Esub <memlimit>
Wed Apr  3 12:15:01: Submitted from host <juno>, CWD <$HOME>, Requested Resourc
                     es <rusage[mem=700]>;
 PENDING REASONS:
 Job requirements for reserving resource (mem) not satisfied: 54 hosts;

 RUNLIMIT                
 10.0 min

 MEMLIMIT
    700 G 

 SCHEDULING PARAMETERS:
           r15s   r1m  r15m   ut      pg    io   ls    it    tmp    swp    mem
 loadSched   -     -     -     -       -     -    -     -     -      -      -  
 loadStop    -     -     -     -       -     -    -     -     -      -      -  

 RESOURCE REQUIREMENT DETAILS:
 Combined: select[(type == CentOS7 ) && (type == any &&healthy=1)] order[!-slot
                     s:-maxslots] rusage[mem=700.00] span[hosts=1] affinity[thr
                     ead(1)*1]
 Effective: -

```
I don't see a big difference on our end.

RE: the `-R select` question above

It looks like `-R select` applies to the total resources available on the execution host. Therefore, another option (which looks to be the correct option) may be the following: 

We could try to modify `select[mem>X]` for LSF for users with the configuration `RESOURCE_RESERVE_PER_TASK=Y` by mutliplying `-R rusage[mem=value]` by the number of slots N, and we should get the correct `X` value for `select[mem>X]`.

So if users try `-R "rusage[mem=B]"` the value B should be multiply by number of slots `B` to get `B * N=XX` for `-R select[mem>XX]`

What do you think? 

Thanks again for the help

**Comment by pditommaso** [comment] 2019-04-08 12:18
Hi, on your test I can hardly add something. The best way is to benchmark it under stress condition and see how it behave. 

In general, I think you are a very specific requirement. IMO the best way thing to handle this is using custom NF setting via `clusterOptions` and maybe at some point implement your own LSF executor once you have the consolidated the real option you want to use.

**Comment by evanbiederstedt** [comment] 2019-04-09 19:59
Hi Paolo

Our system administrators asked IBM about this issue. Here is the correspondence. `clusterOptions` without memory may solve the problem, but I'm not sure it addresses the larger problem. 

Here is the correspondence:

**Question to IBM:**
"""
Hi

I have an LSF question from my customer on the relationship between `-R rusage[mem=value]` and `-R select[value>mem]`.
We have the LSF configuration with `RESOURCE_RESERVE_PER_TASK=Y`. 

Basically I need an answer with respect to the following: 
if the job request is ` -R rusage[mem=X]` (where` RESOURCE_RESERVE_PER_TASK=Y`) what should be the value be for `-R select[?>mem]`? From an LSF prospective, why LSF needs this value `-R select[value>mem] `? If it exists, what influence does this have on job scheduling?

If you would like to see the discussion regarding using LSF:
https://github.com/nextflow-io/nextflow/issues/1071

Regards,
"""

**Answer from IBM:**
"""
Hi, 

According to options of bsub command at https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_command_ref/bsub.__r.1.html, -R can be used for running a job on a host which meets the specified resource requirements. A selection section "select" specifies the criteria for selecting execution hosts from the system, while a resource usage section ""rusage" specifies the expected resource consumption of the task.
 
The parameter RESOURCE_RESERVE_PER_TASK would allow mbatchd to reserve resource based on job tasks instead of per-host when it sets to Y.
 
For example, if the parameter RESOURCE_RESERVE_PER_TASK set to N, mbatchd only reserves resources for parallel jobs on a per-host basis. If you run the following command
bsub -n 4 -R "rusage[mem=500]" ./my_job Then, it will requires the job to reserve 500MB on each host 
 
However, if the parameter RESOURCE_RESERVE_PER_TASK set to Y, the job must reserve 500MB of memory for each task (4*500=2 GB) on the host in order to run.
 
To illustrate, if you run the job "bsub -n 4 -R "rusage[mem=500]" ./my_job", with  the parameter RESOURCE_RESERVE_PER_TASK = N
1 slot on Host A / 1 slot Host B / 1 slot on Host C / 1 slot on Host D  -> 500MB on HostA / 500MB on HostB / 500MB on HostC / 500MB on HostD -> reserved 2 slots on Host A / 1 slot on Host B / 1 slot on Host C -> 500MB on HostA / 500MB on HostB / 500MB on HostC -> reserved 2 slots on Host A / 2 slots Host B -> 500MB on HostA -> 500MB on HostB -> reserved 3 slots on Host A / 1 slot Host B -> 500MB on HostA -> 500MB on HostB -> reserved 4 slots on Host A -> 500MB on HostA -> reserved  
However, with RESOURCE_RESERVE_PER_TASK=Y
 
1 slot on Host A / 1 slot Host B / 1 slot on Host C / 1 slot on Host D  -> 500MB on HostA / 500MB on HostB / 500MB on HostC / 500MB on HostD -> reserved 2 slots on Host A / 1 slot on Host B / 1 slot on Host C -> 500MB*2 on HostA / 500MB on HostB / 500MB on HostC -> reserved 2 slots on Host A / 2 slots Host B -> 500MB*2 on HostA -> 500MB*2 on HostB -> reserved 3 slots on Host A / 1 slot Host B -> 500MB*3 on HostA -> 500MB on HostB -> reserved 4 slots on Host A -> 500MB*4 on HostA -> reserved  
Please advise me if you have questions or concerns.
 
Regards,
"""

Thank you for your work on this! Let me know how we should best proceed.

**Comment by pditommaso** [comment] 2019-04-16 07:55
OK, can you summarise the `mem` should be divided for the num of `cpus` for *both* `-R select` and `-R rusage` options when `RESOURCE_RESERVE_PER_TASK=Y` ?

**Comment by evanbiederstedt** [comment] 2019-04-26 05:12
Hi @pditommaso 

Apologies for the delays. 

We've tried this locally, and double-checked to IBM to make sure:

When `RESOURCE_RESERVE_PER_TASK=Y`, then `-R rusage` is per slot and `-R select` applies to all available resources on the host level. For LSF, there is no dependence between `select` and `rusage`.

This command:

`bsub -n 2 -R "select[mem>500]" -R "rusage[mem=200]"   sleep 200`

will reserve `200GB` per slot, and `400GB` on the host level. That will run on site.

However, `bsub -n 2 -R "select[mem>800]" -R "rusage[mem=200]"   sleep 200` will fail on site, as there is no host with 800GB of memory

**Comment by pditommaso** [comment] 2019-04-29 09:22
WHat about this: 

```
def mem = task.config.getMemory()
def mem1 = ( task.config.cpus > 1 && !perJobMemLimit ) ? mem.div(task.config.cpus as int) : mem

result << '-M' << String.valueOf(mem1.toUnit(memUnit))
result << '-R' << "rusage[mem=${mem1.toUnit(usageUnit)}] select[mem>=${mem.toUnit(memUnit)}]" 
```

**Comment by evanbiederstedt** [comment] 2019-04-29 17:30
Hi @pditommaso 

I *think* that should work. So if I understand the above correctly, users will use the flag `reserve_per_task`? I think this could also be parsed from `$LSF_ENVDIR/lsf.conf`, similar to the LSF memory discussion.

There either is `RESOURCE_RESERVE_PER_TASK=N` or `RESOURCE_RESERVE_PER_TASK=Y`. 

Naturally, a flag could override this. I'm happy to help out (as it's unfair to simply make feature requests non-stop without chipping in.)

Thanks, Evan

**Comment by pditommaso** [comment] 2019-04-29 17:47
> There either is RESOURCE_RESERVE_PER_TASK=N or RESOURCE_RESERVE_PER_TASK=Y.

Ah, excellent, this simplifies things.

**Comment by pditommaso** [comment] 2019-05-15 16:11
Done

**Closed by pditommaso** 2019-05-15 16:11 UTC
Labels: platform/lsf, pri/awaiting-more-evidence

**Comment by kpjonsson** [comment] 2019-05-15 16:43
@pditommaso Thanks.

**Comment by gongyixiao** [comment] 2019-05-15 16:46
Looks great! Thank you very much.

**Comment by evanbiederstedt** [comment] 2019-05-15 17:29
Very much appreciated! Thank you!
