### ISSUE TITLE
Local executor doesn't use cpu constraint

### ISSUE THREAD

**Issue by birnbera** [nextflow-io/nextflow#1831] opened 2020-12-11 22:30 UTC
### Expected behavior and actual behavior

Based on the [documentation](https://www.nextflow.io/docs/latest/config.html#scope-executor) I would expect the number of cpus available to a task to be limited by the number of cpus specified in a (local) executor block. However, it does not appear to have any effect.

### Steps to reproduce the problem

In order to test whether Nextflow is truly respecting the number of cpus specified I used the following setup:

`nextflow.config`:
```nextflow
executor {
    name = "local"
    cpus = 1
}
```

`test.nf`:
```nextflow
process test_cpus {
    script:
    """
    seq 10000000000 > /dev/null &
    seq 10000000000 > /dev/null &
    wait
    """
}
```
(I'm using such a large argument to `seq` in order to get Nextflow to print the time statistics at the end, which is doesn't do if execution is too short).

### Program output 
I run the script via:
```console
nextflow run test.nf
```

After completion Nextflow reports that the process took 1 minute and 26 seconds:
```console
Completed at: 11-Dec-2020 22:06:57
Duration    : 1m 26s
CPU hours   : (a few seconds)
Succeeded   : 1
```

Now, if you change the `cpus` field in `nextflow.config` to `2`, as in:
```nextflow
executor {
    name = "local"
    cpus = 2
}
```

I would expect to see the process take approximately half as long, however the result is the same:
```console
Completed at: 11-Dec-2020 22:09:51
Duration    : 1m 27s
CPU hours   : (a few seconds)
Succeeded   : 1
```

Just in case the process was still using 1 cpu by default, I added the `cpus 2` directive to the process, but received the same result.

This is in contrast to how it works on the command line using `taskset`. For example, I created a `bash` script identical to the script block in `test.nf`.

`test.sh`:
```bash
#!/usr/bin/env bash

seq 10000000000 > /dev/null &
seq 10000000000 > /dev/null &
wait
```

And timed the script execution using `time` and different numbers of cpus:
```console
$ time taskset --cpu-list 0 ./test.sh
real	2m52.175s
user	2m38.344s
sys	0m13.821s
$ time taskset --cpu-list 0,1 ./test.sh
real	1m25.556s
user	2m37.159s
sys	0m13.905s
```

If you look at the Nextflow log, you see that the pool size is the number of logical cpus on the system:
```log
Dec-11 22:08:24.341 [main] DEBUG nextflow.Session - Executor pool size: 64
```
And the local executor is at least seeing the `cpus` field in `nextflow.config`.
```log
Dec-11 22:08:24.745 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=2; memory=498.2 GB; capacity=64; pollInterval=100ms; dumpInterval=5m
```
Above I'm showing with `cpus` set to 2, but it also reports the correct number for `cpus` set to 1.

### Environment 

* Nextflow version: [20.07.1] 
* Java version:
```console
$ java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
* Operating system: [Centos 7]
* Bash version: (use the command `$SHELL --version`)
```console
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```

**Comment by abhi18av** [comment] 2020-12-12 07:20
Hi @birnbera ,

This is an interesting and well-posed question, I'm not familiar with the overall implementation details for executors but, for `local` executor, I myself have seen the underlying process taking up more than the specified number of CPUs if it has an inbuilt default. For example, [`prokka` has a default of 8 cpus](https://github.com/tseemann/prokka/#command-line-options).

But generally I've noticed that workflows are written to explicitely rely on the number logical CPUs specified in the `cpus` directive using [process implicit variables](https://www.nextflow.io/docs/latest/script.html#process-implicit-variables).

For example,

```
process TASK {

cpus 4

script: 

"""
tool --threads ${task.cpus}
"""

}

```


Please correct me if I'm wrong, but it seems `seq` is single threaded by design or atleast [doesn't allow explicit CPU assignment](https://man7.org/linux/man-pages/man1/seq.1.html).

**Comment by abhi18av** [comment] 2020-12-12 08:16
This might be an anti-pattern, but I did a little experiment using `taskset` to see how I could incorporate this into a script.


```nextflow

process TWO_CPUS {
    cpus 2

    shell:
    '''
    taskset --cpu-list $(seq -s, 0 !{task.cpus - 1}) test.sh
    '''
}

```

**Comment by birnbera** [comment] 2020-12-12 21:39
@abhi18av Thanks for your comments. Regarding your observation that `seq` is single threaded, that is why I chose it. I tried testing with `sleep` at first, but since it doesn't actually do anything *by design* I used `seq` just as a way to keep the processor busy.  In my script, I put it in the background so both `seq` invocations can execute in parallel.

The problem is that while some tools do let you tell it how many processors to use, not all tools are this well behaved (I'm looking at you [Qualimap](http://qualimap.conesalab.org/)) and will continue to spawn an inordinate number of threads (often times many more than the number of cpus). So basically, I am looking for a way to actually limit the number of cpus that a process can use and let it go to town on the threading, without bogging down other better behaved processes.

> This might be an anti-pattern, but I did a little experiment using `taskset` to see how I could incorporate this into a script.
> 
> ```nextflow
> process TWO_CPUS {
>     cpus 2
> 
>     shell:
>     '''
>     taskset --cpu-list $(seq -s, 0 !{task.cpus - 1}) test.sh
>     '''
> }
> ```

I hadn't thought of using `seq` this way, but it doesn't really solve the problem since 1) this needs to be configurable per executor (or at least in `profiles`) and 2) you don't want to tell every instance of the same process to use the same set of cpus.

Ideally, if one process needs `m` cpus and another process needs `n` cpus, to the greatest extent possible Nextflow should try to reserve a disjoint set of cpus for each (or allowing the minimal amount of overlap). Clearly at the end of the day Nextflow is not really a scheduler so it's possible that reserving cpus and the cpu process directive with the local executor is the real anti-pattern. Still, I'm confused about what they're *supposed* to do given my initial observations.

**Comment by pditommaso** [comment] 2020-12-13 13:34
The support for container cpus allocation  (ption `--cpus`) is relatively new and it was not available when the Nextflow support was implemented. 

https://www.docker.com/blog/cpu-management-docker-1-13/

I agree that would be useful to add it. A pull request is welcome.

**Comment by birnbera** [comment] 2020-12-13 16:43
Hi @pditommaso, takes for taking the time to look at this. I'm more confused now, however. What does this have to do with containers? I'm not using Docker at all in this example.

**Comment by pditommaso** [comment] 2020-12-14 07:17
I think I've misread this and assumed it was related to container execution. The local execution only does a simple allocation but does not enforce the process CPUs requirements.

**Comment by birnbera** [comment] 2020-12-14 07:28
@pditommaso, I see. That definitely was not obvious to me from the [docs](https://www.nextflow.io/docs/latest/config.html#scope-executor). Would you mind expanding a bit on what you mean by simple allocation? Or point me to the relevant code? Thanks!

**Comment by pditommaso** [comment] 2020-12-14 07:33
That the *nominal* cpus requirement for running tasks does not overcome avail cpus. 

https://github.com/nextflow-io/nextflow/blob/e94e6877c2dc9bed983e873b62e302a08843c891/modules/nextflow/src/main/groovy/nextflow/processor/LocalPollingMonitor.groovy#L168-L183

Bear in mind, the local executor is designed mainly for dev and testing purpose. If you need proper jobs scheduling and allocation you should take into consideration a proper job scheduler e.g. Slurm.

**Comment by birnbera** [comment] 2020-12-14 18:11
@pditommaso, Thanks, I think see what the local executor does. For posterity and anyone else that encounters this issue, my understanding is that the `cpus` option to the local executor is a way to catch workflows that require more CPU's than are available. And the `cpus` directive when it comes to locally executing processes is there as a way of passing a variable down to processes, not really to physically limit a process in any way (unlike for, e.g., batch or slurm, which actually use the directive). So if you have a process that requires 16 CPU's but the local executor only mentions 8, you stop the workflow before it even starts. It additionally, will delay executing a process that requires more CPU's than are available at the moment based on the number of instances of other processes that declare a value for the `cpus` directive.

**Comment by pditommaso** [comment] 2020-12-14 20:11
Ok, closing the issue then. Feel free to further comment below if needed.

**Closed** 2020-12-14 20:11 UTC
Labels: help wanted, kind/enhancement

**Comment by birnbera** [comment] 2020-12-14 21:02
@pditommaso, just to make sure I'm interpreting the behavior correctly would you mind giving a thumbs up or thumbs down to what I wrote above?

**Comment by pditommaso** [comment] 2020-12-15 08:46
Yes, the statement above is correct 👍
