### ISSUE TITLE
Render last tag along with the process name

### ISSUE THREAD

**Issue by welchwilmerck** [nextflow-io/nextflow#1144] opened 2019-05-07 13:38 UTC
```
$ nnf info
  Version: 19.0.0.modules-draft10-SNAPSHOT build 5058
  System: Linux 4.4.41-36.55.amzn1.x86_64
```
Just run the example .nf in the docs for [tag](https://www.nextflow.io/docs/latest/process.html#tag)

```
N E X T F L O W  ~  version 19.0.0.modules-draft10-SNAPSHOT
Launching `tag.nf` [stoic_picasso] - revision: b3fea3d29c
executor >  local (3)
[bf/2119fc] process > foo [100%] 3 of 3 ✔
Completed at: 07-May-2019 13:25:06
Duration    : 2.3s
CPU hours   : (a few seconds)
Succeeded   : 3
```

```
N E X T F L O W  ~  version 19.01.0
Launching `tag.nf` [backstabbing_goodall] - revision: b3fea3d29c
[warm up] executor > local
[b9/736b4e] Submitted process > foo (aa alpha)
[40/0599b7] Submitted process > foo (aa gamma)
[9d/d4256e] Submitted process > foo (aa omega)
```

**Comment by pditommaso** [comment] 2019-05-07 13:42
Duplicate of #1141?

**Comment by welchwilmerck** [comment] 2019-05-07 13:46
Ahh, certainly appears to be.

**Comment by pditommaso** [comment] 2019-05-11 10:44
Closing in favour of #1141.

**Comment by pditommaso** [comment] 2019-05-11 10:52
Actually, the #1141 is proposing a more extended visualisation. I'm re-opening this to visualise the last along with the process name.

**Closed** 2019-05-14 08:55 UTC
Labels: kind/enhancement

**Comment by wjv** [comment] 2019-08-23 09:25
This is purely aesthetic, but…

If the tags are not all the same character length (e.g. if they are species names), this change leads to the right-hand column in the command line output (the column showing `[100%] 82 of 82`) continually jumping left and right while the pipeline is executing. While this doesn’t affect processing, but it’s visually distracting.

(I’m considering removing tagging from a project since my users thought the output jumping back and forth meant something is wrong.)

It might be better if the column containing `processName (tag)` is simply widened and never shrunk back down again if the length of the tag decreases.

**Comment by pditommaso** [comment] 2019-08-23 10:23
@wjv please report it as separate issue

**Comment by wjv** [comment] 2019-08-23 10:24
Thanks @pditommaso, I’ll do that. I’ll also add a little video I recorded to demonstrate what happens.
