### ISSUE TITLE
Nextflow is unable to generate conda enviroment from yaml file with conda version 4.7.5

### ISSUE THREAD

**Issue by rwgn23** [nextflow-io/nextflow#1237] opened 2019-07-22 09:13 UTC
## Bug report 

With the newer conda versions it is recommended to use `conda activate `instead of `source activate `. I am using conda version 4.7.5. With this conda version nextflow is not able to generate a environment from a yaml file.

### Expected behavior and actual behavior

Expected behavior: Nextflow generates the environment.
Actual behavior: Nextflow does not generate the enviroment.

### Steps to reproduce the problem

Using conda version 4.7.5 (I guess its 4.4+)
Using the conda directive and giving it a path to a yaml file for creating an conda enviroemnt

```
process someProcess {
    conda "some.yaml"

    """
    echo test
    """
}
```

### Program output 
```

ERROR ~ Error executing process > 'test'

Caused by:
  Process `test` terminated with an error exit status (1)

Command executed:

  echo test

Command exit status:
  1

Command output:
  (empty)

Command wrapper:
  .command.run: line 77: activate: No such file or directory

Work dir:
  /mnt/workspace/rwiegan/work/71/324c12992440f40cf20d4a18de99f6

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Log File
[nextflow.log](https://github.com/nextflow-io/nextflow/files/3416524/nextflow.log)

### Environment 

* Nextflow version: 19.04.1 
* Java version: 1.8.0_192
* Operating system: Debian 4.9.110

**Comment by pditommaso** [comment] 2019-07-22 09:19
It looks duplicate of #1195

**Comment by rwgn23** [comment] 2019-07-22 09:33
Ah yes.
Sorry and thank you.

**Closed** 2019-07-22 11:34 UTC
