### ISSUE TITLE
Problems downloading data from S3

### ISSUE THREAD

**Issue by sminot** [nextflow-io/nextflow#1263] opened 2019-08-06 03:16 UTC
### Expected behavior and actual behavior

While a task runs via the AWS Batch executor, it is expected that input files will be downloaded from S3 prior to the start of the task.

Instead, I observe with large-scale workflows in which many large files are being downloaded into a single task that not all of the input files are downloaded as expected. This is an error that occurs less than 1% of the time, making it difficult to troubleshoot. However, there is a message printed to the logs which may be helpful:

```
Error when retrieving credentials from container-role: Error retrieving metadata: Received non 200 response (429) from ECS metadata: You have reached maximum request limit.
```

### Steps to reproduce the problem

I apologize that I cannot faithfully reproduce the problem, as it only happens with very large workflows in which a task needs to download many large files from S3 into the working directory.

### Program output 

The constant error message associated with this problem is:

```
Error when retrieving credentials from container-role: Error retrieving metadata: Received non 200 response (429) from ECS metadata: You have reached maximum request limit.
```

### Environment 

* Nextflow version: 19.05.0-SNAPSHOT build 5075
* Java version: 1.8.0_181
* Operating system: Linux

### Suggestion

My suggestion is that prior to executing the run script, the `.command.run` executable checks for the presence of the input files, which would at least remove the silent error in which the input files are simply missing.

**Comment by jgolob** [comment] 2019-08-07 20:30
I can confirm this issue, as well as the circumstances in which I can consistently cause the result: 
- `executor = 'awsbatch'`
- a large number of files coming to / from S3 into the container. 

This seems related to the following issues with AWS:
https://github.com/aws/amazon-ecs-agent/issues/1231
https://github.com/aws/amazon-ecs-agent/issues/1262

Setting the environment variable ECS_TASK_METADATA_RPS_LIMIT (via `env.ECS_TASK_METADATA_RPS_LIMIT="1,1"` in `nextflow.config`) to the lowest possible setting does not resolve the issue (and makes me wonder if the environmental variable is being applied at the wrong step (i.e. after rather than before staging of files).

**Comment by pditommaso** [comment] 2019-08-08 07:18
Yes, I think this is mostly a problem on AWS side caused by network congestion due to too many file transfers. 

You may try to mitigate using smaller instances and reducing the num of parallel download, check the `maxParallelTransfers` in the batch settings. https://www.nextflow.io/docs/latest/config.html#scope-aws

**Comment by sminot** [comment] 2019-08-08 12:04
I'm going to add here that (based on the commit history) I would guess that this option is available as of version 19.05.0-edge

**Comment by sminot** [comment] 2019-08-08 12:06
However, I would also propose that the ideal behavior for Nextflow would be to confirm that all downloaded files really do exist in the working directory after the download step and prior to starting the processing of the task. How do you feel about that @pditommaso?

**Comment by pditommaso** [comment] 2019-08-08 15:41
>  I would guess that this option is available as of version 19.05.0-edge

I'll suggest using the latest `19.07.0` version, there was some mess in prior versions with file transfers. 

> I would also propose that the ideal behavior for Nextflow would be to confirm that all downloaded .. etc 

Not sure to understand how that would work?

**Comment by jgolob** [comment] 2019-08-08 16:08
The `maxParallelTransfers` was unable to address this error. I was able to work around this by using the `maxForks` directive for the relevant IO-intensive processes.

To help with debugging this, I can make a workflow that consistently results in this error when executed on AWS. Let me know and I will do so, @pditommaso

**Comment by sminot** [comment] 2019-08-22 13:46
@pditommaso I just wanted to touch base and see what you thought about adding a step after download that checks to make sure that all files have been downloaded? 

I'm currently doing this manually in some processes, which is going to be very unintuitive for some users (who might not understand that a file could be silently missing due to file transfer issues). 

Thoughts?

**Comment by pditommaso** [comment] 2019-10-19 14:53
Sorry I was missing this comment. The plan is to improve the support for Batch using [Luste FSx storage](https://aws.amazon.com/fsx/lustre/). S3 has the limits described above. Closing this issue for now. Feel free to comment/reopen if needed.

**Closed by pditommaso** 2019-10-19 14:53 UTC
Labels: storage/aws-s3

**Comment by maxbates** [comment] 2020-10-21 22:11
I've run into this issue and can confirm it is not intuitive that files may be missing. It usually manifests in an error like:

```
Oops.. something wrong happened while creating task 'my_task' unique id -- Offending keys: [
...
]
```

It would be much clearer if there were a check whether the file exists before attempting to hash it. 

Importantly, when downloading a directory, if some file(s) in the directory fail to download, an invalid hash would be generated. That would be a really nasty bug.
