### ISSUE TITLE
Error after upgrading to 24.02.0-edge 

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#4810] opened 2024-03-11 17:01 UTC
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Pipeline works well with version 23.10.1
 With the new nextflow I got:

```
ERROR ~ Error executing process > 'BASECALL:DORADO_BASECALL:baseCall (mod---2)'

Caused by:
  class org.codehaus.groovy.runtime.GStringImpl cannot be cast to class java.lang.String (org.codehaus.groovy.runtime.GStringImpl is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

Source block:
  """
            dorado basecaller ${params.EXTRAPARS} --emit-fastq ./ > ${idfile}.fastq
            bgzip -@ ${task.cpus} ${idfile}.fastq
      """
````

**Comment by bentsherman** [comment] 2024-03-11 17:06
Is there a stack trace for this error? It will be difficult to find the source of the error without the trace

**Comment by lucacozzuto** [comment] 2024-03-12 10:18
do you mean the `.nextflow.log?`

**Comment by lucacozzuto** [comment] 2024-03-12 10:21
I added another part of the error

**Comment by pditommaso** [comment] 2024-03-12 10:34
Luca, please include `.nextflow.log` file

**Comment by lucacozzuto** [comment] 2024-03-12 11:09
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/14571283/nextflow.log.txt)
Here it goes. Thanks!

**Comment by lucacozzuto** [comment] 2024-03-12 11:39
You can see the code here:

https://github.com/biocorecrg/BioNextflow/blob/master/subworkflows/basecalling/dorado.nf

Thanks!

**Comment by pditommaso** [comment] 2024-03-12 12:20
Is there are way to replicate it locally?

**Comment by lucacozzuto** [comment] 2024-03-14 09:14
Cd mop_preprocess

**Comment by pditommaso** [comment] 2024-03-14 10:19
You are right, however it fails for other reason 

```
  Unable to find image 'biocorecrg/mopprepr:0.7' locally

```


Are you able to isolate the error in a smaller test case?

**Comment by lucacozzuto** [comment] 2024-03-14 10:40
I'll try to make a smaller test case. However `-with-docker` should download the image (or with -singularity in case you want it).

**Comment by pditommaso** [comment] 2024-03-14 11:03
I did it 

```
nextflow run mop_preprocess.nf -with-docker -profile ci
```

**Comment by lucacozzuto** [comment] 2024-03-14 11:10
Wow. I have a CI that is working on github and is ok :) https://github.com/biocorecrg/MOP2/blob/main/.github/workflows/build.yml

Once I have a simple test case I'll send you. Thanks again

**Comment by lucacozzuto** [comment] 2024-03-14 14:18
I think I track down where it fails... I have this code in the nextflow.config:

```
clusterOptions = { "-l h_vmem=${task.memory.toString().replaceAll(/[\sB]/,'')}" }
```
removing it fixed the problem.

**Comment by lucacozzuto** [comment] 2024-04-19 08:42
Hi, thanks for reopening. I'm currently not using nextflow "edge" anymore since I got java errors that are not present in the normal one.

**Comment by pditommaso** [comment] 2024-04-19 08:57
Duplicate of https://github.com/nextflow-io/nextflow/issues/4931

**Comment by pditommaso** [comment] 2024-04-19 09:54
Sovled by 74004fbd

**Closed by pditommaso** 2024-04-19 09:54 UTC
