### ISSUE TITLE
scratch directive does not work

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1280] opened 2019-08-16 14:44 UTC
## Bug report 

I am trying to use the `scratch` directive on my PBS cluster but it does not work, and I have traced the cause in the auto-generated `.command.run` script. Basically, the run script does correctly set up and stage the scratch directory, but then it changes back to the work directory because it calls itself again.

Here is the abridged run script with my debug notes:
```
#!/bin/bash
#PBS -N nf-revision_Yea
#PBS -o /pscratch/scratch4/btsheal/benchmark-nf/kinc/work/da/06deebb463f498dece3d3cccc791eb/.command.log
#PBS -j oe
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=2:mpiprocs=1:mem=8gb:ngpus=2:gpu_model=k40

cd /pscratch/scratch4/btsheal/benchmark-nf/kinc/work/da/06deebb463f498dece3d3cccc791eb
NXF_ENTRY=${1:-nxf_main}

nxf_trace() {
    # DEBUG: now we are back in the work directory! it's because of the cd command at the top
    pwd

    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}

nxf_launch() {
    # DEBUG: still in the scratch directory
    pwd

    /bin/bash /pscratch/scratch4/btsheal/benchmark-nf/kinc/work/da/06deebb463f498dece3d3cccc791eb/.command.run nxf_trace
}

nxf_main() {
    NXF_SCRATCH="$(set +u; nxf_mktemp $TMPDIR)"
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /pscratch/scratch4/btsheal/benchmark-nf/kinc/work/da/06deebb463f498dece3d3cccc791eb/.command.begin
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    # DEBUG: now we are in the scratch directory
    pwd

    ( nxf_launch ) >$cout 2>$cerr &
}

$NXF_ENTRY
```

In summary, this run script stages the scratch directory and then calls itself in order to launch the task via `nxf_trace`. But since the run script changes to the work directory at the beginning, this throws off the scratch directory.

It seems like this bug could be fixed by changing `nxf_launch` accordingly:
```
nxf_launch() {
    nxf_trace
}
```

### Environment 

* Nextflow version: 19.07.0
* Java version: 1.8
* Operating system: Linux

**Comment by pditommaso** [comment] 2019-08-19 09:09
Possible duplicate of #1226 (?)

**Comment by bentsherman** [comment] 2019-08-19 15:01
I think it is, given that they're using the same executor and they're also using trace and scratch at the same time. I think the above fix would fix their problem as well.

**Comment by chrisjackson-pellicle** [comment] 2020-01-07 01:14
Hi Paolo,

I'm still having this issue in Nextflow 19.10.0 when using `scratch`, pbspro as the executor, and `-with-trace`. As described above, it appears to be caused when the run script calls itself in order to launch the task via `nxf_trace`, and the run script changes back to the work directory rather than staying in the scratch directory. 

The line near the beginning of the `.command.run` script that changes to the working directory appears to have its origin in the PbsExecutor.groovy script, line 76: 

> result += "cd ${quote(task.workDir)}\n"

Looking at the other executor groovy scripts, it looks like this might be an issue with Moab and NQSII, too, as they both contain the same line.

Is there any fix for this? I'd really like to use Nextflow's excellent tracing and visualisation features. Thanks!

**Comment by pditommaso** [comment] 2020-01-07 05:09
Damn, got it! I've pushed a patch on the master branch. You may want to give it a try (see the README to compile it locally).

**Closed by pditommaso** 2020-01-07 05:09 UTC

**Comment by chrisjackson-pellicle** [comment] 2020-01-07 23:01
All working now, thanks very much!
