### ISSUE TITLE
Add the support for Bioconda

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#493] opened 2017-10-24 09:16 UTC
The idea here is to provide a built-in support for [Bioconda](https://bioconda.github.io/) package manager as an alternative to Environment Modules. 

In principle it should be possible to add an option `-with-conda` which instructs to use any `module` declaration as *Conda* packages instead of *Environment Modules*. 

Alternatively it could be possible to add a new `conda` directive to allow the specification of conda packages, eg: `conda 'salmon baw'`

**Comment by pditommaso** [comment] 2017-11-04 11:05
Possible approach: 
1. the content of the `conda` directive is used to create a unique hash key
2. the hash locate the path of the file system where the conda environment is supposed to be stored.
3. if the environment file does not exists, create it with the command `conda create --use-index-cache --use-local --prefix $HASH_KEY --mkdir --yes -q <packages>
4. activate the environment with the command: `source activate $HASH_KEY`

Open question: 
1. where to store the conda environments? shared directory? node scratch dir? pipeline work-dir?
2. how to manage possible race condition when check the env file existence
3. how to import a user provided [yaml environment file](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)

**Comment by fstrozzi** [comment] 2017-11-07 12:37
That would be very useful. 

The main problem is managing the concurrent creation / access of a shared Conda environment from multiple tasks. Activating a shared Conda environment used to be problematic, but it is now fixed (see https://github.com/conda/conda/issues/2837). 

The creation of the Conda environment is probably the big issue to address. 

As already suggested, the ```conda``` directive in a running task could check if the environment corresponding to the ```$HASH_KEY``` is already there, if so than it will simply "source" it, if not then the task will create the environment. 

I am unsure what could be the best approach then to avoid race conditions from multiple tasks trying to create the same environment at the same time because it does not exist yet. Maybe this could be handled directly by Nextflow to guarantee that only one task (the very first one starting) will create the conda environment, putting on hold the others ?

**Comment by pditommaso** [comment] 2017-11-07 16:46
The conda environment creation can be managed a NF level somehow similar to how a singularity image is downloaded once. To avoid avoid race condition with multiple NF instances, the `env` must be created in the pipeline work directory, and should depend to the workflow execution `sessionId`. 

Then the env action should be managed in the script wrapped, provided concurrent activation is not a problem as it seems.

**Comment by fstrozzi** [comment] 2017-11-07 20:18
Good. The only issue could be that creating the conda```env``` in the working directory may not work in the cloud where the working dir can also be on an object storage.

**Comment by pditommaso** [comment] 2017-11-08 07:50
This is true, but I see *conda* as an option for people not able to use containers, mainly HPC folks. 

However this bring to another interesting discussion. Since for each bioconda recipe they create a biocontainer image, it could be nice to have a transparent interoperability between the two (in a similar manner Galaxy is doing if I'm not wrong).

There shouldn't be any technical problem, however still I'm not sure about two things: 
1) is there a consistent mapping between bioconda recipes and biocontainers, if so how resolve each other in term on names
2) should NF introduce a new directive `conda` for conda/bioconda recipes? if so, how biocontainers should be automatically managed? should the `container` directive used or it could be introduced a new option `-with-bioconda` which turns all `conda` defs into implicit `container` directives ?

**Comment by apeltzer** [comment] 2017-11-08 08:52
I think it would be very useful to support `conda` as an alternative. I believe its quite a strong system for people not being able to use containers (even though singularity aims at something similar in terms of HPC support and we're now actively using it for example). 

As far as your two questions go:

1.) I believe there is no consistent mapping between bioconda recipes and biocontainers (yet?). 
2.) Yes, please. I think having a `-with-bioconda` option would be the best for the time being. The problem is, that a.) there is no mapping currently between bioconda recipes and biocontainers so that would be somewhat misleading for new users. So better turn all `conda` defs into implicit `container` directives. 

Just my two cents, I'll comment again when new things are coming up!

**Comment by ypriverol** [comment] 2017-11-08 12:20
@apeltzer for every bioconda package you will be able to find theproper biocontainer here: 

quay.io/biocontainers/ 

for example this is the searchgui container for the corresponding conda recipe 

https://quay.io/repository/biocontainers/searchgui

**Comment by pditommaso** [comment] 2017-11-08 12:30
Nice. This means that we can can assume that for each bioconda recipe there's an equivalent biocontainer, that's what we are discussing. Thanks @ypriverol.

**Comment by fstrozzi** [comment] 2017-11-08 13:21
This is cool. If I am right Biocontainers as well as Bioconda recipes include a single tool at the time. In this case what about situations where a task may rely on more than one package? For instance the tipical bwa + samtools situation, in that case a mapping between a conda recipe and a (bio)container would not work as expected I am afraid, since both packages will be required in the same process (and environment) for the task to run correctly.

**Comment by pditommaso** [comment] 2017-11-10 13:14
Yes, in the case more that a conda recipe is specified, the container cannot be matted automatically. IMO it should report an error unless an explicit `container` image is provided.

**Comment by danfulop** [comment] 2018-02-27 22:57
Is there currently a workaround for loading a conda env to be used by an NF pipeline?

**Comment by pditommaso** [comment] 2018-02-28 08:56
You can simple activate the conda recipes and the run NF

**Comment by danfulop** [comment] 2018-02-28 08:57
Thanks @pditommaso. That's exactly what I'm doing, activating the conda env before running NF.

**Comment by stevekm** [comment] 2018-03-23 14:33
Would this be limited to just Bioconda specifically? The system I am trying to use has a lot of support for Biobuilds (https://biobuilds.org/), which runs on `conda`, whereas building Docker or Singularity containers is problematic due to the combination of non-x86_64 architecture + limited user system rights.

**Comment by pditommaso** [comment] 2018-03-24 10:49
Being a `conda` channel as bioconda, it's supposed to be supported.

**Comment by karl616** [comment] 2018-04-10 07:28
> bwa + samtools situation

Biocontainers support multi-package containers:

https://github.com/BioContainers/multi-package-containers

I haven't tried it out yet but it looks very convenient

**Comment by ypriverol** [comment] 2018-04-10 07:36
We are working to move that to production we will let you know soon.

**Comment by stevekm** [comment] 2018-04-10 23:46
"The creation of the Conda environment is probably the big issue to address."

Wouldn't the creation of the `env` be left up to the end user and outside the scope of NF itself? The fact that you can automatically pull missing Docker & Singularity containers seems like an incidental bonus to using those and not necessarily a feature that NF would have to go out of it's way to replicate. Thoughts?

**Comment by pditommaso** [comment] 2018-04-11 09:47
> Wouldn't the creation of the env be left up to the end user and outside the scope of NF itself?

In principle not, the user should  be able to define the conda packages or a recipe file, then NF should create and activate the it for each task. 

When having a different environment for each process it would be overwhelming for the user to create manually all of them. 

> The fact that you can automatically pull missing Docker & Singularity containers seems like an incidental bonus to using those and not necessarily a feature that NF would have to go out of it's way to replicate.  

Not understanding this. How containers are related to Conda?

**Comment by pditommaso** [comment] 2018-04-25 16:01
Adding for reference some example of conda env files:
 
https://github.com/nf-core/RNAseq/blob/master/environment.yml
https://github.com/nf-core/methylseq/blob/master/environment.yml
https://github.com/nf-core/RNAseq/blob/master/Dockerfile

An interesting idea to investigate could be to create a Conda environment and mount the dependencies bin path into a minimal container such as busybox. This would mix the benefits of container isolation with easy tools configuration.

**Comment by pditommaso** [comment] 2018-04-25 19:58
Another round here. Now it supports Conda environment yaml files. 

Therefore Conda can be specified using the package names, for example: 

```
process foo {
  conda 'bwa=0.7.12 bioconda::star=2.5.4a'

  '''
  bwa || true
  STAR || true
  '''
}   
```

(note: the `::` prefix to specify an optional channel name)

or specifying the path of a yml env file, as shown below: 

```
process foo {
  conda 'some/path/env.yml'

  '''
  bwa || true
  STAR || true
  '''
}   
```

where the yml provide the env using the conda format: 

```
name: my-env-1.0
channels:
  - bioconda
  - defaults
dependencies:
  # Default bismark
  - star=2.5.4a
  - bwa=0.7.15
```

note: relative paths are resolved against the launching directive, therefore better to specify an abs path using the `$baseDir` variable.

As usual the `conda` directive can (and is expected to) be specified in the `nextflow.config` file as any other directive. 

I've uploaded it as `0.30.0-SNAPSHOT` version, please give it a try. Your feedback is important.

**Comment by pditommaso** [comment] 2018-04-26 20:58
Added option `-with-conda <yml file>` to specify the Conda env on the run command line as suggested by @ewels.

**Comment by ewels** [comment] 2018-04-30 22:48
Brilliant! Next one - can we have `process.conda` always defined, but turned on and off with `conda.enabled`? I’m thinking along the same lines of how singularity and docker can be configured.

**Comment by pditommaso** [comment] 2018-05-02 11:49
We had a similar discussion for Environment `module`s (which does not require a `enable` flag) and the outcome is that it's not really needed using a configuration profile to enable it. See #522. 

With the container it makes more sense, because the same container can be used by multiple runtime, therefore you need a way to enable/disable a runtime execution. I think it would be useful in this case.

**Comment by karl616** [comment] 2018-05-02 15:48
I tried to pull the conda branch and build it locally, but the created executable does not recognize the -with-conda flag (```nextflow run -with-conda```). After a bit of looking around, I realized that running launch.sh works. This seems to work... 

I have a small test-case I have been playing around with. I will run this.

**Comment by karl616** [comment] 2018-05-03 14:32
I have problems. I'm trying to run grape-nf with an environment file that works if I load it prior to execution. Running with the `-with-conda` flag I initially get the error below and nothing is executed. Executing the same command a second time, nextflow finds the environment, and starts executing steps. What is peculiar to me is that for some executables can be found (STAR) (I cleared them out of the path prior to starting nextflow), while other are missing (RSEM).

My expectation was that the whole pipeline would be executed inside the provided environment, but maybe I misunderstood? Do I have to update the workflow to benefit from conda?

Below is the error from the first round of execution and attached is the environment. The second execution does not throw any uncatched errors to .nextflow.log, but simply fails to execute.

```
May-03 16:09:52.408 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 't_index (GCA_000001405-RSEM-1.2.21)'

Caused by:
  Failed to create Conda environment
  command: conda env create --prefix /tmp/180308.testGrapeWithBioconda/output/sample/work2/conda/grape-nf-9dba98e1cf0eb4afbf31ee8ba67f7f58 --file /tmp/180308.testGrapeWithBioconda/output/sample/grape-nf_environment.yaml
  status : 143
  message:


java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Conda environment
  command: conda env create --prefix /tmp/180308.testGrapeWithBioconda/output/sample/work2/conda/grape-nf-9dba98e1cf0eb4afbf31ee8ba67f7f58 --file /tmp/180308.testGrapeWithBioconda/output/sample/grape-nf_environment.yaml
  status : 143
  message:

	at nextflow.conda.CondaCache.getCachePathFor(CondaCache.groovy:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at nextflow.processor.TaskRun.getCondaEnv(TaskRun.groovy:555)
	at nextflow.processor.TaskBean.<init>(TaskBean.groovy:122)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at nextflow.executor.BashWrapperBuilder.<init>(BashWrapperBuilder.groovy:257)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at nextflow.executor.LocalTaskHandler.submit(LocalExecutor.groovy:116)
	at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:201)
	at nextflow.processor.LocalPollingMonitor.submit(LocalPollingMonitor.groovy:195)
	at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:481)
	at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1092)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.run(Closure.java:499)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Failed to create Conda environment
  command: conda env create --prefix /tmp/180308.testGrapeWithBioconda/output/sample/work2/conda/grape-nf-9dba98e1cf0eb4afbf31ee8ba67f7f58 --file /tmp/180308.testGrapeWithBioconda/output/sample/grape-nf_environment.yaml
  status : 143
  message:

	at nextflow.conda.CondaCache.runCommand(CondaCache.groovy:230)
	at nextflow.conda.CondaCache.createLocalCondaEnv0(CondaCache.groovy:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.doCall(CondaCache.groovy:173)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.call(CondaCache.groovy)
	at nextflow.file.FileMutex.lock(FileMutex.groovy:109)
	at nextflow.conda.CondaCache.createLocalCondaEnv(CondaCache.groovy:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure2.doCall(CondaCache.groovy:257)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure2.call(CondaCache.groovy)
	at groovyx.gpars.dataflow.LazyDataflowVariable$1.run(LazyDataflowVariable.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 common frames omitted
May-03 16:09:52.418 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.IllegalStateException: Failed to create Conda environment
  command: conda env create --prefix /tmp/180308.testGrapeWithBioconda/output/sample/work2/conda/grape-nf-9dba98e1cf0eb4afbf31ee8ba67f7f58 --file /tmp/180308.testGrapeWithBioconda/output/sample/grape-nf_environment.yaml
  status : 143
  message:
```
[grape-nf_environment.yaml.gz](https://github.com/nextflow-io/nextflow/files/1971290/grape-nf_environment.yaml.gz)

**Comment by pditommaso** [comment] 2018-05-03 14:42
It should work as you expected. The error message contains the conda command executed and the error message. 

```
  Failed to create Conda environment
  command: conda env create --prefix /tmp/180308.testGrapeWithBioconda/output/sample/work2/conda/grape-nf-9dba98e1cf0eb4afbf31ee8ba67f7f58 --file /tmp/180308.testGrapeWithBioconda/output/sample/grape-nf_environment.yaml
  status : 143
  message:
```

The 143 error code makes me think that the process has been killed because takes too long. Could it be possible. You can check that in the previous log file timestamp.

**Comment by karl616** [comment] 2018-05-03 15:05
I'm not entirely sure what's start and what's stop stamps, but I see a very nice increment of 5 min-intervals in the log file. I attached a slightly cleaned up version, so if there are inconsistencies that might be the reason.
[nextflow.log.2.gz](https://github.com/nextflow-io/nextflow/files/1971453/nextflow.log.2.gz)

Running the command presented in the log file in the terminal takes 7m23s. It could be an explanation. I don't have enough conda experience to tell what half an environment will look like. But perhaps this explains why some software is there and others not. Still, the error from the second execution persists after manual creation of the environment.

**Comment by karl616** [comment] 2018-05-04 14:56
After spending some time with it, I think my problem is associated with my own system:

https://github.com/conda/conda/issues/7253

**Comment by karl616** [comment] 2018-05-09 14:47
After resolving my conda problems everything seems to run smoothly... Is there a plan for when this will be incorporated in the stable release?

**Comment by pditommaso** [comment] 2018-05-09 14:56
Nice, likely in 2-3 weeks.

**Comment by pditommaso** [comment] 2018-05-18 19:16
Merged on master. Documentation is available at these links 
https://github.com/nextflow-io/nextflow/blob/master/docs/conda.rst
https://github.com/nextflow-io/nextflow/blob/master/docs/process.rst#conda
https://github.com/nextflow-io/nextflow/blob/master/docs/config.rst#scope-conda

**Closed** 2018-05-18 19:15 UTC
Labels: kind/feature, pri/high

**Comment by crickbabs** [comment] 2018-07-25 16:14
Hi Paolo. I am trying to access the path to a conda environment created by nextflow using a yml file within my "main.nf" script. Is this possible? I tried to look into the source code but I obviously didnt have my groovy glasses on!

**Comment by pditommaso** [comment] 2018-07-25 16:16
Not sure to understand, anyhow please use the [google forum](https://groups.google.com/forum/#!forum/nextflow) or the [gitter channel](https://gitter.im/nextflow-io/nextflow) for question.
