### ISSUE TITLE
`collectFile` does not work if `name` is not specified

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1017] opened 2019-02-05 20:09 UTC
### Expected behavior and actual behavior

When `collectFile()` it used on a channel without the `name` keyword argument specified, it would be expected to use some default name instead. 

Instead, it passes the items through the channel, seemingly unchanged and un-collected. 

### Steps to reproduce the problem

Example workflow:

`collectFile()` used without a name specified:

```
Channel.from( ['Sample1','Sample2','Sample3'] ).into { samples; samples2 }

params.output_dir = "output"

process make_file {
    tag { "${sampleID}" }
    echo true
    publishDir "${params.output_dir}/make_file", mode: 'copy', overwrite: true

    input:
    val(sampleID) from samples

    output:
    file("${sampleID}.txt") into (sample_files, sample_files2)

    script:
    """
    echo "[make_file] ${sampleID}"
    echo "[make_file] ${sampleID}" > "${sampleID}.txt"
    """
}
sample_files.collectFile().set { collected_file }

process print_collected_file {
    echo true

    input:
    file(txt) from collected_file

    script:
    """
    cat "${txt}" | sed -e 's|^|[print_collected_file (${txt})]: |'
    """
}

```

output:

```
./nextflow run main.nf
N E X T F L O W  ~  version 19.01.0
Launching `main.nf` [grave_hypatia] - revision: 8010795775
[warm up] executor > local
[44/9690f5] Submitted process > make_file (Sample2)
[37/5b6dcd] Submitted process > make_file (Sample3)
[4d/3bb8ef] Submitted process > make_file (Sample1)
[make_file] Sample2
[make_file] Sample3
[make_file] Sample1
[7c/9cd395] Submitted process > print_collected_file (2)
[6b/131fa8] Submitted process > print_collected_file (1)
[5a/090800] Submitted process > print_collected_file (3)
[print_collected_file (Sample2.txt)]: [make_file] Sample2
[print_collected_file (Sample1.txt)]: [make_file] Sample1
[print_collected_file (Sample3.txt)]: [make_file] Sample3
```

Here, the `print_collected_file` process got called 3 times, because 3 files were emitted by the channel `collected_file`, which was supposed to be passing along the `collectFile` output. 

However, if you add the `name` argument to `collectFile` like this:

```
sample_files.collectFile(name: 'sample_files.txt').set { collected_file }
```

You get this output:

```
./nextflow run main.nf
N E X T F L O W  ~  version 19.01.0
Launching `main.nf` [elegant_northcutt] - revision: 787d9dd75e
[warm up] executor > local
[a3/04c1d8] Submitted process > make_file (Sample1)
[ba/4e14c4] Submitted process > make_file (Sample2)
[05/f79376] Submitted process > make_file (Sample3)
[make_file] Sample1
[make_file] Sample2
[make_file] Sample3
[db/139887] Submitted process > print_collected_file (1)
[print_collected_file (sample_files.txt)]: [make_file] Sample2
[print_collected_file (sample_files.txt)]: [make_file] Sample3
[print_collected_file (sample_files.txt)]: [make_file] Sample1
```

Here, the `print_collected_file` process is only run once and it receives the single `collectFile` output; I think that this would be the expected action in both cases.

### Environment 

* Nextflow version: 19.01.0

* Java version: 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

* Operating system: macOS, RHEL 7

### Additional context

Its not clear to me if this functionality is a bug, or intended, but it does not appear to be documented. If this is intended, maybe we could have the docs updated to reflect that `name` is required in order for the collection to work?

**Comment by pditommaso** [comment] 2019-02-06 08:38
Duplicate of #138 (?)

**Comment by stevekm** [comment] 2019-02-06 12:10
Oh yeah looks like a duplicate then

**Comment by pditommaso** [comment] 2019-02-06 12:34
OK, closing this in favour of #138.

**Closed by pditommaso** 2019-02-06 12:34 UTC
