### ISSUE TITLE
Not possible to use same output directory on s3 more than once with AWS Bach

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#916] opened 2018-11-07 08:30 UTC
## Bug report 

Not possible to use same output directory on s3 more than once with AWS Bach

### Expected behavior and actual behavior

I would expect to be able to use the same output directory more than once

### Program output 

```
N E X T F L O W  ~  version 18.10.1
Launching `main.nf` [insane_ritchie] - revision: dc6de99e6c
ERROR ~ Unexpected error [UnsupportedOperationException]

 -- Check '.nextflow.log' file for details
```

`.nextflow.log`
```bash
Nov-07 09:24:48.230 [main] DEBUG nextflow.cli.Launcher - $> /home/max/bin/nextflow run main.nf -profile awsbatch -work-dir s3://sarek-work --outDir s3://sarek-results/results_tiny --sample Sarek-data/testdata/tsv/tiny-manta-s3.tsv --genome smallGRCh37 --verbose --genome_base s3://sarek-references/small
Nov-07 09:24:48.345 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 18.10.1
Nov-07 09:24:48.362 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [insane_ritchie] - revision: dc6de99e6c
Nov-07 09:24:48.383 [main] DEBUG nextflow.config.ConfigBuilder - Found config home: /home/max/.nextflow/config
Nov-07 09:24:48.384 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/max/workspace/github/Sarek/nextflow.config
Nov-07 09:24:48.384 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/max/.nextflow/config
Nov-07 09:24:48.385 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/max/workspace/github/Sarek/nextflow.config
Nov-07 09:24:48.421 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `awsbatch`
Nov-07 09:24:48.819 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `awsbatch`
Nov-07 09:24:49.341 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [standard, slurm, cfc, awsbatch, singularity, slurmDownload, docker, singularityPath, binac]
Nov-07 09:24:49.383 [main] DEBUG nextflow.Session - Session uuid: 11fddaaa-310c-4591-9ae0-c492db7af845
Nov-07 09:24:49.383 [main] DEBUG nextflow.Session - Run name: insane_ritchie
Nov-07 09:24:49.384 [main] DEBUG nextflow.Session - Executor pool size: 8
Nov-07 09:24:49.397 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 18.10.1 build 5003
  Modified: 24-10-2018 14:03 UTC (16:03 CEST)
  System: Linux 4.15.0-38-generic
  Runtime: Groovy 2.5.3 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_191-b12
  Encoding: UTF-8 (UTF-8)
  Process: 7976@skadi [127.0.1.1]
  CPUs: 8 - Mem: 15.3 GB (6.1 GB) - Swap: 15.6 GB (15.6 GB)
Nov-07 09:24:49.427 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Nov-07 09:24:49.434 [main] DEBUG nextflow.Global - Using AWS credentials defined in nextflow config file
Nov-07 09:24:49.435 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=HB2ZCx.., region=eu-west-1, access_key=AKIAJM..}
Nov-07 09:24:50.456 [main] DEBUG nextflow.file.FileHelper - Can't check if specified path is NFS (1): /sarek-work/

Nov-07 09:24:50.456 [main] DEBUG nextflow.Session - Work-dir: s3://sarek-work/ [null]
Nov-07 09:24:50.796 [main] DEBUG nextflow.Session - Session start invoked
Nov-07 09:24:50.799 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Nov-07 09:24:50.800 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /sarek-results/results_tiny/Reports/Sarek_trace.txt
Nov-07 09:24:51.170 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.UnsupportedOperationException: null
        at com.upplication.s3fs.S3FileSystemProvider.move(S3FileSystemProvider.java:554)
        at java.nio.file.Files.move(Files.java:1395)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at nextflow.extension.FilesEx.renameTo(FilesEx.groovy:608)
        at nextflow.extension.FilesEx$renameTo.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at nextflow.extension.FilesEx.rollFile0(FilesEx.groovy:1359)
        at nextflow.extension.FilesEx.rollFile0(FilesEx.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:224)
        at nextflow.extension.FilesEx.rollFile(FilesEx.groovy:1333)
        at nextflow.extension.FilesEx.rollFile(FilesEx.groovy)
        at nextflow.trace.TraceFileObserver.onFlowStart(TraceFileObserver.groovy:201)
        at nextflow.Session$_start_closure17.doCall(Session.groovy:496)
        at nextflow.Session$_start_closure17.call(Session.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
        at nextflow.Session.start(Session.groovy:496)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:157)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:240)
        at nextflow.cli.Launcher.run(Launcher.groovy:428)
        at nextflow.cli.Launcher.main(Launcher.groovy:586)
```

### Steps to reproduce the problem

cf https://github.com/SciLifeLab/Sarek/issues/680

### Environment 

* Nextflow version: 18.10.1 
* Java version: [?]
* Operating system: Amazon ECS-Optimized Amazon Linux AMI

**Comment by pditommaso** [comment] 2018-11-08 18:33
Not sure to understand what do you mean by * use the same output directory more than once* ?

**Comment by MaxUlysse** [comment] 2018-11-09 08:41
When I try to run Sarek, and output our results on an empty bucket, the first time would work, and the second time I'll get this error

**Comment by pditommaso** [comment] 2018-11-09 08:44
I guess it's an issue with the S3 library which  requires at least a directory in the S3 bucket. Could you try `s3://sarek-work/something` instead of `s3://sarek-work` ?

**Comment by MaxUlysse** [comment] 2018-11-09 08:49
It's not with the `-w s3://sarek-work` that we have an issue, but with the `--outDir s3://sarek-results/results_tiny`

**Comment by pditommaso** [comment] 2018-11-09 08:52
I have no idea what `outDir` is. List the exact steps to replicate the problem.

**Comment by MaxUlysse** [comment] 2018-11-09 09:14
I'll work on that as soon as I can get my hands on a computer ;-)

**Comment by alneberg** [comment] 2018-12-10 13:52
@pditommaso, I'm pretty sure this problem is caused when Nextflow attempts to roll the trace file which is present within the s3 bucket. This uses the 'move' operation which is not supported in the s3 implementation:
https://github.com/nextflow-io/nextflow-s3fs/blob/6e3e6c4bef34ea84d30d40ca02769d2d7e25a72d/src/main/java/com/upplication/s3fs/S3FileSystemProvider.java#L552-L555

Disabling a trace file in the config seems to circumvent this issue. Do you think it would be possible to implement the s3 move operation by copy + delete?

**Comment by pditommaso** [comment] 2018-12-12 09:58
@alneberg therefore this issue is a duplicate of #813 ?

**Comment by alneberg** [comment] 2018-12-12 10:04
Yes I would say so, so feel free to close this one. Thanks!

**Comment by pditommaso** [comment] 2018-12-12 10:04
OK. Don't put trace files in S3 for now!

**Closed by pditommaso** 2018-12-12 10:04 UTC
Labels: platform/aws-batch, triage/needs-information
