### ISSUE TITLE
SLURM  Unable to re-submit task 

### ISSUE THREAD

**Issue by rwtaylor** [nextflow-io/nextflow#234] opened 2016-10-26 23:55 UTC
Hi,

I am using nextflow to submit jobs to a SLURM cluster. The queue allows for preemption by each nodes 'owner'. So, I think that preemption is what is killing some jobs. Nextflow is erroring and exiting when it attempts to resubmit the job. Surprisingly, the initial job continues to run, which may be why nextflow can not resubmit the job. One, time I think I saw the killed-job marked with 'BeginTime' in the queue. Which, I think means that the "The job's earliest start time has not yet been reached.". So, maybe SLURM is suspending the nextflow-job while the owner's-job is running?

Also, when nextflow exits with the below error, **all** of the initial processes continue to run until they finish or fail.

Is there anything I can do to troubleshoot?

Here is the error in the .nextflow.log: 

```
Oct-26 09:59:38.041 [Thread-3] DEBUG n.processor.TaskPollingMonitor - !! executor slurm > tasks to be completed: 45 -- first: TaskHandler[jobId: 10467359; id: 2; name: Freebayes1 (1); status: RUNNING; exit: -; workDir: /scratch/PI/dpetrov/2016-tiger-wgs/freebayes-vc1/work/29/1572dc2d5090f54e31e33241551511 started: 1477500883593; exited: -; ]
Oct-26 09:59:40.085 [Thread-3] WARN  nextflow.processor.TaskProcessor - Process `Freebayes1 (17)` terminated with an error exit status (143) -- Execution is retried (1)
Oct-26 09:59:40.166 [pool-2-thread-1] DEBUG nextflow.executor.GridTaskHandler - Launching process > Freebayes1 (17) -- work folder: /scratch/PI/dpetrov/2016-tiger-wgs/freebayes-vc1/work/87/48924f11a437002c7605c036ab8289
Oct-26 09:59:40.471 [pool-2-thread-1] ERROR nextflow.processor.TaskProcessor - Unable to re-submit task `Freebayes1 (17)`
Oct-26 09:59:40.477 [pool-2-thread-1] DEBUG nextflow.Session - Session aborted -- Cause: Error submitting process 'Freebayes1 (17)' for execution
Oct-26 09:59:40.480 [Thread-3] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: slurm)
Oct-26 09:59:40.486 [main] DEBUG nextflow.Session - Session await > processes completed
Oct-26 09:59:40.487 [main] DEBUG nextflow.Session - Session await > done
Oct-26 09:59:40.504 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (44)
Oct-26 09:59:41.195 [main] DEBUG nextflow.Session - Session destroyed

```

Here is the process:

```
process Freebayes1 {
  publishDir "outputs/regionVCFs"
  tag "$regionTask"

  cpus { 1 }
  memory { 32.GB * task.attempt }
  time { 2.d * task.attempt }
  errorStrategy { task.exitStatus == 143 ? 'retry' : 'finish' }
  maxRetries 3
  maxErrors '-1'

  input:
  file(bams) from bamFiles.first()
  file(bais) from baiFiles.first()
  set regionTask, regions from regionTasks
    file params.genome
    file params.genomeIndex

  output:
  set regionTask, file("${regionTask}.raw.snps.indels.vcf") into region_VCFs

  script:
  input_bams = bams.collect{"-b $it"}.join(' ')

  """
  freebayes --use-best-n-alleles 4 \
    -f $params.genome \
    $input_bams \
    $regions > region_${regionTask}.vcf

  """
}

```

**Comment by pditommaso** [comment] 2016-10-27 13:30
It seems to me that this is a duplicate of #226. What it's happening is that SLURM in order to suspend the job, kill and then reschedule it. 

Currently nextflow is not able to handle this condition, but I may try to implement a patch to manage it correctly.

**Comment by pditommaso** [comment] 2016-10-27 18:35
@rwtaylor @dctrud I've just uploaded a new snapshot that should fix this issue. You may want to give a try defining in your environment the following var, then using NF as usual: 

```
export NXF_VER=0.22.4-SNAPSHOT
```

**Comment by pditommaso** [comment] 2016-10-31 09:50
@rwtaylor @dctrud any feedback on this issue (unfortunately I dont have access to a slurm cluster to test it)?

**Comment by rwtaylor** [comment] 2016-11-01 19:11
@pditommaso I'm running a long pipeline now with 0.22.4-SNAPSHOT, so I expect some of these suspensions to happen. I'll let you know if Nextflow successfully resubmits! I'm not really sure how to tell if the error (143) given by SLURM is a suspension, or due to a resource violation (like using too much memory).

**Comment by rwtaylor** [comment] 2016-11-01 20:38
@pditommaso It looks like nextflow was able to resubmit some, but not all tasks.

```
[rwtaylor@sh-17-25 /scratch/PI/dpetrov/2016-tiger-wgs/preprocessing/pre-161030]$ tail slurm-10573844.out 
[6c/dc5207] Re-submitted process > Mapping (ASS1-L001_5)
WARN: Process `Mapping (BAN1-L001_5)` terminated with an error exit status (143) -- Execution is retried (1)
[96/507b97] Re-submitted process > Mapping (BAN1-L001_5)
WARN: Process `Mapping (RTR3-L004_2)` terminated with an error exit status (143) -- Execution is retried (2)
ERROR ~ Unable to re-submit task `Mapping (RTR3-L004_2)`

 -- Check '.nextflow.log' file for details
Pipeline completed at: Tue Nov 01 13:17:48 PDT 2016
Execution status: failed
WARN: Killing pending tasks (68)

```

```[rwtaylor@sh-17-25 /scratch/PI/dpetrov/2016-tiger-wgs/preprocessing/pre-161030]$ tail .nextflow.log -n20
Nov-01 13:17:21.058 [pool-2-thread-4] DEBUG nextflow.executor.GridTaskHandler - Launching process > Mapping (BAN1-L001_5) -- work folder: /scratch/PI/dpetrov/2016-tiger-wgs/preprocessing/pre-161030/work/96/507b974b3a3a521d40aebbe2a1de07
Nov-01 13:17:31.076 [pool-2-thread-4] INFO  nextflow.Session - [96/507b97] Re-submitted process > Mapping (BAN1-L001_5)
Nov-01 13:17:31.513 [Thread-7] WARN  nextflow.processor.TaskProcessor - Process `Mapping (RTR3-L004_2)` terminated with an error exit status (143) -- Execution is retried (2)
Nov-01 13:17:31.515 [pool-2-thread-5] DEBUG nextflow.executor.GridTaskHandler - Launching process > Mapping (RTR3-L004_2) -- work folder: /scratch/PI/dpetrov/2016-tiger-wgs/preprocessing/pre-161030/work/b8/c595588aaea67af837d22e468e1097
Nov-01 13:17:48.382 [pool-2-thread-5] ERROR nextflow.processor.TaskProcessor - Unable to re-submit task `Mapping (RTR3-L004_2)`
Nov-01 13:17:48.383 [pool-2-thread-5] DEBUG nextflow.Session - Session aborted -- Cause: Error submitting process 'Mapping (RTR3-L004_2)' for execution
Nov-01 13:17:48.386 [Thread-7] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: slurm)
Nov-01 13:17:48.386 [main] DEBUG nextflow.Session - Session await > processes completed
Nov-01 13:17:48.386 [main] DEBUG nextflow.Session - Session await > done
Nov-01 13:17:48.388 [Actor Thread 216] DEBUG nextflow.processor.TaskProcessor - <Mapping> After stop
Nov-01 13:17:48.389 [Actor Thread 218] DEBUG nextflow.processor.TaskProcessor - <MarkDuplicates> After stop
Nov-01 13:17:48.389 [Actor Thread 215] DEBUG nextflow.processor.TaskProcessor - <CreateIntervals> After stop
Nov-01 13:17:48.390 [Actor Thread 209] DEBUG nextflow.processor.TaskProcessor - <IndexBams> After stop
Nov-01 13:17:48.391 [Actor Thread 215] DEBUG nextflow.processor.TaskProcessor - <Realign> After stop
Nov-01 13:17:48.391 [Actor Thread 209] DEBUG nextflow.processor.TaskProcessor - <FlagStatRealign> After stop
Nov-01 13:17:48.391 [Actor Thread 217] DEBUG nextflow.processor.TaskProcessor - <FlagStat> After stop
Nov-01 13:17:48.421 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (68)
Nov-01 13:17:48.487 [main] DEBUG nextflow.trace.TraceFileObserver - Flow completing -- flushing trace file
Nov-01 13:17:48.521 [main] DEBUG nextflow.trace.TimelineObserver - Flow completing -- rendering html timeline
Nov-01 13:17:48.762 [main] DEBUG nextflow.Session - Session destroyed
[rwtaylor@sh-17-25 /scratch/PI/dpetrov/2016-tiger-wgs/preprocessing/pre-161030]$ 

```

**Comment by pditommaso** [comment] 2016-11-01 21:12
Something didn't work as expected. That jobs returning should not enter in a error status and neither re-submitted. Could you please attach the `.nextflow.log` file for that run.

**Comment by rwtaylor** [comment] 2016-11-01 22:31
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/565213/nextflow.log.txt)

**Comment by rwtaylor** [comment] 2016-11-02 14:22
The pipeline has now been running for 9 hours without exiting. A number of processes seem to have been resubmitted successfully. But, at least 1 process has been duplicated.

```
[rwtaylor@sherlock-ln01 login_node /scratch/PI/dpetrov/2016-tiger-wgs/preprocessing/pre-161030]$ squ
   JOBID PART                                 NAME     USER    STATE       TIME TIME_LIMIT CPU MIN_MEMO PRIO NODELIST(REASON)                  
10606421 owne      nf-MarkDuplicates_(ASS1-L001_5) rwtaylor  RUNNING      14:30 1-16:00:00 16       64G 2663 sh-18-29                          
10606407 dpet      nf-MarkDuplicates_(ASS1-L001_5) rwtaylor  RUNNING      12:25   20:00:00 8        32G 2200 sh-27-24                          
10606412 dpet     nf-MarkDuplicates_(BGAR1-L001_5) rwtaylor  RUNNING      24:11   20:00:00 8        32G 2200 sh-27-23                          
10606078 owne             nf-Mapping_(WAY3-L001_5) rwtaylor  RUNNING    1:03:12   20:00:00 8        32G 2200 sh-18-20                          
10605487 owne      nf-MarkDuplicates_(RTR5-L001_5) rwtaylor  RUNNING    1:12:25   20:00:00 8        32G 2200 sh-0-4                            
10605459 owne      nf-MarkDuplicates_(BAN1-L001_5) rwtaylor  RUNNING    1:13:37   20:00:00 8        32G 2200 sh-0-1                            
10603483 owne      nf-MarkDuplicates_(WAY9-L001_5) rwtaylor  RUNNING    1:37:06   20:00:00 8        32G 2200 sh-18-13                          
10603429 owne      nf-MarkDuplicates_(WAY2-L001_5) rwtaylor  RUNNING    1:38:03   20:00:00 8        32G 2200 sh-18-16                          
10599313 owne            nf-Mapping_(WAY10-L001_5) rwtaylor  RUNNING    9:14:40   20:00:00 8        32G 2200 sh-8-33                           
10599315 owne            nf-Mapping_(WAY12-L001_5) rwtaylor  RUNNING    9:14:40   20:00:00 8        32G 2200 sh-8-9                            
10599296 dpet                           pre-161030 rwtaylor  RUNNING    9:16:01 2-00:00:00 2         8G 1540 sh-27-24                          

```

**Comment by pditommaso** [comment] 2016-11-02 14:24
Could you include the `.nextflow.log` of this run as well?

**Comment by rwtaylor** [comment] 2016-11-02 14:49
[nextflow.log.2.txt](https://github.com/nextflow-io/nextflow/files/566861/nextflow.log.2.txt)

**Comment by pditommaso** [comment] 2016-11-03 14:13
The main problem with this issue is that SLURM to suspend a job kills and then restart it. From the NF the job killing is interpreted as a job failure, thus it will try to re-execute it because you specified that in the `errorStrategy`. 

Thus in the best scenario what would happen is that the pipeline is executed successfully though some jobs may be repeated (because they are restarted both by NF and SLURM). 

To make things more difficult it seems there's an issue that causes NF to fail when re-submitting a job.

Now, I think the only way to handle this problem it to prevent SLURM to resubmit an interrupted job. I'm not 100% sure but I think the `sbatch` command line option `--no-requeue` is meant for that. 


I've uploaded a new snapshot including this flag, you can try it doing the following 

````
CAPSULE_RESET=1 NXF_VER=0.22.4-SNAPSHOT nextflow info
```

Then run nextflow using the command:

```
NXF_VER=0.22.4-SNAPSHOT nextflow run .. etc
```

**Comment by rwtaylor** [comment] 2016-11-09 21:53
Hi @pditommaso,

Thanks, the pipeline now runs without resubmission failures. However, it seems that every `.command.err` file ends with something like this:
```
/scratch/PI/dpetrov/2016-tiger-wgs/preprocessing/ng-1/work/99/4e7412f162bedcc3a99ed778f4c409/.command.run.1: line 90: 191842 Terminated              nxf_trace "$pid" .command.trace
```

In most cases this is ok, but if the process fails then the error code doesn't seem to be captured and the pipeline continues as if the process completed successfully.

**Comment by rwtaylor** [comment] 2016-11-09 21:55
Here is the .nextflow.log

[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/581918/nextflow.log.txt)

**Comment by pditommaso** [comment] 2016-11-09 22:02
The message is expected when using `-trace` option. 

> In most cases this is ok, but if the process fails then the error code doesn't seem to be captured and the pipeline continues as if the process completed successfully.

I don't think it's related with that message neither with this issue.

**Comment by rwtaylor** [comment] 2016-11-09 22:03
Ok thanks

**Comment by pditommaso** [comment] 2016-11-09 22:50
I'm closing this issue. Feel free to reopen if you continue to experience the re-submit on suspend problem or open a new one for other issues.

**Closed by pditommaso** 2016-11-09 22:50 UTC
Labels: enhancement, WIP
