### ISSUE TITLE
Fix the configuration conflict warning due to deprecated containerOverrides 

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#2370] opened 2021-10-07 09:33 UTC
## Bug report 

When a custom job definition is used on AWS Batch with a different CPUs/Memory requirement, the job definition submitted by Nextflow using `containerOverrides` causes the following warning message to be displayed on AWS Batch UI.

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12799326/136358147-797acab5-8bca-496a-8efc-020538ddd750.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/12799326/136358246-c89e3576-3af6-48a0-919b-094f34ac747f.png">

**Reference:** 

https://docs.aws.amazon.com/batch/latest/userguide/troubleshooting.html#override-resource-requirements

**Comment by brett-diamondage** [comment] 2021-12-15 23:29
I'm very interested in seeing this fixes as well. If I could find where nextflow is implementing `containerOverrides` and `containerProperties`, I would be happy to submit a PR with a fix.

**Comment by pditommaso** [comment] 2021-12-16 09:35
This has already been addressed by this issue https://github.com/nextflow-io/nextflow/issues/2421

**Closed by pditommaso** 2021-12-16 09:35 UTC
Labels: platform/aws-batch

**Comment by wikiselev** [comment] 2022-01-25 17:17
Hi @pditommaso , just to clarify. I am launching my pipeline with *Nextflow 21.10.4 build 5656* via Tower on AWS and see the following in **every** container description on AWS batch:

![Screenshot 2022-01-25 at 17 04 48](https://user-images.githubusercontent.com/2342606/151025211-2509b511-de78-43d7-8a3a-0488c9094d1e.png)

When I click on any of the red signs this message pops up:
```
Configuration conflict
This value was submitted using containerOverrides.memory which has been deprecated and was not used as an override. 
Instead, the MEMORY value found in the job definition’s resourceRequirements key was used instead. 
More information about the deprecated key can be found in the AWS Batch API documentation.
```

However, the pipeline runs OK and finishes well. So it looks like the allocation of vcpu and memory is correct, but it's just 1 vcpu and 1024 Mb of memory in the container status on AWS. Is that the expected behaviour?

**Comment by pditommaso** [comment] 2022-01-25 17:43
This warning is reported because likely the AWS Batch job was created with the previous nextflow version using the old API. 

To address the problem, cleanup the job definition created in your Batch environment, so that they will recreated using the new API

**Comment by wikiselev** [comment] 2022-01-25 17:46
Beautiful, many thanks, @pditommaso !

**Comment by zichner** [comment] 2022-02-01 15:45
Thanks for the explanation and the workaround @pditommaso 
If one deletes the job definition and they get re-created with the latest Nextflow, would they still work when using an older version of Nextflow (e.g., v19.10.)? (Different people use different versions of Nextflow for the same pipelines).
Thanks.
