### ISSUE TITLE
Misleading error message from process syntax error

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/nextflow#3201] opened 2022-09-09 14:50 UTC
### Expected behavior and actual behavior

A missing comma resulted in producing an error reporting the process had been used already, rather than saying a comma was missing.

### Steps to reproduce the problem

Bugged example:
```nextflow
workflow {
    LENGTH( Channel.fromFilePairs( ['sampleA_{1,2}.txt','sampleB_1.txt'], size: -1 ) )
}

process LENGTH {
    input:
    tuple val(id) path(files)    // Syntax error is missing , here

    exec:
    println files
}
```

### Program output 

```console
% nextflow run main.nf
N E X T F L O W  ~  version 22.04.5
Launching `main.nf` [exotic_lavoisier] DSL2 - revision: b94845ecbd
Process 'LENGTH' has been already used -- If you need to reuse the same component include it with a different name or include in a different workflow context

 -- Check script 'main.nf' at line: 2 or see '.nextflow.log' file for more details

```

### Environment 

* Nextflow version: 22.04.5
* Java version: openjdk 17.0.3 2022-04-19 LTS
* Operating system: macOS
* Bash version: zsh 5.8.1 (x86_64-apple-darwin21.0)

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment] 2022-09-12 13:20
Duplicate of #3185

**Closed by bentsherman** 2022-09-12 13:20 UTC
Labels: triage/duplicate
