### ISSUE TITLE
List of length 1 is converted to path

### ISSUE THREAD

**Issue by Mashin6** [nextflow-io/nextflow#3341] opened 2022-11-02 12:31 UTC
## Bug report 
When creating a list with a single element containing a path, this list gets automatically converted to path object.

### Expected behavior and actual behavior
I would expect that list will always be passed to processes as list regardless of number of elements stored in it.

### Steps to reproduce the problem
``` groovy
process C {
    input:
    tuple val(id), path(reads)

    script:
    println reads.size()
}

workflow {
    ch_read_pairs = channel.fromFilePairs( params.reads, checkIfExists: true, size: -1  )
    ch_read_pairs.view()
    C( ch_read_pairs )
}
```

### Program output 
`nextflow run [test.nf](http://test.nf/) --reads *_\{R1,R2\}.fastq` returns number of elements
```
[temp, [/data/temp_R1.fastq, /data/temp_R2.fastq]]
2
```

`nextflow run [test.nf](http://test.nf/) --reads *_\{R1,\}.fastq` returns file size
```
[temp, [/data/temp_R1.fastq]]
62
```
### Environment 

* Nextflow version:  22.04.5 
* Java version: openjdk 17.0.3
* Operating system: linux
* Bash version: GNU bash, 4.4.23

### Additional context

Same happens when defining channel with ` Channel.of( [path('temp_R1.fastq')] )`

**Comment by bentsherman** [comment] 2022-11-02 15:33
Duplicate of #969, also related to #1236 and #2425. See this comment for the planned solution: https://github.com/nextflow-io/nextflow/issues/2425#issuecomment-1181923896

**Closed by bentsherman** 2022-11-02 15:33 UTC
Labels: lang/processes
