### ISSUE TITLE
Add direct support for Python package installer via Pip and virtual envs

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#4671] opened 2024-01-18 03:01 UTC
I am thinking we could add a new package provider (in addition to Conda and Spack) that uses Pyhton `pip` directly instead of Conda.

Advantages (non-exhaustive):
- Friendly and hence attractive to `pip` intensive communities (astronomers, data scientists)
- Quick install times, so easy add for both Nextflow and Wave
- Quicker than Conda for Pypi packages

Disadvantages (non-exhaustive):
- compared to conda, does not allow for mixing with non Pypi packages - however, it does target a different community
- yet another package manager in Nextflow - but worth the small effort IMHO

Example syntax (along the lines of `conda`):
```
process.pip `numpy pandas matplotlib`
```

To be supported in:
- Nextflow core
- Wave (through official `python` base images)

**Comment by marcodelapierre** [comment] 2024-01-18 03:01
Spun out of https://github.com/nextflow-io/nextflow/issues/4664

**Comment by pditommaso** [comment] 2024-01-18 08:27
What's the difference with https://github.com/nextflow-io/nextflow/issues/4664? 🤔

**Comment by marcodelapierre** [comment] 2024-01-18 09:08
> What's the difference with https://github.com/nextflow-io/nextflow/issues/4664? 🤔

The difference is that under the hood it would not use Conda but only Python + Pip (+ venv for encapsulation of packages).  
* Pip is faster, and in my (limited) experience also more robust for dependency resolution of Python packages.  
* On the other end, it only allows installations where packages ALL come from Pypi
* Final container size of conda vs pip : to be investigated

**Comment by bentsherman** [comment] 2024-01-18 11:38
Definitely need to use venv or some equivalent to have isolated environments

**Comment by pditommaso** [comment] 2024-01-22 08:14
Still believe this is a duplicate of https://github.com/nextflow-io/nextflow/issues/4664

**Comment by marcodelapierre** [comment] 2024-01-22 08:17
The distinct aspect of this one is to add support for a new package manager, Pip, in addition to the current ones, that are Conda and Spack.   

Pros and cons outlined in first comment at top.

**Comment by pditommaso** [comment] 2024-01-22 08:18
Pip is a mess, big -1

**Comment by marcodelapierre** [comment] 2024-01-22 08:27
Fair enough! 

@ewels  any specific big shout from the user community towards supporting `pip`? Or for now are we good simply with the newly documented Pypi package installation via Conda?

**Closed** 2024-01-25 08:45 UTC
