### ISSUE TITLE
ANSI logging swallows print statements

### ISSUE THREAD

**Issue by grst** [nextflow-io/nextflow#1818] opened 2020-12-02 16:49 UTC
## Bug report 

When I include a println statement for debugging, but an error occurs afterwards, 
it (sometimes) gets swallowed by the ANSI logging feature. It is always written to `.nextflow.log` 
and it is always printed if ANSI logging is disabled. 

### Expected behavior and actual behavior

Expected: always display debug statements, such as `println`. 

Actual: it is not printed, or rather printed and overwritten. 

### Steps to reproduce the problem

Minimal nextflow example: 

```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

process test {

    exec:
    println "Hello"
    doesnotexist 
}

workflow { 
    test()
}
```

### Program output 
```console
N E X T F L O W  ~  version 20.10.0
Launching `./test.nf` [cheesy_bohr] - revision: 43c551a5cd
[-        ] process > test -
executor >  local (1)
[31/45f383] process > test [100%] 1 of 1, failed: 1 ✘
Error executing process > 'test'

Caused by:
  Unknown variable 'doesnotexist' -- Make sure it is not misspelt and defined somewhere in the script before using it

Source block:
  println "Hello"
  doesnotexist

Work dir:
  /home/sturm/Downloads/nf/logging/work/31/45f3835c1bf120187f41c6432c4b14

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

### Environment 

* Nextflow version: 20.10.0
* Java version: openjdk version "11.0.8-internal" 2020-07-14
* Operating system: Linux
* Bash version: 5.0.18

**Comment by pditommaso** [comment] 2020-12-07 20:11
Duplicate of #1621

**Closed by pditommaso** 2020-12-07 20:11 UTC
