### ISSUE TITLE
Using  s3 path as publishDir is really slow

### ISSUE THREAD

**Issue by sivkovic** [nextflow-io/nextflow#1174] opened 2019-06-07 20:20 UTC
### Expected behavior and actual behavior

Using s3 path as a `publishDir` is extremely slow. For example the whole processing of 200 TN pairs with our pipeline lasted for 12 hours and publishing is completed 36 hours after that. 
### Steps to reproduce the problem

It is reproducible by using s3 bucket as `publishDir`.

### Program output 

Output which `nextflow` produce is expected.

### Environment 

* Nextflow version: 19.04.1 
* Java version: 1.8
* Operating system: macOS, Linux

### Additional context

I am aware that this technically is not a bug, but I haven't figured out why it is so slow, and I'm interested is there a way to improve this.

**Comment by pditommaso** [comment] 2019-06-08 16:34
Is the transfer happening across S3 buckets or from an S3 bucket and local storage?

**Comment by sivkovic** [comment] 2019-06-09 15:00
Across S3 buckets.

**Comment by pditommaso** [comment] 2019-06-10 08:09
I think it's a duplicate of #856, then. This a weird problem. In principle, it should be being a transfer managed remotely by the S3 backend and therefore fast. Any suggestion/fix it is welcome.

**Comment by pditommaso** [comment] 2019-06-10 08:09
Closing in favour of #856.

**Closed by pditommaso** 2019-06-10 08:09 UTC
Labels: storage/aws-s3
