### ISSUE TITLE
Need more consistency when dealing with list of input

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#251] opened 2016-11-23 10:50 UTC
```groovy
A = Channel.from( [[file('a1'), file('a2')]], [[file('b1'), file('b2')]])

process testInputA {
    input: file(x) from A

    output: stdout resultA

    """
    echo $x
    """
}
resultA.subscribe { println "A: $it" }
```
Returns:
```
A: input.1
A: input.1
```
expected output:
```
A: a1 a2
A: b1 b2
```

```groovy
B = Channel.from( [[file('a1'), file('a2')]], [[file('b1'), file('b2')]])

process testInputB {
    input: set file(x) from B

    output: stdout resultB

    """
    echo $x
    """
}
resultB.subscribe { println "B: $it" }
```
Returns what is expected:
```
B: a1 a2
B: b1 b2
```

```groovy
C = Channel.from( [[file('a1'), file('a2')]], [[file('b1'), file('b2')]])

process testInputC {
    input: set x from C

    output: stdout resultC

    """
    echo $x
    """
}
resultC.subscribe { println "C: $it" }
```
Returns:
```
C: [/path/a1, /path/a2]
C: [/path/b1, /path/b2]
```
The expected output should be:
```
C: /path/a1 /path/a2
C: /path/b1 /path/b2
```

```groovy
D = Channel.from( [[file('a1'), file('a2')]], [[file('b1'), file('b2')]])

process testInputD {
    input: val(x) from D

    output: stdout resultD

    """
    echo $x
    """
}
resultD.subscribe { println "D: $it" }
```
Returns:
```
D: [[/path/b1, /path/b2]]
D: [[/path/a1, /path/a2]]
```
The expected output should be:
```
D: /path/b1 /path/b2
D: /path/a1 /path/a2
```

```groovy
E = Channel.from( [[file('a1'), file('a2')]], [[file('b1'), file('b2')]])

process testInputE {
    input: val(x) from E

    output: stdout resultE

    """
    echo $x
    """
}
resultE.subscribe { println "E: $it" }
```
Returns:
```
E: [[/path/b1, /path/b2]]
E: [[/path/a1, /path/a2]]
```
The expected output should be:
```
E: /path/b1 /path/b2
E: /path/a1 /path/a2
```

```groovy
F = Channel.from( [[file('a1'), file('a2')]])

process testInputF {
    input: file(x) from F

    output: stdout resultF

    """
    echo $x
    """
}
resultF.subscribe { println "F: $it" }
```
Returns what is expected:
```
F: a1 a2 
```

```groovy
G = Channel.from( [[file('a1'), file('a2')]])

process testInputG {
    input: set file(x) from G

    output: stdout resultG

    """
    echo $x
    """
}
resultG.subscribe { println "G: $it" }
```
Returns:
```
G: a1
```
The expected output should be:
```
G: a1 a2
```

```groovy
H = Channel.from( [[file('a1'), file('a2')]])

process testInputH {
    input: set x from H

    output: stdout resultH

    """
    echo $x
    """
}
resultH.subscribe { println "H: $it" }
```
Returns:
```
H: /path/a1
```
The expected output should be:
```
H: /path/a1 /path/a2
```

```groovy
I = Channel.from( [[file('a1'), file('a2')]])

process testInputI {
    input: val(x) from I

    output: stdout resultI

    """
    echo $x
    """
}
resultI.subscribe { println "I: $it" }
```
Returns:
```
I: [/path/a1, /path/a2]
```
The expected output should be:
```
I: /path/a1 /path/a2
```

```groovy
J = Channel.from( [[file('a1'), file('a2')]])

process testInputJ {
    input: set val(x) from J

    output: stdout resultJ

    """
    echo $x
    """
}
resultJ.subscribe { println "J: $it" }
```
Returns:
```
J: /path/a1
```
The expected output should be:
```
J: /path/a1 /path/a2
```

**Comment by pditommaso** [comment] 2016-11-23 12:49
The problem is the input structure is not the one expected. Replacing 

```
A = Channel.from( [[file('a1'), file('a2')]], [[file('b1'), file('b2')]])
```

with

```
A = Channel.from( [file('a1'), file('a2')], [file('b1'), file('b2')])
```

It works. Is there any reason why you are using two nested lists?

**Comment by MaxUlysse** [comment] 2016-11-23 13:09
It does indeed explain the consistency between A-E and F-J, I made a quick copy paste when trying and didn't pay attention to that, and the first example works, but, why does:
```groovy
B = Channel.from( [[file('a1'), file('a2')], [file('b1'), file('b2')]])

process testInputB {
    input: set file(x) from B

    output: stdout resultB

    """
    echo $x
    """
}
resultB.subscribe { println "B: $it" }
```
Returns:
```
B: a1
B: b1
```
when the expected output:
```
B: a1 a2
B: b1 b2
```
I guess the answer will explain also why I get the same kind of results with:
```groovy
C = Channel.from( [[file('a1'), file('a2')], [file('b1'), file('b2')]])

process testInputC {
    input: set x from C

    output: stdout resultC

    """
    echo $x
    """
}
resultC.subscribe { println "C: $it" }
```
wich returns:
```
C: /path/a1
C: /path/b1
```
and:
```groovy
E = Channel.from( [[file('a1'), file('a2')], [file('b1'), file('b2')]])

process testInputE {
    input: set val(x) from E

    output: stdout resultE

    """
    echo $x
    """
}
resultE.subscribe { println "E: $it" }
```
which returns:
```
E: /path/a1 /path/a2
E: /path/b1 /path/b2
```
```
But why  when I do that:
```groovy
D = Channel.from( [[file('a1'), file('a2')], [file('b1'), file('b2')]])

process testInputD {
    input: val(x) from D

    output: stdout resultD

    """
    echo $x
    """
}
resultD.subscribe { println "D: $it" }
```
I receive that:
```
D: [/path/b1, /path/b2]
D: [/path/a1, /path/a2]
```
when my expected output should be:
```
D: /path/b1 /path/b2
D: /path/a1 /path/a2
```

**Comment by pditommaso** [comment] 2016-11-23 18:27
Test B & C you are right, the result it's not right. It should be the same issue as #216. However the problem is `set` are supposed to be used at least with two elements, thus in a future release this won't be supported. 

Test E, I'm unable to replicate it. It's supposed to be same problem as B & C. 

Test D is fine, `x` get a value that is a list of paths.

**Comment by MaxUlysse** [comment] 2016-11-24 08:42
My bad, for E, I made a bad copy paste, again...
What I get is:
```
E: /path/a1
E: /path/b1
```
and I expect something like
```
E: /path/a1 /path/a2
E: /path/b1 /path/b2
```

But it's similar to the other cases with set.

My last question that I don't understand, is why when dealing with a list of file, it returns files separated by spaces:
```
file1 file2 file3
```
But when it's a list of value, it returns a list of value in bracket separated by commas:
```
[/path/file1, /path/file2, /path/file3]
```

**Comment by pditommaso** [comment] 2016-11-24 09:37
> My last question that I don't understand, is why when dealing with a list of file, it returns files separated by spaces

That's by design to make easier to use many file names in a BAHS snippet. For example: 

   cat $list_of_files

Will expand to:

   cat file1 file2 file3

**Comment by MaxUlysse** [comment] 2016-11-24 09:50
I understand the concept, but what not applying that to a list of value too ?
`echo $list_of_values` expands to `echo [value1, value2, value3]`
It should be also:
`echo $list_of_values` expands to `echo value1 value2 value3`

Both $list_of_values and $list_of_files are list, they should behave the same way, no ?

**Comment by pditommaso** [comment] 2016-11-24 10:04
The main reason is that to render the list of files without quotes and brackets requires a non-trivial hack that limits the ability to manipulate that object as list object, therefore I choose to not modify the semantic for plain list values.

**Comment by MaxUlysse** [comment] 2016-11-24 10:20
I know, I made an horrible bash hack to remove brackets and comma, and then notice that it was not behaving the same way when it was specified as file...
What I'm doing now, is:
```
#!/usr/bin/env nextflow

D = Channel.from( [[file('a1'), file('a2')], [file('b1'), file('b2')]])

process testInputD {
    input: val(x) from D

    output: stdout resultD

    script:
	values = x.collect{"$it"}.join(' ')
    """
    echo $values
    """
}
resultD.subscribe { println "D: $it" }
```
and I got what I really want:
```
D: /path/a1 /path/a2
D: /path/b1 /path/b2
```

**Comment by pditommaso** [comment] 2016-12-05 09:03
Since the latest release `0.22.6` a warning message is displayed when an input/output `set` defines only one component. This syntax will not be supported any more in a future release.

**Comment by MaxUlysse** [comment] 2016-12-05 09:04
OK,
Thanks a lot for your help

**Closed by pditommaso** 2016-12-05 09:03 UTC
