### ISSUE TITLE
slurm_load_jobs error: Socket timed out on send/recv operation

### ISSUE THREAD

**Issue by StevenWingett** [nextflow-io/nextflow#2696] opened 2022-03-04 10:17 UTC
## Bug report 
I have encountered a problem while running the rnaseq pipeline in nf-core.  After talking on Slack with Paolo Di Tommaso and Phil Ewells, they suggested this issue was most likely a Nextflow problem and that I should report the issue here rather then on nf-core (https://nextflow.slack.com/archives/C02T98A23U7/p1646310005987449 ).

### Expected behavior and actual behavior
I was trying to run the nf-core/rnaseq (v3.5) pipeline.  It mainly runs fine, except it seems to randomly fail.  I've displayed the error message later on in this bug report.

### Steps to reproduce the problem
As I mentioned above, this problem is sporadic and random in nature and so hard to reproduce.  Furthermore, if I keep trying -resume multiple times then the pipeline will eventually complete.

I suspected this is something to do with the slurm scheduler being overwhelmed.  So, I set submitRateLimit = '1sec' to try to prevent this happening.  This did not resolve the issue.

### Program output 

```
Mar-03 02:29:07.519 [Task monitor] WARN  n.executor.AbstractGridExecutor - [SLURM] queue status cannot be fetched
- cmd executed: squeue --noheader -o %i %t -t all -u swingett
- exit status : 1
- output      :
  slurm_load_jobs error: Socket timed out on send/recv operation
```

I've also attached one of the log files (there were many generated, since the pipeline was resumed multiple times.)

[nextflow_log_retry.log.zip](https://github.com/nextflow-io/nextflow/files/8184929/nextflow_log_retry.log.zip)

### Environment 
Nextflow v21.10.6 (build 5660)
Scientific Linux 7.9 (Nitrogen)
slurm 21.08.0
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
nf-core/rnaseq (v3.5)

### Additional context
Also,  I noticed that the command in the error report does not work on my system if I enter it in the command line:

```
[swingett@hex paired_end]$ squeue --noheader -o %i %t -t all -u swingett
squeue: error: Unrecognized option: %t
```

Perhaps importantly, if I edit that command and add quotes, then the option is recognised:

```
[swingett@hex paired_end]$ squeue --noheader -o "%i %t" -t all -u swingett
480145 PD
480144 R
```

Sorry if I have missed something obvious as I am quite new to Nextflow.  Please do let me know if you require further details.

Many thanks,
Steven

**Comment by pditommaso** [comment] 2022-03-13 19:14
This issue seems caused by the Slurm cluster returning an unexpected error message when submitting the job(s) execution. 

I've added a retry policy to try handling this error condition. This will included in uploading Nextflow release

**Comment by StevenWingett** [comment] 2022-03-16 10:05
Hi,

Thanks very much for looking into this for us.  I'll try the new version once it is released and hopefully it will solve the issue.  These apparently "random" problems are hard to resolve and our computing team have not been able to identify a fault from the slurm cluster.  If all goes well we can start rolling out these pipeline across our institute.

Many thanks once again.

All the best,
Steven

**Comment by pditommaso** [comment] 2022-04-23 18:33
This has been released as of versions `22.03.0-edge` and `22.04.0`

**Closed by pditommaso** 2022-04-23 18:33 UTC
Labels: platform/slurm

**Comment by StevenWingett** [comment] 2022-04-25 08:33
Hi,

Thanks for letting me know.  Pleasingly, I have not seen this problem again since upgrading Nextflow.  It seems as though this has fixed the issue.

Many thanks,

Steven

**Comment by pditommaso** [comment] 2022-04-25 09:20
Nice to hear !
