### ISSUE TITLE
withName not working when process is included

### ISSUE THREAD

**Issue by sawibo** [nextflow-io/nextflow#1271] opened 2019-08-09 10:53 UTC
## Bug report 
When including a process (e.g. include X from X.nf) the withName selector in the nextflow.config file does not seem to be able to find the process.

### Expected behavior and actual behavior
Expected:
process specific config is loaded from nextflow.config

Actual :
WARN: There's no process matching config selector: X

### Steps to reproduce the problem
#main.nf
include X from X.nf

#nextflow.config
process {
 withName : X {
  cpus 12
 }
}
#X.nf
process X {
 random process
}

### Program output 
WARN: There's no process matching config selector: X

### Environment 

* Nextflow version: 19.07.0 build 5106
* Java version: 1.8.0_60
* Operating system: Linux

### Additional context
Running with nextflow.preview.dsl=2

**Comment by pditommaso** [comment] 2019-08-09 13:19
I think this is a duplicate of #1175.

**Comment by sawibo** [comment] 2019-08-09 13:19
I just noticed, thanks!

**Comment by pditommaso** [comment] 2019-08-10 13:20
75b96aa

**Closed by pditommaso** 2019-08-10 13:20 UTC
Labels: lang/dsl2
