### ISSUE TITLE
K8s local executor and file permissions in `bin` folder

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#693] opened 2018-05-10 20:30 UTC
Hi Paolo, I also noticed that `get_software_versions` process always fails:
```
ubuntu@k8s-master:~/kubespray$ NXF_VER=0.30.0-SNAPSHOT ./nextflow kuberun wikiselev/rnaseq --genome GRCh37 --reads '/mnt/gluster/data/*_{1,2}.fastq.gz' -v testpvc:/mnt/gluster
Pod started: zen-lichterman
N E X T F L O W  ~  version 0.30.0-SNAPSHOT
Pulling wikiselev/rnaseq ...
 downloaded from https://github.com/wikiselev/rnaseq.git
Launching `wikiselev/rnaseq` [zen-lichterman] - revision: 6d44261a24 [master]
===================================
 nfcore/rnaseq  ~  version 1.5dev
===================================
Run Name       : zen-lichterman
Reads          : /mnt/gluster/data/*_{1,2}.fastq.gz
Data Type      : Paired-End
Genome         : GRCh37
Strandedness   : None
Trim R1        : 0
Trim R2        : 0
Trim 3' R1     : 0
Trim 3' R2     : 0
Aligner        : STAR
STAR Index     : s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/STARIndex/
GTF Annotation : s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf
BED Annotation : s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.bed
Save Reference : No
Save Trimmed   : No
Save Intermeds : No
Max Memory     : 80 GB
Max CPUs       : 7
Max Time       : 10d
Output dir     : ./results
Working dir    : /mnt/gluster/ubuntu/work
Container      : nfcore/rnaseq:latest
Pipeline Release: master
Current home   : /root
Current path   : /mnt/gluster/ubuntu
R libraries    : false
Script dir     : /mnt/gluster/projects/wikiselev/rnaseq
Config Profile : standard
=========================================
[warm up] executor > k8s
[warm up] executor > local
[6c/5e819d] Submitted process > workflow_summary_mqc
[c2/35c537] Submitted process > fastqc (22028_2#118)
[8e/a0ac9f] Submitted process > trim_galore (22028_2#11)
[cf/db0c82] Submitted process > fastqc (22028_2#111)
[b5/816b74] Submitted process > get_software_versions
[00/4e1040] Submitted process > fastqc (22028_2#11)
[b3/d7eb41] Submitted process > trim_galore (22028_2#118)
[a1/013023] Submitted process > trim_galore (22028_2#111)
[b5/816b74] NOTE: Process `get_software_versions` terminated with an error exit status (127) -- Error is ignored
```

Here is the `.command.sh` from this process:
```
#!/bin/bash -euo pipefail
echo 1.5dev &> v_ngi_rnaseq.txt
echo 0.30.0-SNAPSHOT &> v_nextflow.txt
fastqc --version &> v_fastqc.txt
cutadapt --version &> v_cutadapt.txt
trim_galore --version &> v_trim_galore.txt
STAR --version &> v_star.txt
hisat2 --version &> v_hisat2.txt
stringtie --version &> v_stringtie.txt
preseq &> v_preseq.txt
read_duplication.py --version &> v_rseqc.txt
featureCounts -v &> v_featurecounts.txt
picard MarkDuplicates --version &> v_markduplicates.txt  || true
samtools --version &> v_samtools.txt
multiqc --version &> v_multiqc.txt
scrape_software_versions.py &> software_versions_mqc.yaml
```
Here is the folder content of the process:
```
ubuntu@vlad-k8s-test-k8s-master-nf-1:/mnt/gluster/pvc-319c8c17-3ca6-11e8-89b1-fa163e31bb09$ l -la ubuntu/work/b5/816b745fb2ac7bf91ab85486eb41c6/
total 18
drwxr-xr-x 2 root root 4096 May 10 17:16 ./
drwxr-xr-x 3 root root 4096 May 10 17:16 ../
-rw-r--r-- 1 root root    0 May 10 17:16 .command.begin
-rw-r--r-- 1 root root  131 May 10 17:16 .command.err
-rw-r--r-- 1 root root  131 May 10 17:16 .command.log
-rw-r--r-- 1 root root    0 May 10 17:16 .command.out
-rw-r--r-- 1 root root 1843 May 10 17:16 .command.run
-rw-r--r-- 1 root root  614 May 10 17:16 .command.sh
-rw-r--r-- 1 root root 2654 May 10 17:16 .command.stub
-rw-r--r-- 1 root root    3 May 10 17:16 .command.trace
-rw-r--r-- 1 root root    3 May 10 17:16 .exitcode
-rw-r--r-- 1 root root  106 May 10 17:16 v_fastqc.txt
-rw-r--r-- 1 root root   16 May 10 17:16 v_nextflow.txt
-rw-r--r-- 1 root root    7 May 10 17:16 v_ngi_rnaseq.txt
```
So, it fails on `fastqc` step. If I look in the `v_fastqc.txt` file:
```
/mnt/gluster/ubuntu/work/b5/816b745fb2ac7bf91ab85486eb41c6/.command.sh: line 4: fastqc: command not found
```
which means that somehow it is run outside of the pipeline docker image. So, then I looked at the config file and found this:
```
  $get_software_versions {
    memory = { check_max( 2.GB, 'memory' ) }
    cache = false
    executor = 'local'
    errorStrategy = 'ignore'
  }
```
I then removed `executor = 'local'` and got the error 126 instead of 127:
```
ubuntu@k8s-master:~/kubespray$ NXF_VER=0.30.0-SNAPSHOT ./nextflow kuberun wikiselev/rnaseq --genome GRCh37 --reads '/mnt/gluster/data/*_{1,2}.fastq.gz' -v testpvc:/mnt/gluster
Pod started: lonely-curran
N E X T F L O W  ~  version 0.30.0-SNAPSHOT
Pulling wikiselev/rnaseq ...
 downloaded from https://github.com/wikiselev/rnaseq.git
Launching `wikiselev/rnaseq` [lonely-curran] - revision: eaebf588e8 [master]
===================================
 nfcore/rnaseq  ~  version 1.5dev
===================================
Run Name       : lonely-curran
Reads          : /mnt/gluster/data/*_{1,2}.fastq.gz
Data Type      : Paired-End
Genome         : GRCh37
Strandedness   : None
Trim R1        : 0
Trim R2        : 0
Trim 3' R1     : 0
Trim 3' R2     : 0
Aligner        : STAR
STAR Index     : s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/STARIndex/
GTF Annotation : s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf
BED Annotation : s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.bed
Save Reference : No
Save Trimmed   : No
Save Intermeds : No
Max Memory     : 60 GB
Max CPUs       : 7
Max Time       : 10d
Output dir     : ./results
Working dir    : /mnt/gluster/ubuntu/work
Container      : nfcore/rnaseq:latest
Pipeline Release: master
Current home   : /root
Current path   : /mnt/gluster/ubuntu
R libraries    : false
Script dir     : /mnt/gluster/projects/wikiselev/rnaseq
Config Profile : standard
=========================================
[warm up] executor > k8s
WARN: Process 'workflow_summary_mqc' cannot be executed by 'k8s' executor -- Using 'local' executor instead
[warm up] executor > local
[a1/ddde43] Submitted process > trim_galore (22028_2#11)
[7f/6c3f17] Submitted process > workflow_summary_mqc
[09/05ba27] Submitted process > fastqc (22028_2#118)
[23/ce76b6] Submitted process > trim_galore (22028_2#111)
[9c/3813d0] Submitted process > fastqc (22028_2#11)
[54/a1d871] Submitted process > fastqc (22028_2#111)
[e3/0849ab] Submitted process > trim_galore (22028_2#118)
[ad/11b155] Submitted process > get_software_versions
[ad/11b155] NOTE: Process `get_software_versions` terminated with an error exit status (126) -- Error is ignored
```

The error appeared at the last line of the `.command.sh`, which is `scrape_software_versions.py &> software_versions_mqc.yaml`. The error message was the following:
```
/mnt/gluster/ubuntu/work/ad/11b1552f96bf47e208440291c5da01/.command.sh: line 16: /mnt/gluster/projects/wikiselev/rnaseq/bin/scrape_software_versions.py: Permission denied
```
So, this looks like right permissions of files in the `bin` folder are not passed to the pods? So, in conclusion:

* local executors with Docker containers do not work on K8s (I am not sure why Phil used local here...)
* something is not right with file permissions in the `bin` folder

**Comment by wikiselev** [comment] 2018-05-10 20:35
Also, though I removed `executor = 'local'` from both `get_software_versions` and `workflow_summary_mqc`, however `workflow_summary_mqc` complained (see above NF messages):
```
WARN: Process 'workflow_summary_mqc' cannot be executed by 'k8s' executor -- Using 'local' executor instead
```
Not sure why this is happening...

**Comment by pditommaso** [comment] 2018-05-11 07:58
The [workflow_summary_mqc](https://github.com/wikiselev/rnaseq/blob/master/main.nf#L1036-L1054) is not a shell process, it just create a file therefore it can only run locally (actually it could be replaced by a few lines of groovy). 

The problem is raised by `get_software_versions`. IMO It should run like any other process (not locally) and likely the python script `scrape_software_versions.py ` has been committed w/o execute permission. Maybe @ewels or @apeltzer can help here.

**Comment by pditommaso** [comment] 2018-05-24 17:18
Because, for example, the docker/singularity may not be available in the (local) node where NF is running (generally) the head node. When using Kubernetes, nextflow runs in its own container, therefore that process will fail. To summary it may break the application portability.

**Comment by ewels** [comment] 2018-05-28 15:35
Gotcha 👍  Ok cool, will try to avoid using `local` for specific processes from now on. https://github.com/nf-core/cookiecutter/issues/30

**Comment by pditommaso** [comment] 2018-05-29 15:12
This sounds solved 👍

**Closed** 2018-05-29 15:15 UTC
Labels: triage/needs-information
