### ISSUE TITLE
Nested params defined in config are not overridden at command line

### ISSUE THREAD

**Issue by mjhipp** [nextflow-io/nextflow#1923] opened 2021-02-23 20:07 UTC
## Bug report 

Nested params can be assigned at the command line, but they do not overwrite the params defined in config or script file.  

### Expected behavior and actual behavior

Expected behavior: a nested param (`params.nested.foo`) that is defined in `nextflow.config` can be overridden at the command line.

Actual behavior: nested param is not overridden. 

### Steps to reproduce the problem

Using these files:

test.config:
```
params.foo = 'foo'
params.nested.foo = 'nestedfoo'
```

test.nf:
```
nextflow.enable.dsl=2

params.baz = 'baz'
params.nested.baz = 'nestedbaz'

workflow {
  log.info """\
  
  These are defined in test.config and overriden at command line:
  params.foo        : $params.foo
  params.nested.foo : $params.nested.foo

  These are not defined anywhere, and given at command line:
  params.bar        : $params.bar
  params.nested.bar : $params.nested.bar
  
  These are defined in test.nf and overridden at command line:
  params.baz        : $params.baz
  params.nested.baz : $params.nested.baz
  """
}
```

Run command:

```
NXF_VER="21.02.0-edge" ./nextflow -C test.config run test.nf --foo changed --nested.foo changed --bar assigned --nested.bar assigned --baz changed --nested.baz changed
```

### Program output 

```
N E X T F L O W  ~  version 21.02.0-edge
Launching `test.nf` [tiny_lichterman] - revision: c5d820028f

  These are defined in test.config and overriden at command line:
  params.foo        : changed
  params.nested.foo : nestedfoo

  These are not defined anywhere, and given at command line:
  params.bar        : assigned
  params.nested.bar : assigned

  These are defined in test.nf and overridden at command line:
  params.baz        : changed
  params.nested.baz : nestedbaz


```

I would expect `params.nested.foo` and `params.nested.baz` to be "changed", as set in command line.

### Environment 

* Nextflow version: 21.02.0-edge 
* Java version: openjdk version "1.8.0_232"
* Operating system: macOS
* Bash version: zsh 5.8 (x86_64-apple-darwin20.0)

### Additional context

When using the latest release (20.10.0), the nested params are not able to be assigned at all from command line:

```
❯ NXF_VER="20.10.0" ./nextflow -C test.config run test.nf --foo changed --nested.foo changed --bar assigned --nested.bar assigned --baz changed --nested.baz changed
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [pensive_hamilton] - revision: c5d820028f
These are defined in test.config and overriden at command line:
  params.foo        : changed
  params.nested.foo : nestedfoo

  These are not defined anywhere, and given at command line:
  params.bar        : assigned
  params.nested.bar : null

  These are defined in test.nf and overridden at command line:
  params.baz        : changed
  params.nested.baz : nestedbaz
```

I can still override them using `-c`, except nested params that are defined in the script:

test-override.conf:
```
params.foo = soft-override
params.nested.foo = soft-override
params.bar = soft-override
params.nested.bar = soft-override
params.baz = soft-override
params.nested.baz = soft-override
```

If I change `test.config` to `nextflow.config` and pass in the `-c` file, it overrides all but the nested param defined in the script:

```
❯ NXF_VER="21.02.0-edge" ./nextflow -c test-override.conf run test.nf
N E X T F L O W  ~  version 21.02.0-edge
Launching `test.nf` [zen_elion] - revision: c5d820028f

  These are defined in test.config and overriden at command line:
  params.foo        : soft-override
  params.nested.foo : soft-override

  These are not defined anywhere, and given at command line:
  params.bar        : soft-override
  params.nested.bar : soft-override

  These are defined in test.nf and overridden at command line:
  params.baz        : soft-override
  params.nested.baz : nestedbaz

```

**Comment by pditommaso** [comment] 2021-02-23 21:10
Likely duplicate of https://github.com/nextflow-io/nextflow/issues/1856

**Comment by mjhipp** [comment] 2021-02-23 21:42
This is occurring after the fix for #1856. If I run the files from #1856 I get the expected/fixed output:

```
❯ ./nextflow run 1856.nf --test.foo foo_over
N E X T F L O W  ~  version 21.02.0-edge
Launching `1856.nf` [deadly_kalam] - revision: b4ba18d4c7
  test.foo: foo_over
  test.bar:  bar_def
```

**Comment by mjhipp** [comment] 2021-02-23 22:05
The config from #1856:

```
params {
  test {
    foo = "foo_def"
    bar = "bar_def"
  }
}
```
If I run this config file, I get the expected/fixed results (https://github.com/nextflow-io/nextflow/issues/1923#issuecomment-784532919).


However, if I rewrite that config file, with the same information but different format:

```
params.test.foo = "foo_def"
params.test.bar = "bar_def"
```

And then try to run the same command, it does not overwrite:

```
❯ ./nextflow -C 1856.config run 1856.nf --test.foo foo_over
N E X T F L O W  ~  version 21.02.0-edge
Launching `1856.nf` [marvelous_pauling] - revision: d0e5d37cae
  test.foo: foo_def
  test.bar: bar_def
```

**Comment by mjhipp** [comment] 2021-02-25 03:21
## Nested params in different scopes overwrite each other

From the above, it would seem the solution would be to only define nested params using the curly brackets notation, as that allows overriding. However, there are also issues with that. 

When defining nested params in the curly brackets notation, a nested param in a different scope will overwrite ones found before. 

### Example 1

Here, `nested.foo.bar` overwrites `foo.bar`:


test1.config:                  
```nextflow
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
}
```

```
❯ nextflow -C test1.config config`
params {
   foo {
      bar = 'bar2'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
}
```

### Example 2

Here, `nested2.foo.bar` overwrites `nested.foo.bar` and `foo.bar`

test2.config:
```nextflow                    
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
  bar = 'bar3'
  nested2 {
    baz = 'baz3'
    foo {
      bar = 'bar4'
    }
  }
}
```
```
❯ nextflow -C test2.config config
params {
   foo {
      bar = 'bar4'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar4'
      }
   }
   bar = 'bar3'
   nested2 {
      baz = 'baz3'
      foo {
         bar = 'bar4'
      }
   }
}
```

### Example 3

If I list the shallowest scope last, there is no overriding:

test3.config:
```nextflow
params {
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
  bar = 'bar3'
  nested2 {
    baz = 'baz3'
    foo {
      bar = 'bar4'
    }
  }
  foo {
    bar = 'bar1'
  }
}
```
```
❯ nextflow -C test3.config config
params {
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
   bar = 'bar3'
   nested2 {
      baz = 'baz3'
      foo {
         bar = 'bar4'
      }
   }
   foo {
      bar = 'bar1'
   }
}
```

### Example 4

If I use dot-notation, there is also no overwriting:

test4.config (equal information as test1.config, different format):
```nextflow
params.foo.bar = 'bar1'
params.baz = 'baz1'
params.nested.baz = 'baz2'
params.nested.foo.bar = 'bar2'
```
```
❯ nextflow -C test4.config config
params {
   foo {
      bar = 'bar1'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
}
```

However, If I use dot notation, I cannot override params at command line (as top comment):

printparams.nf:
```nextflow
nextflow.enable.dsl=2

log.info "$params"
```

Using either `test1.config` or `test4.config`, and `--foo.bar bar3` option, I would expect this output:

```
[foo:[bar:bar3], baz:baz1, nested:[baz:baz2, foo:[bar:bar2]]]
```

However, when using `test4.config` (dot notation), it does not override anything:

```
❯ nextflow -C test4.config run printparams.nf --foo.bar bar3
N E X T F L O W  ~  version 21.02.0-edge
Launching `printparams.nf` [nauseous_tuckerman] - revision: f06db69bf6
[foo:[bar:bar1], baz:baz1, nested:[baz:baz2, foo:[bar:bar2]]]
```

And when using `test1.config` (curly braces) it overrides both `foo.bar` and `nested.foo.bar`:

```
❯ nextflow -C test2.config run printparams.nf --foo.bar bar3
N E X T F L O W  ~  version 21.02.0-edge
Launching `printparams.nf` [hungry_venter] - revision: f06db69bf6
[foo:[bar:bar3], baz:baz1, nested:[baz:baz2, foo:[bar:bar3]]]
```

**Comment by pditommaso** [comment] 2021-03-21 15:48
I've spotted the bug reported as the main issue report. For the problem is the last comment you may want to open a separate ticket.

**Closed by pditommaso** 2021-03-21 15:48 UTC

**Comment by mjhipp** [comment] 2021-03-22 23:21
Thank you! I added #1982

**Comment by mes5k** [comment] 2021-04-02 21:22
@pditommaso  I'm not sure this fix is complete.  Running with a docker image built from the `master` branch today, I get the exception seen in this [log file](https://github.com/nextflow-io/nextflow/files/6251276/problem.nextflow.log).  This is the 
[config file](https://github.com/nextflow-io/nextflow/files/6251275/problem.nextflow.config.txt) that seemed to generate the problem.   It traces back to `deepClone` function added to Bolts for this fix.

This config file works fine with 21.03.0-edge.

**Comment by pditommaso** [comment] 2021-04-03 10:28
I'm not able to replicate, but it's strange but it chose the deepClone for `Serializable`, instead of the one for `Map`. 

Can you try to get rid of the first and see if it solves? 

https://github.com/nextflow-io/nextflow/blob/cfe6b1d192baa51b5814b68602477944fd5b8d/modules/nf-commons/src/main/nextflow/extension/Bolts.groovy#L915-L935

**Comment by pditommaso** [comment] 2021-04-03 21:12
Posted a patch

**Comment by mes5k** [comment] 2021-04-03 21:27
Confirmed!  Works beautifully.  Thanks for the quick turnaround!
