### ISSUE TITLE
Unable to download the genome via fromSRA method 

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#1699] opened 2020-08-06 17:59 UTC
## Bug report 

Hello everyone, 

I am trying to download the genomes from NCBI using the accension ID - ERR776668 and I've run into the following error

```
Illegal character in authority at index 6: ftp://err776668      ftp.sra.ebi.ac.uk
```

### Expected behavior and actual behavior

Nextflow should stage the files and download them.

### Steps to reproduce the problem

```nextflow
/*
================================
params
================================
*/

params.resultsDir = 'results/rawGenomes'
// we can obtain this key from the NCBI portal
params.apiKey = "FIXME"

/*
================================
ids of genomes to be downloaded
================================
*/

ids = [
'ERR776668'
]
  

/*
================================
only for publishing these files to results folder
================================
*/


process downloadRawGenomes {

    input:
    set genomeName, file(genomeReads) from Channel.fromSRA(ids, cache: true, apiKey: params.apiKey)

    errorStrategy 'ignore'

    script:
    
    """
    mkdir -p ../../../$params.resultsDir
    mv \$(readlink -f ${genomeReads[0]}) ../../../$params.resultsDir/
    mv \$(readlink -f ${genomeReads[1]}) ../../../$params.resultsDir/

    """


}
```

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)
```
Aug-06 17:47:18.920 [main] DEBUG nextflow.cli.Launcher - $> nextflow run test.nf
Aug-06 17:47:19.052 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.07.1
Aug-06 17:47:19.068 [main] INFO  nextflow.cli.CmdRun - Launching `test.nf` [nauseous_noyce] - revision: da53b1993b
Aug-06 17:47:19.231 [main] DEBUG nextflow.Session - Session uuid: 81f2e8ed-e303-4a4d-9394-ff23e534a9c1
Aug-06 17:47:19.231 [main] DEBUG nextflow.Session - Run name: nauseous_noyce
Aug-06 17:47:19.234 [main] DEBUG nextflow.Session - Executor pool size: 8
Aug-06 17:47:19.301 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 20.07.1 build 5412
  Created: 24-07-2020 15:18 UTC (15:18 GMT)
  System: Linux 5.3.0-1026-gcp
  Runtime: Groovy 2.5.11 on OpenJDK 64-Bit Server VM 11.0.1-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)
  Process: 6226@compute-ide-upg-master-abhinav-3444 [10.140.0.16]
  CPUs: 8 - Mem: 29.4 GB (27.4 GB) - Swap: 0 (0)
Aug-06 17:47:19.336 [main] DEBUG nextflow.Session - Work-dir: /mnt/disks/user/abhinav/high_tb_burden_countries/work [ext2/ext3]
Aug-06 17:47:19.336 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /mnt/disks/user/abhinav/high_tb_burden_countries/bin
Aug-06 17:47:19.384 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Aug-06 17:47:19.386 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Aug-06 17:47:19.532 [main] DEBUG nextflow.Session - Session start invoked
Aug-06 17:47:20.018 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Aug-06 17:47:20.029 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: downloadRawGenomes
Aug-06 17:47:20.150 [ForkJoinPool.commonPool-worker-3] DEBUG nextflow.datasource.SraExplorer - SRA search url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&usehistory=y&retmode=json&api_key=ed38c182ff2cdca964f0c766e220c02ec608&term=ERR776668
Aug-06 17:47:20.198 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Aug-06 17:47:20.199 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Aug-06 17:47:20.206 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Aug-06 17:47:20.215 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=29.4 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Aug-06 17:47:20.392 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Aug-06 17:47:20.392 [main] DEBUG nextflow.Session - Session await
Aug-06 17:47:21.397 [ForkJoinPool.commonPool-worker-3] DEBUG nextflow.datasource.SraExplorer - SRA data request url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=sra&retmode=json&query_key=1&WebEnv=NCID_1_37910302_130.14.18.48_9001_1596736041_1767006815_0MetA0_S_MegaStore&retstart=0&retmax=1000&api_key=ed38c182ff2cdca964f0c766e220c02ec608
Aug-06 17:47:21.702 [ForkJoinPool.commonPool-worker-3] ERROR nextflow.Channel - Illegal character in authority at index 6: ftp://err776668      ftp.sra.ebi.ac.uk
java.net.URISyntaxException: Illegal character in authority at index 6: ftp://err776668 ftp.sra.ebi.ac.uk
        at java.base/java.net.URI$Parser.fail(URI.java:2915)
        at java.base/java.net.URI$Parser.parseAuthority(URI.java:3249)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3160)
        at java.base/java.net.URI$Parser.parse(URI.java:3116)
        at java.base/java.net.URI.<init>(URI.java:600)
        at nextflow.file.http.XFileSystemProvider.key(XFileSystemProvider.groovy:62)
        at nextflow.file.http.XFileSystemProvider.key(XFileSystemProvider.groovy:66)
        at nextflow.file.http.XFileSystemProvider.getFileSystem(XFileSystemProvider.groovy:123)
        at nextflow.file.http.XFileSystemProvider.getPath(XFileSystemProvider.groovy:138)
        at java.base/java.nio.file.Path.of(Path.java:208)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at nextflow.file.FileHelper.asPath(FileHelper.groovy:278)
        at nextflow.file.FileHelper.asPath(FileHelper.groovy:261)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:131)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at nextflow.datasource.SraExplorer.getFastqUrl(SraExplorer.groovy:281)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at nextflow.datasource.SraExplorer.parseDataResponse(SraExplorer.groovy:200)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at nextflow.datasource.SraExplorer.query1(SraExplorer.groovy:157)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at nextflow.datasource.SraExplorer.query0(SraExplorer.groovy:141)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at nextflow.datasource.SraExplorer.query0(SraExplorer.groovy:135)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at nextflow.datasource.SraExplorer.apply(SraExplorer.groovy:103)
        at nextflow.Channel$_fetchSraFiles0_closure16.doCall(Channel.groovy:608)
        at nextflow.Channel$_fetchSraFiles0_closure16.call(Channel.groovy)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Aug-06 17:47:21.713 [ForkJoinPool.commonPool-worker-3] DEBUG nextflow.Session - Session aborted -- Cause: Illegal character in authority at index 6: ftp://err776668    ftp.sra.ebi.ac.uk
Aug-06 17:47:21.748 [ForkJoinPool.commonPool-worker-3] DEBUG nextflow.Session - The following nodes are still active:
[process] downloadRawGenomes
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

Aug-06 17:47:21.750 [main] DEBUG nextflow.Session - Session await > all process finished
Aug-06 17:47:21.750 [main] DEBUG nextflow.Session - Session await > all barriers passed
Aug-06 17:47:21.757 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Aug-06 17:47:21.927 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Aug-06 17:47:21.932 [main] DEBUG nextflow.util.SpuriousDeps - AWS S3 uploader shutdown
Aug-06 17:47:21.949 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

Output of `nextflow info`

```
  Version: 20.07.1 build 5412
  Created: 24-07-2020 15:18 UTC (15:18 GMT)
  System: Linux 5.3.0-1026-gcp
  Runtime: Groovy 2.5.11 on OpenJDK 64-Bit Server VM 11.0.1-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)
```

**Comment by pditommaso** [comment] 2020-08-06 19:49
Duplicate of #1700

**Closed by pditommaso** 2020-08-06 19:49 UTC

**Comment by abhi18av** [comment] 2020-08-07 02:29
Oh, okay 👍
