### ISSUE TITLE
Trouble accessing AWS s3 bucket files with {}

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#511] opened 2017-11-08 10:02 UTC
Hi, 
I'm experimenting with AWS, `using nextflow cloud create` and then connecting to the 

I have files specified as:
- `s3://<bucketname>/<path>/bar1.foo`
- `s3://<bucketname>/<path>/bar2.{foo1,foo2,foo3}`

I have no problem accessing `s3://<bucketname>/<path>/bar1.foo` as `file("s3://<bucketname>/<path>/bar1.foo")` gives me `/<path>/bar1.foo`
But `file("s3://<bucketname>/<path>/bar2.{foo1,foo2,foo3}")` gives me the following error: `ERROR ~ The bucket name parameter must be specified when listing objects in a bucket`

**Comment by fstrozzi** [comment] 2017-11-08 11:25
Hi @MaxUlysse I've opened an issue for this problem a couple of days ago (see https://github.com/nextflow-io/nextflow/issues/509), apparently a fix for this was already provided and it is included in the new upcoming NF release.

**Comment by MaxUlysse** [comment] 2017-11-08 11:45
Oh, sorry, I didn't saw it.
Thanks for mentioning it.
Cheers

**Comment by pditommaso** [comment] 2017-11-08 12:28
duplicate of #509

**Closed by pditommaso** 2017-11-08 12:28 UTC
