### ISSUE TITLE
Is it possible to develop workflows in Java instead of Groovy?

### ISSUE THREAD

**Issue by chhh** [nextflow-io/nextflow#2779] opened 2022-04-07 21:01 UTC
I find it difficult to develop complex scripts because I don't understand the anatomy and rules of scripts completely (due to Groovy's weird syntax and lack of tooling).

Is there any way to develop workflows in Java directly instead? With strong typing, help from IDEs etc.
I don't mind if that's a complicated process, just want to know if that's possible at all.

Thank you!

**Comment by pditommaso** [comment] 2022-04-07 21:03
Duplicate of #2778

**Closed by pditommaso** 2022-04-07 21:03 UTC
