### ISSUE TITLE
Support colon in project names for GCP

### ISSUE THREAD

**Issue by danielecook** [nextflow-io/nextflow#3353] opened 2022-11-05 14:41 UTC
## Bug report 

For historical reasons, it is possible for a colon to appear in a GCP project name. When I run Nextflow with Google Batch I observe the following error:

```
Error executing process > 'sayHello (2)'

Caused by:
  io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unparseable filter: syntax error at line 1, column 58, token ':';
syntax error at line 1, column 59, token '#####/logs/batch_task_logs'
```

Note that this behavior does not occur with the other google executor (life-sciences)

Full traceback:

Note I have redacted the project name and replaced it with `#####`

```

Caused by:
  io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unparseable filter: syntax error at line 1, column 58, token ':';
syntax error at line 1, column 59, token '#####/logs/batch_task_logs'

com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unparseable filter: syntax error at line 1, column 58, token ':';
syntax error at line 1, column 59, token '#####/logs/batch_task_logs'
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:208)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:202)
	at com.google.api.core.ApiFutures$ApiFunctionToGuavaFunction.apply(ApiFutures.java:239)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:234)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:222)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:200)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:94)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:76)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:572)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:468)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:432)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:465)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unparseable filter: syntax error at line 1, column 58, token ':';
syntax error at line 1, column 59, token '#####/logs/batch_task_logs'
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:98)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	... 25 common frames omitted
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unparseable filter: syntax error at line 1, column 58, token ':';
syntax error at line 1, column 59, token '#####/logs/batch_task_logs'
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 17 common frames omitted
```

### Expected behavior and actual behavior

NF Should properly parse project names containing colon values when running Google Batch

### Steps to reproduce the problem

It will be difficult to reproduce - but if the function responsible can be identified from the traceback, then ensuring that can parse colon-containing project names should help.

### Program output 

```
└──╼ nextflow run https://github.com/nextflow-io/hello -profile google
N E X T F L O W  ~  version 22.10.1
Launching `https://github.com/nextflow-io/hello` [admiring_lamarr] DSL2 - revision: 4eab81bd42 [master]
Nov 04, 2022 8:54:51 PM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
executor >  google-batch (4)
executor >  google-batch (4)
[5e/7e37d7] process > sayHello (1) [  0%] 0 of 1
Error executing process > 'sayHello (2)'

Caused by:
  io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unparseable filter: syntax error at line 1, column 58, token ':';
syntax error at line 1, column 59, token '#####/logs/batch_task_logs'
```

### Environment 

* Nextflow version: 22.10.1
* Java version: 11.0.9.1
* Operating system: Linux
* Bash version: GNU bash, version 5.2.1

**Comment by pditommaso** [comment] 2022-11-07 17:18
It looks like this is an error returned by the Google API. Not sure how much we can do about it. I guess trying to remove the comma will break the project reference.

**Comment by danielecook** [comment] 2022-11-10 05:42
I am able to submit jobs to google batch using the python API framework which I assume operates similarly.

**Comment by pditommaso** [comment] 2022-11-10 07:57
Likely, because I think the error is coming from the Cloud logging API client, not the Batch client.

**Comment by danielecook** [comment] 2022-11-10 14:04
Ah I see! I will investigate further. Thanks.

**Comment by aaronegolden** [comment] 2022-12-02 21:25
This is caused by the filter defined here:

https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-google/src/main/nextflow/cloud/google/batch/logging/BatchLogging.groovy#L66

That log reading code is specific to the batch-executor and that's why it's not happening with the life-sciences executor. The exception comes from the Cloud Logging API rather than the Batch API (as Paolo suggested) so that's why you're still able to submit batch jobs to those projects.

Quoting the logName ought to fix this, according to the docs here:

https://cloud.google.com/logging/docs/view/logging-query-language

String values must be double-quoted to escape (among other things) the :(colon) character. Here's a small PR to add the quotes: https://github.com/nextflow-io/nextflow/pull/3464

**Comment by pditommaso** [comment] 2022-12-03 07:31
Merged, thanks

**Closed by pditommaso** 2022-12-03 07:31 UTC
Labels: platform/google-batch
