### ISSUE TITLE
Race condition running multiple processes on file input.

### ISSUE THREAD

**Issue by yesimon** [nextflow-io/nextflow#41] opened 2015-05-01 04:55 UTC
I'm running an nf file with multiple processes that use `storeDir` and file inputs. Exception is non-deterministic and only occurs with over 5+ proc declarations.

race.nf:
```
#!/usr/bin/env nextflow
seqs = file('seqs/*.fastq')

process proc1 {
  storeDir 'results'

  input:
  file fastq from seqs

  output:
  set val(baseName), file(outName) into proc1

  script:
  baseName = fastq.baseName
  outName = baseName + '.proc1'
  """
  echo "blarg" > $outName
  """
}

process proc2 {
  storeDir 'results'

  input:
  file fastq from seqs

  output:
  set val(baseName), file(outName) into proc2

  script:
  baseName = fastq.baseName
  outName = baseName + '.proc2'
  """
  echo "blarg" > $outName
  """
}

... repeat as necessary
```

output:
```
N E X T F L O W  ~  version 0.13.3
Launching race.nf
[warm up] executor > local
[skipping] Stored process > proc2 (3)
[skipping] Stored process > proc3 (1)
[skipping] Stored process > proc3 (3)
[skipping] Stored process > proc2 (2)
[skipping] Stored process > proc2 (1)
[skipping] Stored process > proc1 (2)
[skipping] Stored process > proc5 (1)
[skipping] Stored process > proc5 (2)
[skipping] Stored process > proc5 (3)
[skipping] Stored process > proc1 (1)
[skipping] Stored process > proc1 (3)
[skipping] Stored process > proc3 (2)
[skipping] Stored process > proc4 (1)
[skipping] Stored process > proc4 (2)
[skipping] Stored process > proc4 (3)
ERROR ~ Error executing process > 'proc5 (1)'

Caused by:
  Cannot invoke method bindOutput() on null object


 -- Check '.nextflow.log' file for details
Uncaught exception occurred in gpars pool Actor Thread 14
java.util.concurrent.RejectedExecutionException: Task groovyx.gpars.actor.AbstractLoopingActor$1@2766ae7b rejected from java.util.concurrent.ThreadPoolExecutor@ad4cdb3[Shutting down, pool size =
 1, active threads = 1, queued tasks = 0, completed tasks = 49]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at groovyx.gpars.scheduler.DefaultPool.execute(DefaultPool.java:155)
        at groovyx.gpars.util.AsyncMessagingCore.store(AsyncMessagingCore.java:99)
        at groovyx.gpars.actor.AbstractLoopingActor.send(AbstractLoopingActor.java:241)
        at groovyx.gpars.dataflow.operator.DataflowProcessorActor.send(DataflowProcessorActor.java:85)
        at groovyx.gpars.actor.AbstractLoopingActor.send(AbstractLoopingActor.java:241)                                                                                                   [0/1821]
        at groovyx.gpars.dataflow.operator.DataflowProcessorActor.send(DataflowProcessorActor.java:85)
        at groovyx.gpars.actor.AbstractLoopingActor.terminate(AbstractLoopingActor.java:215)
        at groovyx.gpars.dataflow.operator.DataflowProcessor.terminate(DataflowProcessor.java:147)
        at nextflow.Session.abort(Session.groovy:375)
        at nextflow.Session$abort$7.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at nextflow.processor.TaskProcessor.resumeOrDie(TaskProcessor.groovy:756)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
        at nextflow.processor.TaskProcessor.handleException(TaskProcessor.groovy:694)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:80)
        at nextflow.processor.ParallelTaskProcessor.this$dist$invoke$2(ParallelTaskProcessor.groovy)
        at nextflow.processor.ParallelTaskProcessor$TaskProcessorInterceptor.methodMissing(ParallelTaskProcessor.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:932)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1255)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1208)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
        at nextflow.processor.ParallelTaskProcessor$TaskProcessorInterceptor.onException(ParallelTaskProcessor.groovy:296)
        at groovyx.gpars.dataflow.operator.DataflowProcessor.fireOnException(DataflowProcessor.java:331)
        at groovyx.gpars.dataflow.operator.DataflowProcessor.reportError(DataflowProcessor.java:293)
        at groovyx.gpars.dataflow.operator.DataflowProcessorActor.reportException(DataflowProcessorActor.java:125)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:122)
        at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
        at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by pditommaso** [comment] 2015-05-01 05:01
Could you please include the `.nextflow.log` file ?

**Comment by yesimon** [comment] 2015-05-01 05:08
Since it's a bit long:

https://gist.github.com/yesimon/cf59053d90ee3ea6c700

**Comment by yesimon** [comment] 2015-05-01 05:13
Running the same nf file on my 2-core Macbook Air just hangs on:

```
[51/22abf6] Submitted process > proc1 (2)
[be/46a6ea] Submitted process > proc1 (1)
[9b/e35ed2] Submitted process > proc2 (1)
```

Which after SIGINT leads to this .nextflow.log (looks like different bug).

https://gist.github.com/yesimon/6fd574e972c496b5ad40

**Comment by pditommaso** [comment] 2015-05-01 05:16
Could you please include the full script you are using to replicate the error. Thanks!

**Comment by yesimon** [comment] 2015-05-01 05:18
Full script:
https://gist.github.com/yesimon/6ed53585b4c0f9d87342

**Comment by pditommaso** [comment] 2015-05-01 05:23
Can I ask you to test if the version `0.13.4-SNAPSHOT` is affected by the same problem. You only to set the variable: 

    export NXF_VER=0.13.4-SNAPSHOT 

And launch it again.

**Comment by yesimon** [comment] 2015-05-01 05:32
Fixes the problem for MBA. However the original problem is still similar. I updated the gist.

https://gist.github.com/yesimon/cf59053d90ee3ea6c700

**Comment by yesimon** [comment] 2015-05-01 05:46
This might be because the machine has more cores than available to the user. It shows 16 but fewer cores for each user. Is it possible to specify number of threads in threadpool via command line?

**Comment by pditommaso** [comment] 2015-05-01 06:12
I've managed to replicate the second problem you are reporting and I can confirm that is a regression introduced in version 0.13.x. 

Regarding the first one, I'm unable to replicate it, but I'm supposing that you have effectively spotted out a race condition. May I ask you to test the snapshot that I have just uploaded? In order to use it you will need to force nextflow to redownload the 0.13.4-SNAPSHOT: 

    export NXF_VER=0.13.4-SNAPSHOT
    CAPSULE_RESET=1 nextflow info   

Thanks. 

(the number of thread can be se in the `nextflow.config` file adding the entry `poolSize = n`)

**Comment by yesimon** [comment] 2015-05-01 15:20
Still similar results, even with poolSize = 1.

https://gist.github.com/yesimon/cf59053d90ee3ea6c700

**Comment by pditommaso** [comment] 2015-05-01 15:55
There's something strange because the build number does match with the of the patch. I've just uploaded one more time. Could you gently try it one more time, following these steps:  

    export NXF_VER=0.13.4-SNAPSHOT
    CAPSULE_RESET=1 nextflow info

It should download the new jargs printing the following output: 

    CAPSULE: Downloading dependency io.nextflow:nextflow:pom:0.13.4-20150501.154723-7
    CAPSULE: Downloading dependency io.nextflow:nxf-commons:pom:0.13.4-20150501.154747-7
    CAPSULE: Downloading dependency io.nextflow:nxf-extrae:pom:0.13.4-20150501.154828-7
    CAPSULE: Downloading dependency io.nextflow:nextflow:jar:0.13.4-20150501.154723-7
    CAPSULE: Downloading dependency io.nextflow:nxf-commons:jar:0.13.4-20150501.154747-7
    CAPSULE: Downloading dependency io.nextflow:nxf-extrae:jar:0.13.4-20150501.154828-7
      Version: 0.13.4-SNAPSHOT build 2966
      Modified: 01-05-2015 15:47 UTC (17:47 CEST)
      System: Mac OS X 10.9.5
      Runtime: Groovy 2.3.11 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-b25
      Encoding: UTF-8 (UTF-8)


Then you can try to run it again the race test. 

Thanks a lot.

**Comment by yesimon** [comment] 2015-05-01 16:03
The bug doesn't occur anymore, but now nextflow randomly hangs after finishing all processes. It always hangs with `poolSize = 1`, but sometimes hangs with higher `poolSize`.

https://gist.github.com/yesimon/cf59053d90ee3ea6c700

**Comment by pditommaso** [comment] 2015-05-01 16:12
Could you please share the log file for an execution that hung?

Tx

**Comment by yesimon** [comment] 2015-05-02 16:32
An example of hanging after finishing all processes, after which I cancelled with SIGINT.
```
N E X T F L O W  ~  version 0.13.4-SNAPSHOT
Launching race.nf
[warm up] executor > local
[skipping] Stored process > proc4 (1)
[skipping] Stored process > proc3 (1)
[skipping] Stored process > proc1 (1)
[skipping] Stored process > proc3 (2)
[skipping] Stored process > proc2 (1)
[skipping] Stored process > proc5 (1)
[skipping] Stored process > proc4 (2)
[skipping] Stored process > proc1 (2)
[skipping] Stored process > proc3 (3)
[skipping] Stored process > proc4 (3)
[skipping] Stored process > proc1 (3)
[skipping] Stored process > proc5 (2)
[skipping] Stored process > proc5 (3)
[skipping] Stored process > proc2 (2)
[skipping] Stored process > proc2 (3)
[skipping] Stored process > proc6 (1)
[skipping] Stored process > proc7 (1)
[skipping] Stored process > proc7 (2)
[skipping] Stored process > proc7 (3)
[skipping] Stored process > proc6 (2)
[skipping] Stored process > proc6 (3)
```

.nextflow.log
https://gist.github.com/yesimon/cf59053d90ee3ea6c700

**Comment by pditommaso** [comment] 2015-05-02 17:22
I'm closing this since the issue in the subject has been fixed. I've opened #43 for the last problem you are reporting.

**Closed** 2015-05-02 17:22 UTC
Labels: bug
