### ISSUE TITLE
Resource limits with K8S

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#773] opened 2018-06-27 11:50 UTC
The way resource limits are set with the K8S executor has some problems.
It looks like this needs to be set using the cpu directive in process definition. e.g.
```
process my_process {
    cpus 2

    ...
}
```
The problems I encountered are:

Problem 1: specifying the value '1' did not result in anything being created in the pod definition. Maybe 1 is considered a default and handled as a special case, but this is not correct for K8S as a CPU limit of 1 is meaningful and different from there being no limit.

Problem 2: The K8S spec handles this value as a string, allowing values like '100m' (meaning 100 milli-cpus, or 0.1 cpus). NF does not seem to allow specifying this as a text value (presumably this might cause problems with other executors). Specifying a fractional value (e.g. 0.5) seems to be silently ignored.

Problem 3: The 'cpu' value gets incorporated into the pod definition as a resource limit e.g. as
```
resources:
      limits: {cpu: 2}
```
K8S also has a limit for `request`s and probably that is more appropriate that a `limit`, but it might be best if both could be specified independently.

Problem 4: if specifying a CPU limit you can easily get into the situation that NF tries to start a number of pods but not all of them can be scheduled as there are no more CPUs available. When this happens NF throws an error and the pipeline fails. This is a complex topic and should probably be handled as a separate issue, but at the least I think the pod's `restartPolicy` should be set to `OnFailure` rather than `Never`, but how NF handles errors from process could complicate this.

**Comment by pditommaso** [comment] 2018-06-28 21:42
Many things: 

Problem 1) I think you are right, by default is a process uses 1 cpus, therefore it should be reflect in the resources specification otherwise a pod can consume all available cpus. 

Problem 2) this could be managed in the `cpus` directive but then how the actual command/tool would use that value? I mean the `cpus` is reflected in the `task.cpus` property that is generally used in the command script to set the number of threads/cpus that a multithread program should use. See [for example here](https://github.com/nextflow-io/rnaseq-nf/blob/master/main.nf#L88). Would not make sense to provide there a decimal value. 

Problem 3) This has been done on purpose. When `requests` is omitted it is implicitly equals to the `limits` value. Therefore k8s *guarantees* such resources. I think this makes sense for computational jobs.

Problem 4) Yes, maybe this should be managed as separate issue.

**Comment by tdudgeon** [comment] 2018-06-29 08:40
Problem 1). So can this be corrected so that a value of '1' does get included?

Problem 2). Yes, understand why this is handled as an integer, but in cases like K8S we need something different. That's why it would be useful to have full control over the pod specification.

Problem 3). Yes, but having the limit equal to the request is not always ideal. My best guess (not been able to test this) is that for single threaded tasks (I have lots of these) you might want a request of 0.9 cpu (so that you can run as many tasks as you have cores, allowing for a small amount of utilisation by 'book keeping' pods) and a limit of 1.2cpu (to make sure that the pod doesn't get evicted if it's usage goes up to 1.0 which it theoretically should). Again would be useful to have full control over the pod specification to allows this.

Problem 4). Agreed. But let's discuss first.

**Comment by pditommaso** [comment] 2018-07-02 12:09
> Problem 1). So can this be corrected so that a value of '1' does get included?

Yes
 
> Problem 2). Yes, understand why this is handled as an integer, but in cases like K8S we need something different.

It could be extended to handle a string value, but still I don't see how it can be used that value by a tool. Do you have an example? 

> Problem 3). Yes, but having the limit equal to the request is not always ideal.  [etc]

I see your point. It would make sense to extend the `memory` definition to handle this case. I will open a separate issue for that. 

 > Problem 4). Agreed. But let's discuss first.

ok

**Comment by pditommaso** [comment] 2018-07-03 07:23
But my point is that NF expose that value in the task command to set the number of cpus/core for a multithread application, for example: 

```
bwa mem --threads $task.cpus .. 
```

It would make no sense for such tools to use a fractional number of cpus.

**Comment by pditommaso** [comment] 2018-07-18 12:15
Problem 1 has been addressed by a separate issue #806. I will this open for Problem 2.

**Comment by pditommaso** [comment] 2019-04-22 16:39
Reminder to myself about K8s pod resources work. Pods can be of one of 3 different classes: *Guaranteed*, *Burstable*, and *Best-Effort*, in decreasing order of priority.

A pod is assigned to one of the above classes depending on the resources `requests` and `limits` pod attributes: 
* when `requests` == `limits` (or only `limits` is specified), then the pod is classified as *Guaranteed*; Note 
* when `requests` < `limits` (or only `requests` is specified), then the pod is classified as *Burstable*;
* when both `requests` and `limits` are omitted then the pod is classified as *Best-Effort*. 

Read more [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md) and [here](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container).

**Comment by alanbchristie** [comment] 2020-04-15 11:46
Specifying only a limit alone is not enough for _ Guaranteed_. To obtain a _Guaranteed_ allocation **Every Container in the Pod must have a CPU limit and a CPU request, and they must be the same.** (https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#qos-classes)

**Comment by pditommaso** [comment] 2020-10-12 15:03
keep open

**Comment by zeehio** [comment] 2021-04-15 14:03
Trying to provide my 2cts.

One thing is the fraction of CPU time that should be assigned to a particular process. This fraction is usually normalized to the number of cores available. So on an 8 core system you can ask for 4 cores, for 2.5 cores or for 0.5 cores for instance, but it does not make sense to ask for 8.5 cores. The OS through the CPU scheduler assigns the corresponding fraction of time to the process.

Another thing is how many threads/processes a program should use to perform a computation. Usually it can be set to the fraction of CPU time described above -rounded down when it is larger than 1, rounded up if it is less than 1- `num_processes = max(1, floor(cpu_fraction))`.

The problem is that until this issue, nextflow could safely use the same value for both concepts. As I see it `task.cpus` could be deprecated and split into `task.cpu_fraction` (as the `[float] fraction of CPU time, normalized to the number of cores available`) and `task.num_processes` (as the `[int] number of processes or threads to be used by a task`). `num_processes` could be computed from  `cpu_fraction` as described above.

Related to this, we could bring into the topic simultaneous multithreading (hyperthreading) and with it whether the `cpu_fraction` should be normalized to physical cores or logical cores (usually it's logical cores). If that's the case, some tasks might benefit from having `num_processes` halved if hyperthreading is enabled, because hyperthreading is actually not helping much.

**Comment by marcadella** [comment] 2021-05-05 12:15
Looks like k8s resource limits doesn't work at all on 21.04: #2088

**Comment by courcelm** [comment] 2021-11-17 15:54
It would be useful to be able to set request and limit individually. When limit is set I get CPU throttling which slow my process. I will be useful to be able to remove limit.

**Comment by bentsherman** [comment] 2024-04-30 22:13
After some discussion, we decided we aren't going to implement request/limit for CPUs or the fractional CPUs, because we believe there are other ways to handle this use case:

- Nextflow no longer sets the cpu limit in K8s so that pods can burst CPU usage if they need it and it's available. I believe this is why you saw better performance when setting cpus to 0.9-1.1 instead of 1

- Instead of allowing fractional CPUs, it is more efficient to batch many tasks into a single job, which creates less scheduler overhead. #3909 will add a `batch` directive for this purpose

**Closed by bentsherman** 2024-04-30 22:13 UTC
Labels: executor/k8s, pinned
