### ISSUE TITLE
conda environment not detected

### ISSUE THREAD

**Issue by MarcElosua** [nextflow-io/nextflow#4614] opened 2023-12-22 18:18 UTC
Hi everyone, I am new to nextflow and I'm running into an error using nextflow with a conda environment that I have no idea how to solve...
I have this process in my [test.nf](http://test.nf/) file
```groovy
// Declare syntax version
nextflow.enable.dsl=2

process processSampleSheet { 
    executor 'local' // No need to launch a job for this step
    
    storeDir params.main_dir + "/outputs"
    
    // output gemid csv file to channel
    output:
    path "sample-sheet-gemid.csv"
    
    script:
    """
	#!/usr/bin/env python3
	
	import secrets
	import string
	import pandas as pd

	# Function to generate random 8-character alphanumeric string
	def generate_random_string():
		alphabet = string.ascii_letters + string.digits
		return ''.join(secrets.choice(alphabet) for _ in range(8))

	print("${params.sampleSheetPath}")
	# Read and subset sample sheet
	meta = pd.read_csv("${params.sampleSheetPath}")

	# Add a unique gem_id for each sample
	meta['gem_id'] = meta.apply(lambda x: generate_random_string(), axis=1)

	# Write dataframe to csv
	meta.to_csv("sample-sheet-gemid.csv", header = True, index = False)
    """
}
```

and the nextflow.config file looks like:

```groovy
// GLOBAL PARAMETERS
params.main_dir = '/temp_work/'
params.sampleSheetPath = params.main_dir + '/sample_sheet_test.csv'  // Your sample sheet file
params.fastqPath = params.main_dir + '/fastq_sub'  // Your sample sheet file
params.cellrangerPath = '/programs/x86_64-linux/cellranger/7.1.0/' // need to be in interactive node -> srun --pty /bin/bash
params.expect_cells = 10000
params.reference = '/reference_databases/ReferenceGenome/10xGenomics/refdata-gex-GRCh38-2020-A'
params.slurm_template = params.main_dir + '/scripts/slurm.template'

// Remove work and cacher and .nextflow files at the end of the process
cleanup = true

// SLURM parameters
// https://www.nextflow.io/docs/latest/config.html?highlight=queuesize
executor {
    name = 'slurm'
    queueSize = 250
    pollInterval = '15 sec'
}

// Path to the conda environment
conda.enabled = true
process.conda = '/home/melosua/miniconda3/envs/cellranger'
```

And I get this error

```
N E X T F L O W  ~  version 23.04.1
Launching `test.nf` [spontaneous_booth] DSL2 - revision: 597ea8dcd4
executor >  local (1)
executor >  local (1)
[92/7bcc8b] process > processSampleSheet     [100%] 1 of 1, failed: 1 ✘
[-        ] process > processFastq           -
[-        ] process > processFastQC          -
[-        ] process > processMultiQC         -
[-        ] process > processCellrangerCount -
ERROR ~ Error executing process > 'processSampleSheet'

Caused by:
  Process `processSampleSheet` terminated with an error exit status (1)

Command executed:

  #!/usr/bin/env python3
  
  import secrets
  import string
  import pandas as pd
  
  # Function to generate random 8-character alphanumeric string
  def generate_random_string():
  	alphabet = string.ascii_letters + string.digits
  	return ''.join(secrets.choice(alphabet) for _ in range(8))
  
  print("/temp_work/melosua/project/sample_sheet_test.csv")
  # Read and subset sample sheet
  meta = pd.read_csv("/temp_work/melosua/project/sample_sheet_test.csv")
  
  # Add a unique gem_id for each sample
  meta['gem_id'] = meta.apply(lambda x: generate_random_string(), axis=1)
  
  # Write dataframe to csv
  meta.to_csv("sample-sheet-gemid.csv", header = True, index = False)

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.run: line 126: /usr/bin/activate: No such file or directory

Work dir:
  /temp_work/melosua/project/work/92/7bcc8bf468d6575875f5ecb261d246

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

The .command.log file only has this error
```
cat /temp_work/melosua/project/work/92/7bcc8bf468d6575875f5ecb261d246/.command.log 
.command.run: line 126: /usr/bin/activate: No such file or directory
```

Line 126 in .command.run is
```bash
source $(conda info --json | awk '/conda_prefix/ { gsub(/"|,/, "", $2); print $2 }')/bin/activate /home/melosua/miniconda3/envs/cellranger
```

So it seems like it is having an issue calling conda from the process.conda but have no idea how to fix it, any help would be greatly appreciated!!! Thank youuu

**Comment by bentsherman** [comment] 2024-01-03 16:35
Closing as duplicate of #4610

**Closed by bentsherman** 2024-01-03 16:35 UTC
Labels: software/conda
