### ISSUE TITLE
Ignite autoscale option

### ISSUE THREAD

**Issue by nephantes** [nextflow-io/nextflow#899] opened 2018-10-13 14:26 UTC
### Expected behavior and actual behavior

When I start a cluster using ignite with the parameters below it doesn't add new instances even some jobs wait in the queue more than 5 minutes. My expectation, when there are jobs require more memory and cpu than used ones, it should add new instances but  it doesn't. It is trying to run all of them. 

```
cloud { 
   userName = 'ubuntu'
   imageId =  '{MYAMI}'
   instanceType = 'r5.2xlarge'
   subnetId = '{MYSUBNETID}'
   sharedStorageId = '{MYSS}'
   sharedStorageMount = '/mnt/efs'
   keyFile = '{MYKEYFILE}'
   autoscale {
       enabled = true 
       terminateWhenIdle = true
       maxInstances = 4
   }
}
```

### Program output 
I copied all the reports below with .nextflow.log
https://galaxyweb.umassmed.edu/logs/timeline.html
https://galaxyweb.umassmed.edu/logs/report.html
https://galaxyweb.umassmed.edu/logs/.nextflow.log
https://galaxyweb.umassmed.edu/logs/nextflow.config

### Steps to reproduce the problem

If you start an instance with the configuration parameters above and run multiple copies of the application that takes more than five minutes and the total requested memory and cpu more than the machine has, my expectation is adding more machines since it has autoscale.
So, there were two programs; RSEM and STAR. We set the memory and cpu like below.

```
process.$RSEM.memory = '32 GB'
process.$RSEM.cpus = 4
process.$Map_STAR.memory = '32 GB'
process.$Map_STAR.cpus = 4
```

While running STAR we used "--runThreadN 4 " option and for RSEM "-p 4".

What are we missing? Is there any other configuration do we need to do to be able to use autoscale functionality of ignite. 
Thanks,
Alper

### Environment 

* Nextflow version: [version 0.31.1 build 4886] 
* Java version: [1.8.0_181]
* Operating system: [Ubuntu 16.04.5]

**Comment by pditommaso** [comment] 2018-10-15 07:43
Autoscaling only work when the cluster is provisioned using `nextflow cloud create` command, instead it looks you are managing it on your own.

**Comment by pditommaso** [comment] 2018-10-16 08:44
The problem is this ` -cluster.join path:/mnt/efs/.dolphinnext/profile1`. Autoscaling currently is only supported the default cloud-based joining mechanism.

**Comment by onuryukselen** [comment] 2018-10-16 17:44
Thanks Paolo,
We have removed -cluster.join and tried again. I copied all log files and reports below.
While starting the cluster we used the config file below;
https://galaxyweb.umassmed.edu/logs/test/nextflow.config
and the command is below;
nextflow cloud create cluster9

Here we set minInstances to 2, just to see, if it will start with 2 nodes or not. But it didn't.

We then started a run. Our expectation is seeing the second machine started after 5 minutes, if there are jobs waiting in the queue. In this case, three jobs started immediately and three jobs were waiting more then 10 minutes in the queue. You can see the timeline report below;
https://galaxyweb.umassmed.edu/logs/test/timeline.html
The .nextflow.log file;
https://galaxyweb.umassmed.edu/logs/test/.nextflow.log
The config file for this run;
https://galaxyweb.umassmed.edu/logs/test/nextflow-run.config
Reprot file;
https://galaxyweb.umassmed.edu/logs/test/report.html

So, autoscale is still not running. What else are we missing here?
Thanks

**Comment by pditommaso** [comment] 2018-10-16 17:48
You commit your AWS keys ... I strongly advice you to disable them **immediately**. I need some time to reviews the log.

**Comment by nephantes** [comment] 2018-10-16 18:23
Thanks for pointing it out. Removed!

**Comment by pditommaso** [comment] 2018-10-18 05:17
I'm not able to replicate the issue. In your log there should be `Auto-scaling enabled: true`, but I can't it, this means that the autoscale does not get activated. 

In the master node of the cluster create by NF there should be config file named: `$HOME/.nextflow/config`. What's the content?

**Comment by nephantes** [comment] 2018-10-18 16:33
On the machine we run "nextflow cloud create". They don't match with our prepared nextflow.config file. 
The content is below;

more ~/.nextflow/config 
cloud {
    imageId = '{MYAMI}'
    instanceType = 'm3.xlarge'
    subnetId = '{MYSUBNET}'
    userName = 'kucukura'
    keyFile = '~/.ssh/id_rsa.pub'
    sharedStorageId = '{MYVOL}'
    instanceStorageMount = '/share'
}

**Comment by nephantes** [comment] 2018-10-19 15:57
Thanks Paolo,
I have uploaded the contents of the files you asked below;

   https://galaxyweb.umassmed.edu/logs/cloud/boot.log
   https://galaxyweb.umassmed.edu/logs/cloud/cloud-init-output.log
   https://galaxyweb.umassmed.edu/logs/cloud/cloud-init.log

Let me know if you anything is missing here in the installation or configuration.
Thanks

**Comment by pditommaso** [comment] 2018-10-22 14:00
Yes, this looks fine. Does you still have the autoscaling issue? not it should work (always include also the .nextflow.log).

**Comment by nephantes** [comment] 2018-10-22 14:38
Yes, it is not working. It doesn’t support auto scale. Do you have a working Amazon image example with configuration parameters that you can share with me? If so, I can compare those images and see what is missing. Solving is going to be important for us since, we cannot use multiple machines with nextflow now.
Thanks

**Comment by nephantes** [comment] 2018-10-22 20:13
Hi Paolo,
Auto-scale is still not working. It is not about the Amazon image. I have used your amazon image file to recreate it. (I got this image ID from your documentation; ami-4b7daa32)

I used command below to create the cluster
    
      nextflow cloud create cluster14 

The config file in the master node is below;

https://galaxyweb.umassmed.edu/logs/test2/config

As you can see in the timeline, it supposed to add new nodes after 5 minutes. But it doesn't start it.
     
https://galaxyweb.umassmed.edu/logs/test2/timeline.html

The .nextflow.log file;

https://galaxyweb.umassmed.edu/logs/test2/.nextflow.log

The config file for this specific run;

https://galaxyweb.umassmed.edu/logs/test2/nextflow.config

Report file;

https://galaxyweb.umassmed.edu/logs/test2/report.html

Other log files you 

$HOME/boot.log:
https://galaxyweb.umassmed.edu/logs/test2/boot.log
/var/log/cloud-init.log:
https://galaxyweb.umassmed.edu/logs/test2/cloud-init.log
/var/log/cloud-init-output.log:
https://galaxyweb.umassmed.edu/logs/test2/cloud-init-output.log

Could you please let us know, what could be wrong? 
Thank you very much for your time.

Alper

**Comment by nephantes** [comment] 2018-10-24 04:19
Hi Paolo,
I found the reason why nextflow couldn't enable autoscale option.
I was running nextflow remotely with ssh command;

      ssh -t nephantes@ec2-35-153-39-189.compute-1.amazonaws.com 'nextflow /mnt/efs/alpertest/lstest2/run46/nextflow.nf -process.executor ignite  --inputparam \"/mnt/efs/test/fastqfiles/*.fastq\" --mate \"single\"    -with-report -with-trace -with-timeline"

And realized that nextflow add some environment variables so just before nextflow run command, I run 

    source ~/.bash_profile 

Now, nextflow enables Autoscale option and starts the machines on amazon. However, it doesn't add these new worker nodes to the cluster and therefore submitted jobs don't use these new nodes. Is there anything else I need to do to tell nextflow to add these worker nodes to the cluster?

nextflow logs here;
https://galaxyweb.umassmed.edu/logs/test3/.nextflow.log

Other logs are in this directory;
https://galaxyweb.umassmed.edu/logs/test3/

**Comment by pditommaso** [comment] 2018-10-24 15:31
I see. So now the questions is, does the autoscale work when ssh-ing in the node instead of running the command remotely ?

**Comment by nephantes** [comment] 2018-10-24 16:10
Hi Paolo,
I just wanted to share my experience for your records.

It is working perfectly when I run nextlow remotely with ssh **on your image** after I source ~/.bash_profile and /etc/profile.

The nextflow logs on the working version;
https://galaxyweb.umassmed.edu/logs/test4/.nextflow.log
All other logs about this run and environment;
https://galaxyweb.umassmed.edu/logs/test4/

Autoscale is enabled on my image but when I do exactly same run,  autoscale works and nextflow starts the machines however, it doesn't add these worker machines into the cluster (while yours add).    

So, what I observed about the differences in between images; It looks like cloud-init version is different and the version I have doesn't have cloud-init-cfg. Your cloud-init version is 0.7.6. My version on ubuntu image is 18.3-9-g2e62cb8a-0ubuntu1~16.04.2.

The nextflow log on my image (which it doesn't add the worker nodes to the cluster);
https://galaxyweb.umassmed.edu/logs/test3/.nextflow.log
All other logs;
https://galaxyweb.umassmed.edu/logs/test3/

I will start using your image for now, but if that's a general case for ubuntu on newer cloud-init versions, you might want to test. I just wanted share my observation. 

Thanks for all your help.

**Comment by nephantes** [comment] 2018-12-04 17:56
Sorry, forgot to message you. Yes, it is remote lunch. But fixed when I source the profiles.

**Comment by pditommaso** [comment] 2018-12-04 19:31
Ok, therefore I'm closing this. Tx

**Closed by pditommaso** 2018-12-04 19:31 UTC
