### ISSUE TITLE
trying to work with pairs of input files ... and failing

### ISSUE THREAD

**Issue by grendon** [nextflow-io/nextflow#641] opened 2018-03-22 22:16 UTC
The overall objective is to perform peak calling with MACS2 and with EPIC.
These tools need two files as input, one for the control sample and one for the treatment sample.

This is the snippet of the code that is failing

```
params.bams = "/long-path/Dedup-Filtered-Bams/*_{input,IP}.*.bam"

Channel

     .fromFilePairs(params.bams, flat: true)
     .set { macsChannel }

process MACS2 {
    tag                 { id }
    queue                runQueue
    memory               "10 GB"
    errorStrategy        'finish'
    module               macs2Mod,samtoolsMod
    publishDir           "${params.outdir}/macs2", mode: 'copy'

    input:
    set val(id), file(ctrl), file(trmt) from macsChannel

    output:
    file "*"

    script:
    dirname = ${id}
    """
    macs2 callpeak \\
	-t ${ctrl} \\
	-c ${trmt} \\
	${params.broad} \\
	-f BAM \\
	-g ${params.genomeSize} \\
	-n $id  \\
	--outdir $dirname \\
	-q 0.01 --bw ${params.macs2bandwidth} -s ${params.macs2tagsize} --bdg \\
	--verbose 3  ${dirname}.macs2.log
    """

}
```

And these are the last few lines of the nextflow.log file

```
Mar-22 16:59:48.275 [main] DEBUG nextflow.Session - Session await
Mar-22 16:59:48.317 [Actor Thread 7] ERROR nextflow.processor.TaskProcessor - Error executing process > 'MACS2 (HP_C2_763_C1)'

Caused by:
  No signature of method: _nf_script_e06e7860.$() is applicable for argument types: (_nf_script_e06e7860$_run_closure5$_closure15$_closure16) values: [_nf_script_e06e7860$_run_closure5$_closure15$_closure16@505f4113]
Possible solutions: is(java.lang.Object), run(), run(), any(), any(groovy.lang.Closure), use([Ljava.lang.Object;)

Source block:
     dirname = ${id}
     """
     macs2 callpeak \\
  -t ${ctrl} \\
  -c ${trmt} \\
  ${params.broad} \\
  -f BAM \\
  -g ${params.genomeSize} \\
  -n $id  \\
  --outdir $dirname \\
  -q 0.01 --bw ${params.macs2bandwidth} -s ${params.macs2tagsize} --bdg \\
  --verbose 3 > ${dirname}.macs2.log
     """

Tip: you can try to figure out what's wrong by changing to the process work dirand showing the script file named `.command.sh`
Mar-22 16:59:48.322 [Actor Thread 7] INFO  nextflow.Session - Execution cancelled -- Finishing pending tasks before exit
Mar-22 16:59:48.327 [main] DEBUG nextflow.Session - Session await > all process finished
Mar-22 16:59:48.427 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Mar-22 16:59:53.327 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: slurm)
Mar-22 16:59:53.328 [main] DEBUG nextflow.Session - Session await > all barriers passed
Mar-22 16:59:53.358 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms]
Mar-22 16:59:53.358 [main] DEBUG nextflow.trace.TraceFileObserver - Flow completing -- flushing trace file
Mar-22 16:59:53.384 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Mar-22 16:59:53.400 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

**Comment by pditommaso** [comment] 2018-03-23 09:16
I guess the problem is: 

```
 script:
    dirname = ${id}
```

That's wrong, you only need `$` or `${ }` to interpolate variables in a string.

**Comment by grendon** [comment] 2018-03-23 16:43
Yes. That  was the problem. I removed the line and the pipeline is running. BUT!
It is running in a weird way; submitting jobs sequentially rather than concurrently
even though the cluster has enough idle nodes to run those processes simultaneously. 
It is simply weird!

This is a snippet of the last few lines of the nextflow.log that is still running

>Mar-23 10:29:17.545 [main] DEBUG nextflow.Session - Session await
>Mar-23 10:29:17.739 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
>Mar-23 10:29:17.757 [Task submitter] INFO  nextflow.Session - [6b/898519] Submit ted process > MACS2 (Amy_C2_763_C1)
>Mar-23 10:34:17.636 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 4; name: MACS2 (Amy_C2_763_C1); status: RUNNING; exit: -; err or: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/ batch1-part2-only/work/6b/89851958ed451b0577ffd601aa02da]
>Mar-23 10:34:22.008 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 10:39:17.713 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 4; name: MACS2 (Amy_C2_763_C1); status: RUNNING; exit: -; err or: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/ batch1-part2-only/work/6b/89851958ed451b0577ffd601aa02da]
>Mar-23 10:39:22.023 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 10:44:17.803 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 4; name: MACS2 (Amy_C2_763_C1); status: RUNNING; exit: -; err or: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/ batch1-part2-only/work/6b/89851958ed451b0577ffd601aa02da]
>Mar-23 10:44:22.031 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 10:49:17.888 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 4; name: MACS2 (Amy_C2_763_C1); status: RUNNING; exit: -; err or: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/ batch1-part2-only/work/6b/89851958ed451b0577ffd601aa02da]
>Mar-23 10:49:22.036 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 10:54:18.148 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 4; name: MACS2 (Amy_C2_763_C1); status: RUNNING; exit: -; err or: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/ batch1-part2-only/work/6b/89851958ed451b0577ffd601aa02da]
>Mar-23 10:54:22.043 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 10:54:22.191 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task c ompleted > TaskHandler[id: 4; name: MACS2 (Amy_C2_763_C1); status: COMPLETED; ex it: 0; error: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Se q/results/batch1-part2-only/work/6b/89851958ed451b0577ffd601aa02da]
>Mar-23 10:54:22.201 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
>Mar-23 10:54:22.225 [Task submitter] INFO  nextflow.Session - [f7/845986] Submit ted process > MACS2 (HP_C2_763_C1)
>Mar-23 10:54:22.227 [Task submitter] DEBUG n.processor.TaskPollingMonitor - %% e xecutor local > tasks in the submission queue: 2 -- tasks to be submitted are sh own below ~> TaskHandler[id: 6; name: MACS2 (VTA_C2_763_C1); status: NEW; exit: -; error: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/batc h1-part2-only/work/7c/b189bcd2254dfccfe720ca859b5ef9] ~> TaskHandler[id: 7; name: MACS2 (FR_CTX_C2_763_C1); status: NEW; exit: -; erro r: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/b atch1-part2-only/work/9e/bce55c99a28190e0d1d1d90748792c]
>Mar-23 10:59:18.009 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 5; name: MACS2 (HP_C2_763_C1); status: RUNNING; exit: -; erro r: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/b atch1-part2-only/work/f7/8459866cc5b14760931ae5d82c732e]
>Mar-23 10:59:22.052 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 11:04:18.043 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 5; name: MACS2 (HP_C2_763_C1); status: RUNNING; exit: -; erro r: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/b atch1-part2-only/work/f7/8459866cc5b14760931ae5d82c732e]
>Mar-23 11:04:22.058 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 11:09:18.106 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 5; name: MACS2 (HP_C2_763_C1); status: RUNNING; exit: -; erro r: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/b atch1-part2-only/work/f7/8459866cc5b14760931ae5d82c732e]
>Mar-23 11:09:22.065 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 11:14:18.171 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 5; name: MACS2 (HP_C2_763_C1); status: RUNNING; exit: -; erro r: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/b atch1-part2-only/work/f7/8459866cc5b14760931ae5d82c732e]
>Mar-23 11:14:22.071 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 11:19:18.232 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 5; name: MACS2 (HP_C2_763_C1); status: RUNNING; exit: -; erro r: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/b atch1-part2-only/work/f7/8459866cc5b14760931ae5d82c732e]
>Mar-23 11:19:22.077 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 11:19:37.041 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task c ompleted > TaskHandler[id: 5; name: MACS2 (HP_C2_763_C1); status: COMPLETED; exi t: 0; error: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq /results/batch1-part2-only/work/f7/8459866cc5b14760931ae5d82c732e]
>Mar-23 11:19:37.053 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
>Mar-23 11:19:37.053 [Task submitter] INFO  nextflow.Session - [7c/b189bc] Submit ted process > MACS2 (VTA_C2_763_C1)
>Mar-23 11:19:37.055 [Task submitter] DEBUG n.processor.TaskPollingMonitor - %% e xecutor local > tasks in the submission queue: 1 -- tasks to be submitted are sh own below ~> TaskHandler[id: 7; name: MACS2 (FR_CTX_C2_763_C1); status: NEW; exit: -; erro r: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/b atch1-part2-only/work/9e/bce55c99a28190e0d1d1d90748792c]
>Mar-23 11:24:18.251 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 6; name: MACS2 (VTA_C2_763_C1); status: RUNNING; exit: -; err or: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/ batch1-part2-only/work/7c/b189bcd2254dfccfe720ca859b5ef9]
>Mar-23 11:24:22.085 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled
>Mar-23 11:29:18.348 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! exe cutor local > tasks to be completed: 1 -- pending tasks are shown below ~> TaskHandler[id: 6; name: MACS2 (VTA_C2_763_C1); status: RUNNING; exit: -; err or: -; workDir: /home/groups/hpcbio/projects/pandey/2018-March-ChIP-Seq/results/ batch1-part2-only/work/7c/b189bcd2254dfccfe720ca859b5ef9]
>Mar-23 11:29:22.091 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No mor e task to compute -- Execution may be stalled

**Comment by pditommaso** [comment] 2018-03-24 10:46
Please attach the complete `.nextflow.log` file.

**Comment by grendon** [comment] 2018-03-24 21:47
Hi.
First of all, thank you for the reply.
I just rerun it today because I had tried other things between then and now.
The log of this run reproduced the problem I alluded to earlier in this post.
[nextflow.log](https://github.com/nextflow-io/nextflow/files/1844830/nextflow.log)

**Comment by pditommaso** [comment] 2018-03-26 06:47
It looks your workflow is using both slurm and local executor. Since the system on which you are running it has only 1 cpu (?), the local executor allows only a task a time. 

There are two solution: 1) remore the use of the local executor is not needed; 2) increase the local executor queue size. 

(I'm closing this because it's not related anymore with the original issue. Feel free to comment below if needed).

**Closed by pditommaso** 2018-03-26 06:47 UTC
