### ISSUE TITLE
publishDir directive enabled flag is ignored

### ISSUE THREAD

**Issue by paulderaadt** [nextflow-io/nextflow#1434] opened 2020-01-02 09:01 UTC
### Expected behavior and actual behavior

publishDir "path", enabled: false
Should supress the files being published, but they get published regardless.

### Steps to reproduce the problem
```
#!/usr/bin/env nextflow


chan = Channel.from([1, 2, 3])

params.publish = false
process test_something {
    publishDir "test/", enabled: params.publish

    input:
    val x from chan
    echo true
    output:
    file("*") into chen
    script:
    if (params.publish) { 
    println "publishing"
    }
    """
    echo $x > ${x}.txt
    """

}
```
### Program output 
```
N E X T F L O W  ~  version 19.07.0
Launching main.nf [grave_brahmagupta] - revision: 33ede48541
executor >  local (3)
[62/c98b1b] process > test_something (3) [100%] 3 of 3 ✔


 ls test/

1.txt  2.txt  3.txt
```

### Environment 

* Nextflow version: [19.07.0] 
* Java version: [
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
]
* Operating system: [Linux]

`if (params.publish) 
{
publishDir "path"
}`
does work but makes for uglies code.

**Comment by pditommaso** [comment] 2020-01-03 15:22
This looks a duplicate of #1381. Can you try the latest snapshot?

**Comment by paulderaadt** [comment] 2020-01-03 16:02
> This looks a duplicate of #1381. Can you try the latest snapshot?

Using NF from https://github.com/nextflow-io/nextflow/releases/tag/v19.12.0-edge seems to fix the issue, thank you.

**Comment by pditommaso** [comment] 2020-01-03 16:04
Excellent.

**Closed by pditommaso** 2020-01-03 16:04 UTC
