### ISSUE TITLE
Docker cpus runtime option

### ISSUE THREAD

**Issue by bugh1** [nextflow-io/nextflow#1829] opened 2020-12-11 00:37 UTC
Currently Nextflow supports specifying cpu and memory directives in a process block. When Nextflow is running on a 'local' executor and the process is specified to run in a container, Nextflow appends a '--memory' command line argument to the Docker run command (the .command.run file shows this) when a memory directive is specified. However, the cpus directive does not do something similar, and the container is running in an enviroment not limited by the cpus specified. 

Is this a bug or a feature not implemented? The [DockerBuilder](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/container/DockerBuilder.groovy) class where '--memory' seems to be added has an option where '--cpuset' can get added, but it looks like that is not triggered by specifying the cpus directive. If this is a feature not implemented perhaps '--cpus' could be added on to the docker run command?

**Comment by pditommaso** [comment] 2020-12-21 15:10
Done. Duplicate of #1832

**Closed by pditommaso** 2020-12-21 15:10 UTC
