### ISSUE TITLE
update default defaultBranch to main

### ISSUE THREAD

**Issue by ahvigil** [nextflow-io/nextflow#3994] opened 2023-06-02 01:14 UTC
## New feature

The last few years have seen many projects move from `master` to `main` as the default project branch. Notably [github](https://github.com/github/renaming) and [gitlab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/) now use `main` as the default branch for new repos. Sensitive issues of historical and cultural significance aside, does it make sense to update the default branch name in nextflow to reflect this updated and commonly used convention? This is now the default on 2 of the 3 cloud version control providers mentioned in the documentation for the manifest scope (and github is arguably the largest and most influential of these).

On the other hand, I believe the default behavior of `git` itself is to continue using `master` for newly created repos unless configured otherwise via `init.defaultBranch`, and as far as I know bitbucket still uses that convention as well (though both have added the ability to override that). I could see the default behavior of `git init` as a compelling reason to maintain the current nextflow manifest default.

## Usage scenario 

This may be mostly a cosmetic issue as I'm not entirely sure what the manifest defaultBranch gets used for?

## Suggest implementation 

update the constant at https://github.com/nextflow-io/nextflow/blob/1daebeef025f45b8e9e5cab62e783ddb3327118f/modules/nf-commons/src/main/nextflow/Const.groovy#L145 along with various references to `master` in tests and function defaults.

**Comment by ahvigil** [comment] 2023-09-15 17:03
looks like https://github.com/nextflow-io/nextflow/issues/1670 is related

**Comment by bentsherman** [comment] 2023-11-01 17:32
Duplicate of #3593, in the other issue I suggested that Nextflow accept both `master` and `main` as default branches

**Closed by bentsherman** 2023-11-01 17:32 UTC
Labels: software/git
