### ISSUE TITLE
Bug with nxf_unstage() module only with storeDir directive in Nextflow v22.04.3 || Urgent 

### ISSUE THREAD

**Issue by luisovallex** [nextflow-io/nextflow#2912] opened 2022-05-28 03:00 UTC
### Expected behavior and actual behavior

Expected behavior it's to store the files on S3 using storeDir directive, but the actual behavior it's the pipeline crashing because Nextflow cannot find the output files.

During the debugging process we tested the pipeline with the publishDir directive and everything looks to be fine, so we decide to go trough the work directory and check for the .command.run scripts to see the difference between the execution with publishDir and storeDir, we saw a couple of differences between the codes:

This is the .command.run file generated when running the pipeline with publishDir:
[publishdir.txt](https://github.com/nextflow-io/nextflow/files/8790385/publishdir.txt)

And this is the one generated when running the pipeline with storeDir:
[workdir.txt](https://github.com/nextflow-io/nextflow/files/8790386/workdir.txt)

There are many differences, but the one I don't get it's related with the nxf_s3_upload and nxf_s3_download, because storedir file has this functions and publishdir do not.

After checking and comparing these files we decide to test the storeDir .command.run file by going inside the container, edit the file and then run it manually and we come to the conclusion that the main issue it's related to this piece of code:

```
nxf_unstage() {
    true
    cp .command.out /mnt/efs/ngs_scratch/workdir/210812_NB501331_0892_AH57FVBGXK/updated-path4/14/96e35fb77d096c4ca2d3291e49b398/.command.out || true
    cp .command.err /mnt/efs/ngs_scratch/workdir/210812_NB501331_0892_AH57FVBGXK/updated-path4/14/96e35fb77d096c4ca2d3291e49b398/.command.err || true
    cp .command.trace /mnt/efs/ngs_scratch/workdir/210812_NB501331_0892_AH57FVBGXK/updated-path4/14/96e35fb77d096c4ca2d3291e49b398/.command.trace || true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
    IFS=$'\n'
    for name in $(eval "ls -1d L1.Aligned.sortedByCoord.out.bam L1.Chimeric.out.sam L1.Chimeric.out.junction L1.Log.final.out" | sort | uniq); do
        nxf_s3_upload '$name' s3://k8s-temporal-efs/results/210812_NB501331_0892_AH57FVBGXK/A01-00159459-VL45582-A-d/align/L1 || true
    done
    unset IFS
}
```

After changing the '$name' to "$name", we were able to push all the files required during the container running and finally nextflow will mark this processes as succeeded. 
### Steps to reproduce the problem

NXF_VER=22.04.3 nextflow run [any file with storeDir directive using S3 as storage, no matter if is a small file].nf 

One of the processes is similar to this one:

```
params.resuls = 's3://my-bucket-name/results'

process alignment {
        echo true
        tag { sample_name + ":" + lane_id }

        maxRetries 3
        errorStrategy 'retry'

        storeDir { "${params.results}/$runid/$sample_name/align/$lane_id" }

        input:
                file reference
                set sample_name, sample_id, lane_id, file(read1), file(read2) from fastqs
                //val k from kickoff.first()
                val k from kickoff

        output:
                set sample_name, file ("${lane_id}.Aligned.sortedByCoord.out.bam")  into alignments
                set sample_name, file ("${lane_id}.Chimeric.out.sam")  into fusion_sams
                set sample_name, file ("${lane_id}.Chimeric.out.junction")  into fusion_jxns
                set sample_name, file ("${lane_id}.Log.final.out")  into star_logs
                set sample_name, sample_id, lane_id  into meta

        script:
                template "alignment.sh"
}
```
This is the script for the process, needs to be changed to a .sh file:
[alignment.txt](https://github.com/nextflow-io/nextflow/files/8790749/alignment.txt)

### Program output 

Application message:

`Missing output file(s) `L1.Aligned.sortedByCoord.out.bam` expected by process `alignment (A01-00159459-VL45582-A-d:L1)` -- Execution is retried (2)`

.nextflow.log:

```
May-28 02:07:55.466 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 8; name: alignment (A01-00159459-VL45582-A-d:L1); status: COMPLETED; exit: 0; error: -; workDir: /mnt/efs/ngs_scratch/workdir/210812_NB501331_0892_AH57FVBGXK/storedir-fix6/0b/7c799e85ec9c865eb1e78bd9022e51]
May-28 02:07:55.563 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process `alignment (A01-00159459-VL45582-A-d:L1)` is unable to find [S3Path]: `/k8s-temporal-efs/results2/210812_NB501331_0892_AH57FVBGXK/A01-00159459-VL45582-A-d/align/L1/L1.Aligned.sortedByCoord.out.bam` (pattern: `L1.Aligned.sortedByCoord.out.bam`)
May-28 02:07:55.564 [Task monitor] INFO  nextflow.processor.TaskProcessor - [0b/7c799e] NOTE: Missing output file(s) `L1.Aligned.sortedByCoord.out.bam` expected by process `alignment (A01-00159459-VL45582-A-d:L1)` -- Execution is retried (2)
```

[.nextflow.log](https://github.com/nextflow-io/nextflow/files/8790364/default.nextflow.log)

### Environment 

* Nextflow version: 22.04.3
* Java version: Openjdk 11.0.14.1 2022-02-08 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14.1+1-LTS, mixed mode, sharing)
* Operating system: Linux

### Additional context

I'm moving a Nextflow pipeline from AWS Batch to AWS EKS and also upgrading the version from 20.01.0 to 22.04.3, I want to keep most of the things (related to nextflow configuration and main.nf files) as they are on AWS Batch and one of the most important things it's to use S3 with the storeDir directive for many processes. With almost the same configuration for the main.nf file I'm not able to do it and ends in a pipeline crashing. In the Additional context I will add more details about how we solve this problem and what needs to me changed.

Hope this is enough to demonstrate my request, if not please feel free to ask everything you need to know. 
Thanks

**Comment by bentsherman** [comment] 2022-06-30 20:58
Possible duplicate of #2790

**Closed** 2022-07-11 19:29 UTC
Labels: storage/aws-s3
