### ISSUE TITLE
.command.log is missing in process work dir when executor is k8s.

### ISSUE THREAD

**Issue by pdp10** [nextflow-io/nextflow#4257] opened 2023-09-01 11:14 UTC
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

The expected behaviour is that `.command.log` should be generated in the process work directory for any chosen executor.
The actual behaviour is that `.command.log` is missing when using `k8s` executor. Note that they are generated using the `local` executor.

These are the files generated in a work directory using `k8s` executor: 
```
root@pipeline-67999df957-v5fhl:/work/nextflow/92/454301ca0bde676736aa013748bf0e# ls -lart 
total 148
drwxr-xr-x 3 root root   6144 Sep  1 10:43 ..
-rw-r--r-- 1 root root   5270 Sep  1 10:51 .command.run
-rw-r--r-- 1 root root    684 Sep  1 10:51 .command.sh
-rw-r--r-- 1 root root      0 Sep  1 10:51 .command.begin
-rw-r--r-- 1 root root      0 Sep  1 10:52 .command.out
-rw-r--r-- 1 root root      0 Sep  1 10:52 .command.err
-rw-r--r-- 1 root root      1 Sep  1 10:52 .exitcode
```
The process completed correctly (exit code is 0). 

Note: I only tested the executors: `local` and `k8s`. It could be that this issue occurs for other executors.

### Steps to reproduce the problem
Switch executor from `local` to `k8s` and check the presence of `.command.log`.

### Program output 
There is nothing abnormal in the main `nextflow.log`.

### Environment 

* Nextflow version: 23.04.2 build 5870 
* Java version: 11.0.18
* Operating system: Debian 5.10.149-2 (2022-10-21)
* Bash version: 5.1.4

**Comment by bentsherman** [comment] 2023-09-01 13:51
Duplicate of #2364

**Closed by bentsherman** 2023-09-01 13:51 UTC
Labels: platform/k8s
