### ISSUE TITLE
K8s permission problems for scripts in `bin` folder

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#698] opened 2018-05-14 23:18 UTC
Hi Paolo,

For the same pipeline that work no problem on LSF I get a permission error when running on K8s:
```
[warm up] executor > k8s
[f7/cf7557] Submitted process > irods (ImmHet6564351)
[c3/bac014] Submitted process > irods (ImmHet6564353)
[41/cbf3d4] Submitted process > irods (ImmHet6564350)
[d8/815486] Submitted process > irods (ImmHet6564354)
[09/a15092] Submitted process > irods (ImmHet6564352)
ERROR ~ Error executing process > 'irods (ImmHet6564351)'

Caused by:
  Process `irods (ImmHet6564351)` terminated with an error exit status (126)

Command executed:

  irods.sh ImmHet6564351

Command exit status:
  126

Command output:
  (empty)

Command error:
  .command.stub: line 38: ps: command not found
  .command.sh: line 2: /mnt/gluster/projects/cellgeni/rnaseq-noqc/bin/irods.sh: Permission denied
  .command.stub: line 27: ps: command not found
  .command.stub: line 12: ps: command not found
  .command.stub: line 99:    32 Terminated              nxf_trace "$pid" .command.trace
```
When I look in the local version of the pipeline the file permissions are not executable:
```
ubuntu@vlad-k8s-test-k8s-master-nf-1:/mnt/gluster/pvc-319c8c17-3ca6-11e8-89b1-fa163e31bb09$ ls -la projects/cellgeni/rnaseq-noqc/bin/
total 24
drwxr-xr-x  2 root root 4096 May 14 23:13 .
drwxr-xr-x 10 root root 4096 May 14 23:13 ..
-rw-r--r--  1 root root 3647 May 14 23:13 dupRadar.r
-rw-r--r--  1 root root 2271 May 14 23:13 edgeR_heatmap_MDS.r
-rw-r--r--  1 root root 3763 May 14 23:13 gtf2bed
-rw-r--r--  1 root root  305 May 14 23:13 irods.sh
-rw-r--r--  1 root root  994 May 14 23:13 markdown_to_html.r
-rw-r--r--  1 root root 2912 May 14 23:13 merge_featurecounts.py
-rw-r--r--  1 root root  542 May 14 23:13 merge_salmon.R
```
In a local version of the same pipeline on the LSF farm all these files are executable:
```
vk6@bc-26-3-14:/lustre/scratch117/cellgen/cellgeni/tic-24test$ ls -la ~/.nextflow/assets/cellgeni/rnaseq-noqc/bin/
total 36
drwxr-sr-x  2 vk6 team218 4096 May 14 21:25 .
drwxr-sr-x 10 vk6 team218 4096 May 14 17:18 ..
-rwxr-xr-x  1 vk6 team218 3647 Apr 23 17:38 dupRadar.r
-rwxr-xr-x  1 vk6 team218 2271 Apr 23 17:38 edgeR_heatmap_MDS.r
-rwxr-xr-x  1 vk6 team218 3763 Apr 23 17:38 gtf2bed
-rwxr-xr-x  1 vk6 team218  305 May 14 21:25 irods.sh
-rwxr-xr-x  1 vk6 team218  994 Apr 23 17:38 markdown_to_html.r
-rwxr-xr-x  1 vk6 team218 2912 Apr 23 17:38 merge_featurecounts.py
-rwxr-xr-x  1 vk6 team218  542 Apr 24 22:54 merge_salmon.R
```

**Comment by pditommaso** [comment] 2018-05-15 07:04
Sure, you have commit that scripts with execute permission?

**Comment by pditommaso** [comment] 2018-05-15 07:08
More the message ` ps: command not found` signals that you are using a container which does not include the `ps` tool. Make sure to add gnu coretools or at least the `procps` package.

**Comment by wikiselev** [comment] 2018-05-15 09:33
Thanks Paolo, the `procps` thing makes sense. What base image do your recommend that will contain all necessary things? `ubuntu:latest`? At the moment this container uses `FROM continuumio/miniconda`

**Comment by pditommaso** [comment] 2018-05-15 09:40
That's fine, make sure to add `apt-get install procps`

**Comment by wikiselev** [comment] 2018-05-16 00:40
Hi Paolo, it didn't help... I still get `permission denied` error:
```
Command error:
  .command.sh: line 2: /mnt/gluster/projects/cellgeni/rnaseq-noqc/bin/irods.sh: Permission denied
  .command.stub: line 98:    32 Terminated              nxf_trace "$pid" .command.trace
```

The files are definitely executable:
```
> ls cellgeni/rnaseq-noqc/bin
total 56
drwxr-xr-x   9 vk6  1307   288B 14 May 16:59 .
drwxr-xr-x  17 vk6  1307   544B 16 May 00:24 ..
-rwxr-xr-x   1 vk6  1307   3.6K 23 Apr 11:13 dupRadar.r
-rwxr-xr-x   1 vk6  1307   2.2K 23 Apr 11:13 edgeR_heatmap_MDS.r
-rwxr-xr-x   1 vk6  1307   3.7K 23 Apr 11:13 gtf2bed
-rwxr-xr-x   1 vk6  1307   305B 14 May 21:24 irods.sh
-rwxr-xr-x   1 vk6  1307   994B 23 Apr 11:13 markdown_to_html.r
-rwxr-xr-x   1 vk6  1307   2.8K 23 Apr 11:13 merge_featurecounts.py
-rwxr-xr-x@  1 vk6  1307   542B 24 Apr 22:40 merge_salmon.R
```
and `procps` is also installed: https://github.com/cellgeni/irods/blob/7768fab02e5e2663de94bf610b295525ef03c23a/Dockerfile#L3

**Comment by wikiselev** [comment] 2018-05-16 10:16
Hi Paolo, it looks like the permissions are not pulled from the Github correctly, because if I change the permission of the files manually on K8s everything works just file. And the script is defined as executable on Github: https://github.com/cellgeni/rnaseq-noqc/blob/master/bin/irods.sh

**Comment by pditommaso** [comment] 2018-05-16 10:17
Weird, being just use `bash /path/to/irods.sh` instead.

**Comment by HelenCousins** [comment] 2018-05-16 10:56
I did
 git clone https://github.com/HelenCousins/nextflow.git
and ls -l nextflow/bin:
-rwxr-xr-x 1 root root 155 May 16 10:44 myiinit.sh

I used
NXF_VER=0.30.0-SNAPSHOT nextflow kuberun HelenCousins/nextflow -v testpvc:/home

and ls -l projects/HelenCousins/nextflow/bin/

-rw-r--r-- 1 root root 155 May 15 19:37 myiinit.sh


It has certainly lost its +x, which it has in on gitHub, and when cloned normally.

**Comment by HelenCousins** [comment] 2018-05-16 12:27
I tried cloning it from inside a pod (not a nextflow pod though) and it remain executable.

**Comment by pditommaso** [comment] 2018-05-17 08:07
This is hardly a NF issue. It could be more problem related with the gluster/k8s file system permission. 

However I would suggest to execute it prefixing the script with the `bash` interpreted. This should solve the problem. Could you please confirm.

**Comment by pditommaso** [comment] 2018-05-29 15:18
I'm closing this because there's any more feedback. Feel free to comment below if needed.

**Closed by pditommaso** 2018-05-29 15:18 UTC
Labels: platform/k8s, triage/needs-information

**Comment by wikiselev** [comment] 2018-06-11 14:40
Hi @pditommaso , I can now confirm that adding `bash` to the scripts worked! Thanks, Vlad

**Comment by wikiselev** [comment] 2018-07-30 14:01
Apparently the `bash` solution above only worked for bash scripts. For other scripts like python or R we found the following solution. In the process script the the full path to the file should be defined like e.g.:
```
python $workflow.projectDir/bin/script.py
```
Looks like `$workflow.projectDir/bin` is the only way to access the `bin` directory, we tried some other workarounds but they didn't work.

**Comment by pditommaso** [comment] 2018-07-30 14:04
You need to check: 

1) the `<projectDir>/bin` folder in the container `$PATH`
2) the target script has executable permission

**Comment by wikiselev** [comment] 2018-07-30 14:10
1. Is ok
2. As far as we can see `glusterfs` changes permission of the files in the `bin` folder during pulling from GitHub. The scripts are executable on GitHub, but are not executable on `glusterfs`. Maybe NF user needs more rights?

**Comment by pditommaso** [comment] 2018-07-30 14:14
> The scripts are executable on GitHub, but are not executable on glusterfs 

That's bad. I think you need to investigate why this is happening. Is this a feature or a bug? 

> Maybe NF user needs more rights?

From NF point of view is just Bash invoking your script over the directories defined by `$PATH`.

**Comment by jambler24** [comment] 2021-02-16 10:48
Having the same issue with a python script in the bin folder. 

N E X T F L O W  ~  version 20.07.1
Singularity image

`Error executing process > 'post_roary (1)'

Caused by:
  Process `post_roary (1)` terminated with an error exit status (1)

Command executed:

  chmod -x post_roary.py
  post_roary.py --phenotype_data sample_sheet_FsD_dichotomized.csv

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 2: /users/jambler/.nextflow/assets/jambler24/bac_pangenome/bin/post_roary.py: Permission denied
`

Would advise re-opening the issue, seems like it is also referenced on gitter with no reasonable solution. The assumption is that a script in the bin folder can be executed.

**Comment by darachmiller** [comment] 2024-03-04 19:27
Here in 2024 having the same issue. I moved a script to `bin/` based on reading this: https://training.nextflow.io/advanced/structure/
and I couldn't get it to run. Permission denied. 

Using Singularity-run-from-docker-image, with `autoMount` true, `runOptions` of `--no-home --bind /scratch` (the parent of directory in which I'm working). `bin/` and the python script have the right permissions (a+rx). If I don't include it as a process input then I don't see the script in the work directory with a `ls` in the script, before attempting to run it.

What works is `combine`-ing it in as a `Channel.from([file('bin/script.py')])`

FYI
