### ISSUE TITLE
containerOptions shm-size is expecting a different kind of value when using Docker with AWS Batch executor

### ISSUE THREAD

**Issue by mriffle** [nextflow-io/nextflow#5196] opened 2024-08-01 19:03 UTC
## Bug report 

When specifying the `shm-size` containerOption, Docker is expecting the number of bytes. However, I when the executor is AWS Batch, I believe Nextflow is expecting this to be the number of MiB

### Expected behavior and actual behavior

The expected behavior is that the units of this parameter would not depend on the executor.

### Environment 

* Nextflow version: [24.04.3] 
* Java version: [openjdk version "11.0.24" 2024-07-16]
* Operating system: [Linux]
* Bash version: (GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu))

**Comment by pditommaso** [comment] 2024-08-01 19:11
This has been addressed in version 24.04.4 https://github.com/nextflow-io/nextflow/releases/tag/v24.04.4

**Comment by pditommaso** [comment] 2024-08-01 19:13
Duplicate of https://github.com/nextflow-io/nextflow/issues/5176

**Comment by mriffle** [comment] 2024-08-01 19:16
I think this is a little different. If I specify a `shm-size` of 1000, that will be over 1g when the executor is awsbatch, but only 1000 bytes everywhere else. Or am I wrong?

**Comment by pditommaso** [comment] 2024-08-01 19:19
You can specify either as byte or with a unit suffix, when using 24.04.4 it will be converted in both cases to MB in the Bath Job request

**Comment by mriffle** [comment] 2024-08-01 19:20
Awesome, thanks for the clarification.

**Comment by pditommaso** [comment] 2024-08-01 19:21
You are welcome. Closing this. Feel free to comment/re-open if needed

**Closed by pditommaso** 2024-08-01 19:21 UTC
