### ISSUE TITLE
Setting dumpHashes=false in nextflow.config is still taking it as true since version 23

### ISSUE THREAD

**Issue by pavan-kotha-strandls** [nextflow-io/nextflow#5277] opened 2024-09-03 06:55 UTC
## Bug report 

Setting dumpHashes=false in nextflow.config is still taking it as true since version 23

### Expected behavior and actual behavior

Adding the config option dumpHashes=true in the nextflow.config displays the cache info.
And setting dumpHashes=false should not show the cache info.
Since version 23, dumpHashes=true or dumpHashes=false is displaying the cache info

### Steps to reproduce the problem

Add "dumpHashes=true" in the nextflow.config

### Program output 

With dumpHashes = true
===================
N E X T F L O W  ~  version 22.10.6
Launching `main.nf` [evil_darwin] DSL2 - revision: 2cf4c0373d
[-        ] process > direct   [  0%] 0 of 1
[-        ] process > indirect [  0%] 0 of 1
[direct] cache hash: 2996df33c3a5b88dfb8574989f42b504; mode: STANDARD; entries: 
  352d083f11116b85530cbb6783ceb95d [java.util.UUID] 67db2a0e-0946-499d-bb06-a7d4882e582c 
  53bbb7b30375adebc635ea07115af7e2 [java.lang.String] direct 
  c8428201a4ee4269986c694535a5da50 [java.lang.String] """
    echo direct process execution
    echo "start"
    cat $txt
    echo "end"
    """
 
  9b1d4a4998845c9455de9d7cf21ca8c0 [java.lang.String] ubuntu 
  004dbab739fdc524666b238b10af0573 [java.lang.String] txt 
  6bec26aa34af13f449b4992ca05dbd95 [nextflow.util.ArrayBag] [FileHolder(sourceObj:/home/pavan/Documents/projects/frontend/nextjs/ed-methylation-app/cache-test-1/nextflow.config, storePath:/home/pavan/Documents/projects/frontend/nextjs/ed-methylation-app/cache-test-1/nextflow.config, stageName:nextflow.config)] 
  4f9d4b0d22865056c37fb6d9c2a04a67 [java.lang.String] $ 
  16fe7483905cce7a85670e43e4678877 [java.lang.Boolean] true
=================

With dumpHashes=false

N E X T F L O W  ~  version 22.10.6
Launching `main.nf` [voluminous_tuckerman] DSL2 - revision: 2cf4c0373d
executor >  local (2)
[ba/175a29] process > direct   [100%] 1 of 1 ✔
[e7/4ce5c6] process > indirect [100%] 1 of 1 ✔
===========
 N E X T F L O W   ~  version 24.04.4

Launching `main.nf` [loving_mestorf] DSL2 - revision: 2cf4c0373d

executor >  local (2)
[eb/605cf8] direct   [  0%] 0 of 1
[77/2fb30b] indirect [  0%] 0 of 1
[direct] cache hash: f22c9139a528c5b8224280be97c57f89; mode: STANDARD; entries: 
[direct] cache hash: f22c9139a528c5b8224280be97c57f89; mode: STANDARD; entries: 
  2e10b3c47341b378078a1c958a10b0a3 [java.util.UUID] 97962f09-aa34-4c22-b8dc-ecf54e8249fc 
  53bbb7b30375adebc635ea07115af7e2 [java.lang.String] direct 
  c1357db044c963c9028e03ff65fa8067 [java.lang.String]     """
    echo direct process execution
    echo "start"
    cat $txt
    echo "end"
    """
 
  9b1d4a4998845c9455de9d7cf21ca8c0 [java.lang.String] ubuntu 
  004dbab739fdc524666b238b10af0573 [java.lang.String] txt 
  ff375f05706058b1c024432fae074a54 [nextflow.util.ArrayBag] [FileHolder(sourceObj:/home/pavan/Documents/projects/frontend/nextjs/ed-methylation-app/cache-test-1/nextflow.config, storePath:/home/pavan/Documents/projects/frontend/nextjs/ed-methylation-app/cache-test-1/nextflow.config, stageName:nextflow.config)] 
  4f9d4b0d22865056c37fb6d9c2a04a67 [java.lang.String] $ 
  16fe7483905cce7a85670e43e4678877 [java.lang.Boolean] true 

==========
### Environment 

* Nextflow version: 23+
* Java version: 11.0.13 2021-10-19
* Operating system: Linux
* Bash version: 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

This a very serious issue. The entire pipeline process scripts are printed to the output log.
Since AWS HealthOmics has updated to version 23, any pipeline shared this way with the clients is printing the full pipeline details.

**Comment by pditommaso** [comment] 2024-09-03 07:16
Closing because the issue is unreadable for lack for formatting and test case to replicate the issue.

**Closed by pditommaso** 2024-09-03 07:16 UTC

**Comment by pavan-kotha-strandls** [comment] 2024-09-03 08:43
Run a basic hello world nextflow workflow with dumpHashes=true and dumpHashes=false and compare the console log or .nextflow.log. (It will be the same)
Now run the same with version 22.04.0. (Hashes will not be printed with dimpHashes=false)
