### ISSUE TITLE
beforeScript is not executed in docker container

### ISSUE THREAD

**Issue by tsangacw** [nextflow-io/nextflow#339] opened 2017-05-10 22:51 UTC
I've a small script to setup environment variables and would like to run it before the process' script.  ```beforeScript``` would be perfect, in fact, it works when I'm not using docker.  I checked the ```.command.run```, it simply executes the beforeScript there, and it's not in ```command.run.1```.

Is there a way I can source the script for both docker & non-docker environment?

**Comment by pditommaso** [comment] 2017-05-11 17:13
Unfortunately, that is not possible. `beforeScript` is executed outside the scope of the task script by design.

**Comment by pditommaso** [comment] 2017-05-12 13:05
I'm closing this issue. Feel free to comment below if needed.

**Closed by pditommaso** 2017-05-12 13:05 UTC

**Comment by tsangacw** [comment] 2017-05-12 16:18
why is it not executed in docker?  can we expose a flag in like ```docker.beforeScript=true``` so it'll run in docker container instead?

**Comment by pditommaso** [comment] 2017-05-16 22:10
Because the `beforeScript` is executed in the context of the wrapper script launches the container. It looks like that you want to prefix your process' scripts with common prefix prolog instead. 

You could do that by using a custom function that you can invoke from the process, eg: 

```
def myCustomTemplate( script ) {
  'prefix code here\n' + script
}


process foo {
  script: 
  myCustomTemplate """
  task_script_here
  """"
}
```
