### ISSUE TITLE
Nextflow resume crash with Can't create cache DB

### ISSUE THREAD

**Issue by aghozlane** [nextflow-io/nextflow#309] opened 2017-03-23 12:32 UTC
I use nextflow 0.24.0, and the resume crash if I use an other submission configuration (with -c).
```
N E X T F L O W  ~  version 0.24.0                                    
Launching `blast_approach.nf` [dreamy_noether] - revision: 9cc789a538
ERROR ~ Can't create cache DB: /pasteur/homes/aghozlan/blast_approach/.nextflow/cache/3f2411fe-9c55-40bb-99c6-40511baa0700/db
```
I tried to get back at my initial configuration with no success. Nextflow keep sending me same error.

**Comment by pditommaso** [comment] 2017-03-23 13:03
Can you in include the full stack trace that you can find it the
.nextflow.log file.

**Comment by aghozlane** [comment] 2017-03-23 13:06
here is it.
[nextflow.log.7.txt](https://github.com/nextflow-io/nextflow/files/864758/nextflow.log.7.txt)

**Comment by pditommaso** [comment] 2017-03-23 13:14
It looks that the lock file is still there

```
/pasteur/homes/aghozlan/blast_approach/.nextflow/cache/3f2411fe-9c55-40bb-99c6-40511baa0700/db/LOCK
```

Are you sure there's no a instance? Another reason it could be that a previous run has been stopped abruptly. 

I have you older log files (.nextflow.log.xx) and you are willing to share them, upload them here so that I can try to investigate the cause.

**Comment by aghozlane** [comment] 2017-03-23 13:20
Yes, nextflow was stopped abrutly. There was no available node, so I stopped the submit with a control +C and resubmit on another queue. I tried to disconnect and to reconnect, to remove files in the cache..

[nextflow.log.1.txt](https://github.com/nextflow-io/nextflow/files/864792/nextflow.log.1.txt)
[nextflow.log.2.txt](https://github.com/nextflow-io/nextflow/files/864791/nextflow.log.2.txt)
[nextflow.log.3.txt](https://github.com/nextflow-io/nextflow/files/864794/nextflow.log.3.txt)
[nextflow.log.4.txt](https://github.com/nextflow-io/nextflow/files/864795/nextflow.log.4.txt)
[nextflow.log.5.txt](https://github.com/nextflow-io/nextflow/files/864793/nextflow.log.5.txt)
[nextflow.log.6.txt](https://github.com/nextflow-io/nextflow/files/864790/nextflow.log.6.txt)

**Comment by pditommaso** [comment] 2017-03-23 13:43
Does removing that file solve your problem?

**Comment by aghozlane** [comment] 2017-03-23 13:46
It was impossible. I did a rm -rf but it said that le file was not empty. And I cannot get a root access.

**Comment by pditommaso** [comment] 2017-03-23 13:48
I'm confused, `was` or `is`. Also why you don't permission to remove it. It should belong to your user.

**Comment by aghozlane** [comment] 2017-03-23 13:59
I'm confused too. At the second try,
First, just tried to remove LOCK
rm /pasteur/homes/aghozlan/blast_approach/.nextflow/cache/3f2411fe-9c55-40bb-99c6-40511baa0700/db/LOCK
I get:
../nextflow run blast_approach.nf --in /pasteur/projets/specific/PFGE_activites/NGS/NGS_RawData/PLACENTA_cleaning/raw_reads/ --out /pasteur/projets/specific/PFGE_activites/NGS/NGS_RawData/PLACENTA_cleaning/blast_analysis/final2/ --cpus 6 -w /pasteur/scratch/amine/work_final/ -c nextflow_slurm_hub.config -resume 
N E X T F L O W  ~  version 0.24.0
Launching `blast_approach.nf` [nauseous_cori] - revision: 9cc789a538
ERROR ~ Can't create cache DB: /pasteur/homes/aghozlan/blast_approach/.nextflow/cache/2f0e37ea-1f2b-4767-b580-accc52f568f6/db

 -- Check '.nextflow.log' file for details
then remove everything in that directory
rm -rf /pasteur/homes/aghozlan/blast_approach/.nextflow/cache/2f0e37ea-1f2b-4767-b580-accc52f568f6/db/*

../nextflow run blast_approach.nf --in /pasteur/projets/specific/PFGE_activites/NGS/NGS_RawData/PLACENTA_cleaning/raw_reads/ --out /pasteur/projets/specific/PFGE_activites/NGS/NGS_RawData/PLACENTA_cleaning/blast_analysis/final2/ --cpus 6 -w /pasteur/scratch/amine/work_final/ -c nextflow_slurm_hub.config -resume 
N E X T F L O W  ~  version 0.24.0
Launching `blast_approach.nf` [big_curran] - revision: 9cc789a538
[warm up] executor > slurm
[bb/e45b79] Submitted process > fastqfiltering (2)
Project : /pasteur/homes/aghozlan/blast_approach
Cmd line: nextflow run blast_approach.nf --in /pasteur/projets/specific/PFGE_activites/NGS/NGS_RawData/PLACENTA_cleaning/raw_reads/ --out /pasteur/projets/specific/PFGE_activites/NGS/NGS_RawData/PLACENTA_cleaning/blast_analysis/final2/ --cpus 6 -w /pasteur/scratch/amine/work_final/ -c nextflow_slurm_hub.config -resume
[c2/b1b3f5] Submitted process > fastqfiltering (4)
[5b/5478b6] Submitted process > fastqfiltering (1)
[8c/3d3514] Submitted process > fastqfiltering (3

And I completely lost my history

**Comment by pditommaso** [comment] 2017-04-05 16:59
I'm closing this issue since there's any more feedback. Feel free to comment/reopen it if needed.

**Closed by pditommaso** 2017-04-05 16:59 UTC

**Comment by danielecook** [comment] 2020-01-11 07:27
I am having a similar issue

Here is the stack trace:

```
n-11 07:05:39.190 [Actor Thread 13] WARN  nextflow.processor.TaskProcessor - [wf_alignment:trim_fqs (LTX0019_TH_BO03--b1b72e02hfnt-6)] Unable to resume cached task -- See log file for details
org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.lang.RuntimeException: Could not open table 20550
	at org.iq80.leveldb.impl.DbImpl.checkBackgroundException(DbImpl.java:421)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:584)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:577)
	at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:156)
	at nextflow.CacheDB$getTaskEntry$5.call(Unknown Source)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:829)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:718)
	at sun.reflect.GeneratedMethodAccessor423.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:553)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:58)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Could not open table 20550
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:98)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.util.Level0Iterator.<init>(Level0Iterator.java:47)
	at org.iq80.leveldb.impl.VersionSet.makeInputIterator(VersionSet.java:210)
	at org.iq80.leveldb.impl.DbImpl.doCompactionWork(DbImpl.java:1040)
	at org.iq80.leveldb.impl.DbImpl.backgroundCompaction(DbImpl.java:491)
	at org.iq80.leveldb.impl.DbImpl.backgroundCall(DbImpl.java:436)
	at org.iq80.leveldb.impl.DbImpl.access$100(DbImpl.java:85)
	at org.iq80.leveldb.impl.DbImpl$2.call(DbImpl.java:404)
	at org.iq80.leveldb.impl.DbImpl$2.call(DbImpl.java:398)
	at java.util.concurrent.FutureT
```

**Comment by danielecook** [comment] 2020-01-11 09:16
Is it possible to rebuild the cache?

**Comment by pditommaso** [comment] 2020-01-13 12:51
I think it's the same of #1358. Fixed in the current master.
