### ISSUE TITLE
Non-interactive cloud shutdown?

### ISSUE THREAD

**Issue by alanbchristie** [nextflow-io/nextflow#789] opened 2018-07-10 10:17 UTC
I'm automating my cloud infrastructure using classic tools like Packer, Terraform and Ansible and I can invoke Nextflow's `create` a cluster non-interactively by adding `-y` (cool) but I cannot seem to call `shutdown` without being presented with a prompt.

If it can't be done with the current code can we have a `-y` option for `shutdown` so that cluster destruction can be more easily automated?

Oh - and can the shutdown wait for the resources it created to get deleted before it finishes?

**Comment by pditommaso** [comment] 2018-07-10 10:45
This is a duplicate of #596

**Closed** 2018-07-10 15:24 UTC
