### ISSUE TITLE
Timeline.html is not working on IE11

### ISSUE THREAD

**Issue by Mkimha** [nextflow-io/nextflow#272] opened 2017-01-05 10:42 UTC
Hi,
I would like to report an issue concerning the timeline.html file generated with NextFlow using "-with-timeline" option.
When I try to display the Timeline in a browser ( Tested on IE11 and FireFox 32), it only shows:

![capture](https://cloud.githubusercontent.com/assets/24935121/21677746/c4fe4848-d33b-11e6-8638-cd48dee2fe54.PNG)

How can I fix this?

Thank you for your help.

**Comment by pditommaso** [comment] 2017-01-20 10:34
I'm unable to reproduce the error on Firefox (the latest version it works fine and version 32 is not available anymore). I would suggest to upgrade your browser. 

To render on IE11 add the following line at the beginning of the html script section: 

     <meta http-equiv="X-UA-Compatible" content="IE=edge" />

It will be included in the next NF release. Thanks for reporting the problem.

**Closed by pditommaso** 2017-01-20 10:34 UTC

**Comment by pditommaso** [comment] 2017-01-23 23:47
Included in version `0.23.1`
