### ISSUE TITLE
GitLab auth token is not applied when user credentials are not provided 

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#542] opened 2017-12-01 23:40 UTC
Using nextflow 0.26.3 I can no longer pull from a gitlab repo.  The same command works in version 0.25.7.  Here's the stacktrace with the repo names obscured.

```
Dec-01 19:05:27.019 [main] DEBUG nextflow.cli.Launcher - $> /usr/local/bin/nextflow run http://ZZZZZ/SGI-Pipelines/something.git -resume -hub gitlab -r aws_changes -latest -params-file /mnt/efs/nextflow/run.0a0a85ee-f4cb-4c90-ae7e-ce277ba9e016/params.yaml -process.executor slurm
Dec-01 19:05:27.333 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.26.3Dec-01 19:05:27.807 [main] DEBUG nextflow.scm.AssetManager - Repository URL: http://ZZZZZ/SGI-Pipelines/something.git; Project: SGI-Pipelines/something; Hub provider: gitlabDec-01 19:05:27.815 [main] INFO  nextflow.cli.CmdRun - Pulling SGI-Pipelines/something ...
Dec-01 19:05:27.819 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> http://ZZZZZ/api/v3/projects/SGI-Pipelines%2Fsomething
Dec-01 19:05:27.964 [main] DEBUG nextflow.scm.RepositoryProvider - Response status: 401 -- {"message":"401 Unauthorized"}
Dec-01 19:05:27.972 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> http://ZZZZZ/api/v3/projects/SGI-Pipelines%2Fsomething
Dec-01 19:05:28.027 [main] DEBUG nextflow.scm.RepositoryProvider - Response status: 401 -- {"message":"401 Unauthorized"}
Dec-01 19:05:28.030 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Not authorized -- Check that the GitLab user name and password provided are correct
        at nextflow.scm.RepositoryProvider.checkResponse(RepositoryProvider.groovy:147)
        at nextflow.scm.RepositoryProvider.invoke(RepositoryProvider.groovy:110)
        at nextflow.scm.RepositoryProvider.memoizedMethodPriv$invokeAndParseResponseString(RepositoryProvider.groovy:174)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)        at nextflow.scm.RepositoryProvider$_closure1.doCall(RepositoryProvider.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)        at sun.reflect.NativeM
ethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)        at nextflow.scm.RepositoryProvider$_closure1.doCall(RepositoryProvider.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)        at sun.reflect.NativeM
ethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java
:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:134)
        at groovy.lang.Closure.call(Closure.java:430)
        at nextflow.scm.RepositoryProvider.invokeAndParseResponse(RepositoryProvider.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
1 change; before #2  3 seconds ago       
```

**Comment by pditommaso** [comment] 2017-12-02 08:01
It should be caused by #457. Should not you specify the user name name password (other the auth token) to authenticate with GitLab?

**Comment by mes5k** [comment] 2017-12-03 17:11
The repo is marked as `public` in gitlab, so I shouldn't need to login (I'm not even clear on why I need the token for a public repo, but that's a separate issue). Regardless, up until this point I haven't needed a user or password to clone the repo.  I haven't studied the code closely, but it seems like there might just be two disjoint paths for gitlab logins:  1. using user + password and 2. using the token.

**Comment by pditommaso** [comment] 2017-12-04 16:14
I see. Maybe the solution here is to override the [hasCredentials](https://github.com/nextflow-io/nextflow/blob/issue_515-docker-user/src/main/groovy/nextflow/scm/RepositoryProvider.groovy#L54-L56) method so that it returns `true` only when `config.token` is specified. 

What do you think ?

**Comment by msmootsgi** [comment] 2017-12-04 17:08
So, something like this in [GitlabRepositoryProvider](https://github.com/nextflow-io/nextflow/blob/issue_515-docker-user/src/main/groovy/nextflow/scm/GitlabRepositoryProvider.groovy)?
```
    boolean hasCredentials() {
        config ? config.token || (config.user && config.password) : false
    }
```
That seems like it would work in my case.  Definitely worth a shot!

**Comment by pditommaso** [comment] 2017-12-04 17:26
I've realised that's no good. Because that method is invoked to check is the credentials need to specified when cloning the repo. 

I think it would be enough to modify the [auth](https://github.com/nextflow-io/nextflow/blob/issue_515-docker-user/src/main/groovy/nextflow/scm/GitlabRepositoryProvider.groovy#L47-47) method as followoing: 

```
      if( config.token ) {
            // set the token in the request header
            connection.setRequestProperty("PRIVATE-TOKEN", config.token)
        }
```

**Comment by msmootsgi** [comment] 2017-12-04 19:03
I'd guess that would work too.  If you can create a snapshot, I should be able to test pretty easily.  At your leisure, I've just reverted to 0.25.7 for now.

**Comment by pditommaso** [comment] 2017-12-04 19:37
Uploaded `0.26.4-SNAPSHOT`

**Comment by msmootsgi** [comment] 2017-12-04 19:42
Yes, that worked!

**Comment by pditommaso** [comment] 2017-12-04 19:43
running some tests me too

**Closed** 2017-12-05 06:50 UTC
