### ISSUE TITLE
Allow authentication to weblog endpoint

### ISSUE THREAD

**Issue by seandavi** [nextflow-io/nextflow#3242] opened 2022-09-23 20:03 UTC
## New feature

In a cloud environment, there is a need to secure URLs. While one way of doing this is to simply use a VPC, another is to support simple authentication via bearer token, basic auth in a header. 

## Usage scenario 

See above.

## Suggest implementation 

Adding a "header" component in the weblog config block that nextflow includes in the post would address most basic use cases of securing the web endpoint.

**Comment by bentsherman** [comment] 2022-09-26 20:21
Duplicate of #3198

**Closed by bentsherman** 2022-09-26 20:21 UTC
Labels: triage/duplicate
