### ISSUE TITLE
K8s pod command is broken in Nextflow 22.10.1

### ISSUE THREAD

**Issue by courcelm** [nextflow-io/nextflow#3365] opened 2022-11-08 16:04 UTC
## Bug report 

Nextflow 22.10.1 now uses arguments instead of command in pod manifest. This breaks all execution if the entrypoint of the container is not a shell.

### Expected behavior and actual behavior

In Nextflow version 22.04.3:

  - command:
    - /bin/bash
    - -ue
    - .command.run

In Nextflow version 22.10.1:

  - args:
    - /bin/bash
    - -ue
    - /mnt/nextflow/comet/5392/work/1c/8b1f1127dc7f5d6f89a77732c26834/.command.run

There are two changes.
* command for args - this is causing a major problem
* full path of the command

The expected configuration should be:

  - command:
    - /bin/bash
    - -ue
    - /mnt/nextflow/comet/5392/work/1c/8b1f1127dc7f5d6f89a77732c26834/.command.run

### Environment 

* Nextflow version: 22.10.1
* Java version: [?]
* Operating system: Linux, Kubernetes 1.22.11
* Bash version: (use the command `$SHELL --version`)

**Comment by pditommaso** [comment] 2022-11-08 16:20
duplicate of https://github.com/nextflow-io/nextflow/discussions/3357

**Closed by pditommaso** 2022-11-08 16:20 UTC
