### ISSUE TITLE
AWS Batch: nextflow does not respect AWS_PROFILE variable

### ISSUE THREAD

**Issue by dtenenba** [nextflow-io/nextflow#860] opened 2018-09-07 20:09 UTC
## Bug report 

(If you a reporting a bug please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

I have multiple AWS profiles in my `~/.aws/credentials` and `~/.aws/config` files, and none are
set as the default, by design (this reduces the possibility of doing something in the wrong account by accident). When I want to work with one profile, I do:

```
export AWS_PROFILE=profilename
```

in the shell I'm working in. This always works fine with the AWS CLI, boto3, etc. 
It does not work with nextflow (see error text in next section).

If I back up my `~/.aws` files and create one that has only a single (default) profile,
the job starts fine.

`AWS_PROFILE` is documented here: 
https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

### Program output 

```
$ nextflow run main.nf -w s3://bucket-name-censored/dtenenba/nextflow-tests/
N E X T F L O W  ~  version 0.31.1
Launching `main.nf` [jovial_mestorf] - revision: 2522c5d504
ERROR ~ Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 71E3656AC03CA663; S3 Extended Request ID: PX3KdFIF219oli9mWNLHqOHucyl9/SUwSsLNXPdtdtHshxGVO7mXqxhrMV8JfaTdw5SqxK79i90=)

 -- Check '.nextflow.log' file for details

```

### Steps to reproduce the problem

1. Back up and then remove `~/.aws/config` and `~/.aws/credentials`
2. run `aws configure --profile=nondefault`. Provide valid AWS credentials/region.
3. run `export AWS_PROFILE=nondefault`
4. run `aws s3 ls` just to prove that the AWS CLI respects the `AWS_PROFILE` variable.
5. run any nextflow job that uses AWS batch, you'll see output similar to the above.

### Environment 

* Nextflow version: 0.31.1
* Java version: 1.8.0_101
* Operating system: macOS 10.13.6

**Comment by pditommaso** [comment] 2018-09-08 16:06
This a kind of duplicate of #423. I was not aware of `AWS_PROFILE` variable, it should be quite straighforward to support it.

**Closed** 2019-08-24 10:00 UTC
Labels: help wanted, kind/enhancement, nfhack18, platform/aws-batch, platform/aws-ec2
