### ISSUE TITLE
collectFile doesn't work with watchPath but does with fromPath

### ISSUE THREAD

**Issue by nick297** [nextflow-io/nextflow#338] opened 2017-05-10 14:12 UTC
I want to use .collectFile to aggregated files from a process which runs from a .watchFile Channel. This doesn't work, is there a setting I need to use? It works as expected when using Channel.fromPath

**Comment by pditommaso** [comment] 2017-05-10 14:16
I guess the problem is that `watchFile` never stops, thus `collectFile` cannot finalize the file merge operation.

**Comment by nick297** [comment] 2017-05-10 14:23
OK, thanks, I should probably figure out an alternate method for this

**Comment by pditommaso** [comment] 2017-05-10 19:49
I'm closing this. Feel free to comment below if needed.

**Closed by pditommaso** 2017-05-10 19:49 UTC
