### ISSUE TITLE
Nextflow clone does not work with certain revisions

### ISSUE THREAD

**Issue by mhrvol** [nextflow-io/nextflow#3240] opened 2022-09-23 14:32 UTC
## Bug report 

nextflow clone command does not work with branches/commits 

nextflow clone -h specifies this:

    -r
       Revision to clone - It can be a git branch, tag or revision number

### Expected behavior and actual behavior

Expected: Correct revision is successfully cloned

Actual: Folder with .git is created, everything else is missing

### Steps to reproduce the problem

Console log (first expected result - without '-r', then various examples of '-r' usage):

% nextflow clone https://github.com/nextflow-io/hello        
nextflow-io/hello cloned to: hello...
% ls hello
LICENSE         README.md       circle.yml      main.nf         nextflow.config
% rm -rf hello
% nextflow clone https://github.com/nextflow-io/hello -r mybranch
nextflow-io/hello cloned to: hello ...
% ls hello
% rm -rf hello
% nextflow clone https://github.com/nextflow-io/hello -r 4eab81bd42eed592f4371cd91b755ec78df25fe9
nextflow-io/hello cloned to: hello42eed592f4371cd91b755ec78df25fe9 ...
% $?
zsh: command not found: 0
% ls hello
% ls -A hello
.git
% cd hello
% git checkout mybranch
error: pathspec 'mybranch' did not match any file(s) known to git
% git branch -a
  remotes/origin/master
% cd ..
% rm -rf hello
% nextflow clone https://github.com/nextflow-io/hello -r v1.1                                    
nextflow-io/hello cloned to: hello
% ls hello
LICENSE         README.md       main.nf

### Program output 

See 'Steps to reproduce the problem'

### Environment 

* Nextflow version: [22.04.5.5708] 
* Java version: [11]
* Operating system: [macOS]
* Bash version: zsh 5.8.1 (x86_64-apple-darwin21.0)

**Comment by bentsherman** [comment] 2023-11-01 17:26
Duplicate of #1987

**Closed by bentsherman** 2023-11-01 17:26 UTC
Labels: pinned, software/git
